### ISSUE TITLE
"Do not use Development Server in Production Environment"

### ISSUE THREAD

**Issue by ezebaida** [miguelgrinberg/microblog#102]
Miguel,
I have a very basic knowledge of Python and have just gone through your first article. While I can get the local page to work correctly, I am getting this warning along with "Use a production WSGI instead". Is this something that you addressed and I may have missed? 
Thanks

**Comment by ezebaida** [comment]
needed to run a command that reads
$ export FLASK_ENV=development

**Comment by miguelgrinberg** [comment]
FLASK_ENV is a new thing that was introduced in Flask 1.0 a couple of days ago. The warning that you get is correct, the development server should not be used in production. But you are using it for development, so it is not a problem.
