### ISSUE TITLE
ch17 missing closing quotes 

### ISSUE THREAD

**Issue by krupnikola** [miguelgrinberg/microblog#111]
Hi Miguel,
Minor issue, closing quotes are missing on the command for generating random secret key in ubuntu server:

![selection_008](https://user-images.githubusercontent.com/38564674/41149454-e8dc8266-6b0b-11e8-84ae-e0b0cc76719b.png)

Cheers!

**Comment by miguelgrinberg** [comment]
Looks like I missed to update this in the ebook. It has been updated on my blog. Thanks!
