### ISSUE TITLE
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1044, "Access denied for user 'microblog'@'%' to database 'microblog'") (Background on this error at: http://sqlalche.me/e/e3q8)

### ISSUE THREAD

**Issue by boyl** [miguelgrinberg/microblog#113]
![image](https://user-images.githubusercontent.com/30596191/41771812-e21cb1c4-7648-11e8-89fb-cc4a82ad3a08.png)
I deploy it use docker follow you， this problem I have no idea

**Comment by miguelgrinberg** [comment]
The error suggests that the database user for the microblog app is not set up correctly in your database.

Did you create the database container earlier or at about the same time? If the database was just created, it can take a few seconds for it to fully complete its own initialization, so the microblog container may error trying to access the database. For that reason I have implemented the retries every 5 seconds. If this does not succeed after a few retries, then you need to review the database container, in particular the configuration for the microblog user.

**Comment by boyl** [comment]
@miguelgrinberg 
Thanks so much! It’s problem exactly you say that name of the database  does not match.
I benefit a lot from your blog tutorial ,it’s really great. thank you for much again.
