### ISSUE TITLE
To me, it seems to be and instead of or, because does it make sense to initialize auth if password field does not have any value?

### ISSUE THREAD

**Issue by Sp-NNT** [miguelgrinberg/microblog#116]
https://github.com/miguelgrinberg/microblog/blob/36a393c816695e738ef5a1e40a3ad045dffa07c6/app/__init__.py#L20

**Comment by miguelgrinberg** [comment]
What if you only need to pass a token in the username field? That is a common way to pass authentication for some services.

**Comment by Sp-NNT** [comment]
Considering these 2 cases, I would have written `if app.config['MAIL_USERNAME']`.
Case1, when we have username and password fields filled: we are checking emptiness of these fields, and it would be logic, if we put to clause `and`, but you said that we might pass a token in the username field, therefore we miss password field.
Case2, when we have a token in the username field: we have to consider only username field. In that case, when we write ` if app.config['MAIL_USERNAME'] or app.config['MAIL_PASSWORD']:` the condition returns true even if username is empty and password is not empty.

**Comment by miguelgrinberg** [comment]
You are welcome to code this check any way you want. I prefer to make it as flexible as possible, thus allowing credentials to be passed in both fields, or either one of them.

**Comment by Sp-NNT** [comment]
I am very grateful to you for not leaving any of my questions unanswered, good luck!
