### ISSUE TITLE
Chapter 8 - test config using .flaskenv

### ISSUE THREAD

**Issue by Bruce1979** [miguelgrinberg/microblog#119]
Attempting to run `tests.py` as explained in the tutorial raises errors related to not loading the config object using values from `.flaskenv`:

```
(venv) $ python3 tests.py 
Traceback (most recent call last):
  File "tests.py", line 3, in <module>
    from app import app, db
  File "/basedir/app/__init__.py", line 2, in <module>
    from config import Config
  File "/basedir/config.py", line 3, in <module>
    class Config(object):
  File "/basedir/config.py", line 8, in Config
    MAIL_PORT = int(os.environ.get('MAIL_PORT'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
since app.config['MAIL_PORT'] is `None` (i.e. not set). However, `flask shell` and `flask run` both run fine, and load the config values from `.flaskenv` as intended.

When running `tests.py`, `print(app.config)` produces:
```
<Config {'ENV': 'production', 'DEBUG': False, ..., **'ADMINS': None, 'MAIL_PASSWORD': None, 'MAIL_SERVER': None, 'MAIL_USERNAME': None, 'MAIL_USE_TLS': None, 'SQLALCHEMY_DATABASE_URI': None, 'SQLALCHEMY_TRACK_MODIFICATIONS': False**}>
```

When running `flask run` or `flask shell`, `print(app.config)` produces:
```
<Config {'ENV': 'production', 'DEBUG': True, ..., **'ADMINS': "['admin@mail.com']", 'MAIL_PASSWORD': '', 'MAIL_PORT': 8025, 'MAIL_SERVER': 'localhost', 'MAIL_USERNAME': '', 'MAIL_USE_TLS': True, 'SQLALCHEMY_DATABASE_URI': 'sqlite:////full/path/to/app.db', 'SQLALCHEMY_TRACK_MODIFICATIONS': False}**>
```

*Relevant files:*
basedir/tests.py:
```
from datetime import datetime, timedelta
import unittest
from app import app, db
from app.models import User, Post

class UserModelCase(unittest.TestCase):
  def setUp(self):
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite://'
    # NOTE - config being used for tests is NOT as specified in .flaskenv
    db.create_all()

  def tearDown(self):
    db.session.remove()
    db.drop_all()
...
```
basedir/microblog.py
```
from app import app, db
from app.models import User, Post

@app.shell_context_processor
def make_shell_context():
  return {'db': db, 'User': User, 'Post': Post}
```
basedir/config.py
```
import os

class Config(object):
    SECRET_KEY = os.environ.get('SECRET_KEY')
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    MAIL_SERVER = os.environ.get('MAIL_SERVER')
    MAIL_PORT = os.environ.get('MAIL_PORT')
    MAIL_USE_TLS = os.environ.get('MAIL_USE_TLS')
    MAIL_USERNAME = os.environ.get('MAIL_USERNAME')
    MAIL_PASSWORD = os.environ.get('MAIL_PASSWORD')
    ADMINS = os.environ.get('ADMINS')
```
Note no fallbacks in above config file since all properties are set to valid values in `.flaskenv` (as demonstrated by working site using `flask run` and tested using shell with `flask shell`.

basedir/.flaskenv
```
FLASK_DEBUG = 1
FLASK_APP = 'microblog.py'
SECRET_KEY = 'my_secret'
DATABASE_URL = 'sqlite:///full/path/to/app.db'
MAIL_SERVER = 'localhost'
MAIL_PORT = '8025'
MAIL_USE_TLS = 1
MAIL_USERNAME = ''
MAIL_PASSWORD = ''
ADMINS = ['admin@mail.com']
```
basedir/app/__init__.py
```
from flask import Flask
from config import Config
...

# app and config
app = Flask(__name__)
app.config.from_object(Config)

# database
db = SQLAlchemy(app)
migrate = Migrate(app, db)
...
```

How do I ensure that the flask environment variables from `.flaskenv` are loaded into the `Config` object when running `tests.py`, as they do when using `flask run`? Given `dot-env` files are a suggested configuration option, an explanation of differences when they are being used in situations like this would be a useful addition to the tutorial.

**Comment by miguelgrinberg** [comment]
The `.flaskenv` file is imported by the `flask` command, it will not be imported if you run a different script such as `tests.py`.

You can manually import this file at the top of `tests.py` though:

```python
from dotenv import load_dotenv
load_dotenv('.flaskenv')
```

**Comment by Bruce1979** [comment]
Thank Miguel - that's useful to know. I haven't really explored the doting package before, and realise that while this isn't something you'd necessarily do in production, it's handy to have a simple workflow when in dev. Cheers!

**Comment by miguelgrinberg** [comment]
Absolutely, in fact I prefer to not rely on Flask autoimporting .env files and instead i explicitly import it, as you will see later in the tutorial!
