### ISSUE TITLE
docker build failure 

### ISSUE THREAD

**Issue by larrycai** [miguelgrinberg/microblog#121]
I clone the latest code and do `docker build .`, it reports error

<pre>
..
Step 7/16 : RUN venv/bin/pip install gunicorn pymysql
 ---> Running in 83a49880f60b
Collecting gunicorn
  Downloading https://files.pythonhosted.org/packages/8c/da/b8dd8deb741bff556db53902d4706774c8e1e67265f69528c14c003644e6/gunicorn-19.9.0-py2.py3-none-any.whl (112kB)
Collecting pymysql
  Downloading https://files.pythonhosted.org/packages/a7/7d/682c4a7da195a678047c8f1c51bb7682aaedee1dca7547883c3993ca9282/PyMySQL-0.9.2-py2.py3-none-any.whl (47kB)
Collecting cryptography (from pymysql)
  Downloading https://files.pythonhosted.org/packages/22/21/233e38f74188db94e8451ef6385754a98f3cad9b59bedf3a8e8b14988be4/cryptography-2.3.1.tar.gz (449kB)
Requirement already satisfied: idna>=2.1 in ./venv/lib/python3.6/site-packages (from cryptography->pymysql) (2.6)
Collecting asn1crypto>=0.21.0 (from cryptography->pymysql)
  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
Requirement already satisfied: six>=1.4.1 in ./venv/lib/python3.6/site-packages (from cryptography->pymysql) (1.11.0)
Collecting cffi!=1.11.3,>=1.7 (from cryptography->pymysql)
  Downloading https://files.pythonhosted.org/packages/e7/a7/4cd50e57cc6f436f1cc3a7e8fa700ff9b8b4d471620629074913e3735fb2/cffi-1.11.5.tar.gz (438kB)
    Complete output from command python setup.py egg_info:

        No working compiler found, or bogus compiler options passed to
        the compiler from Python's standard "distutils" module.  See
        the error messages above.  Likely, the problem is not related
        to CFFI but generic to the setup.py of any Python package that
        tries to compile C code.  (Hints: on OS/X 10.8, for errors about
        -mno-fused-madd see http://stackoverflow.com/questions/22313407/
        Otherwise, see https://wiki.python.org/moin/CompLangPython or
        the IRC channel #python on irc.freenode.net.)
...
</pre>

I tried both in Ubuntu & Windows 7 (toolbox) platform,

<pre>
$ docker --version
Docker version 18.03.1-ce, build 9ee9f40
</pre>

**Comment by larrycai** [comment]
Could insert below line to make it pass without optimization 

<pre>
RUN apk add --no-cache --virtual .py_deps build-base python3-dev libffi-dev openssl-dev
</pre>

**Comment by miguelgrinberg** [comment]
The `pymysql` package has made some changes that require a C compiler to be available. You can install a slightly older version of this package to avoid the problem. See https://github.com/PyMySQL/PyMySQL/issues/697#issuecomment-403817794.
