### ISSUE TITLE
I keep getting the error on Chapter 16 

### ISSUE THREAD

**Issue by TheRealZircom** [miguelgrinberg/microblog#123]
I get this error:

elasticsearch.exceptions.RequestError: RequestError(400, 'number_format_exception', 'empty String')

what does this error mean? i have been having the same problem for quite a while

**Comment by miguelgrinberg** [comment]
This is an elasticsearch error. Are you writing things that look like numbers? Elasticsearch may be automatically inferring a number type from that, so then if you try to write something that is not a number you get this error.

**Comment by TheRealZircom** [comment]
No I am not. I copied the tutorial exactly the way u set it out . my body section is called content. could that be the reason?

**Comment by TheRealZircom** [comment]
I have tried everything

**Comment by TheRealZircom** [comment]
even when typing numbers in . I get this

**Comment by miguelgrinberg** [comment]
Please delete all your indexes as shown in the article, then start a new session from the Python interpreter until you get the error. Then copy the entire cli session here.

**Comment by TheRealZircom** [comment]
which cli session? I haven't implemented a language translation feature

**Comment by miguelgrinberg** [comment]
The article shows how to operate the elasticsearch index from a Python cli. This is what I was referring to. Follow the steps in the tutorial until the point you get the error, but do it using the Python session. Then I hope I will be able to see what's causing this error.

**Comment by TheRealZircom** [comment]
ok thx

**Comment by TheRealZircom** [comment]
solved issue
