### ISSUE TITLE
Problem decoding utf-8 json response in the translate.py model 

### ISSUE THREAD

**Issue by GEOpdx** [miguelgrinberg/microblog#13]
When I try to load the Microsoft Translate response into the json module it throws an error

The end of the stack trace looks like:

....\Lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

A bit of debugging revealed that the response from microsoft includes BOM characters that cause the json libary to see the returned result as invalid.  This is the line that has the issue.

        response = json.loads('{"response":' +
                              conn.getresponse().read().decode('utf-8') + '}')

I got around that by changing the decode like this:

        response = json.loads('{"response":' +
                              conn.getresponse().read().decode('utf-8-sig') + '}')

'utf-8-sig' deals with the extra characters.

I am on windows 7 and am trying to figure out if this issue is related to that or other environmental elements.  This seems like a problem someone else should have also had if it was related to the code in your tutorial.

**Comment by miguelgrinberg** [comment]
It could be that the MS translator service started sending the BOM characters recently, or maybe the httplib package is not skipping those bytes as it should. Using `utf-8-sig` is the right thing to do for this, as this encoding works with or without BOM.
