### ISSUE TITLE
Chapter 4 : NameError exceptions when you access db, User and Post

### ISSUE THREAD

**Issue by pes3** [miguelgrinberg/microblog#131]
Hello,

I have added a .flaskenv  to my project, yet when running 

```
`(venv) $ flask shell
>>> `db``
```
I get the NameError still.

Anyone else find a another fix?

**Comment by miguelgrinberg** [comment]
That is not the only thing you need to do, you also have to add a shell context processor function. See https://github.com/miguelgrinberg/microblog/blob/master/microblog.py#L8-L11.
