### ISSUE TITLE
ImportError: cannot import name 'Post' from 'app.models'

### ISSUE THREAD

**Issue by JanZaplatil** [miguelgrinberg/microblog#132]
Ok so i am following your flask tutorial. But i have modified it a bit to suit my specific needs. So you will understand that it is not completely the same. 

So the problem:

1: (venv) $ pip install flask-sqlalchemy      
2: (venv) $ pip install flask-migrate
3:  i configure the database like this: 

import os
basedir = os.path.abspath(os.path.dirname(__file__))

class Config(object):
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'you-will-never-guess'
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or \
                              'sqlite:///' + os.path.join(basedir, 'app.db')
    SQLALCHEMY_TRACK_MODIFICATIONS = False

4. __init__.py  look like this
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)

from app import routes, models

5. models.py looks like this

from datetime import datetime
from app import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    description = db.Column(db.String(120), index=True, unique=True)
    start = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    password_hash = db.Column(db.String(128))

    def __repr__(self):
        return '<User {}>'.format(self.username)
6: ERROR After running coomand flask db init in terminal i get 

(venv) Jans-MBP:taskmanager janzaplatil$ flask db init
Usage: flask db init [OPTIONS]

Error: While importing "taskmanager", an ImportError was raised:

Traceback (most recent call last):
  File "/Users/janzaplatil/Desktop/microblog/venv/lib/python3.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/Users/janzaplatil/Desktop/taskmanager/taskmanager.py", line 2, in <module>
    from app.models import User, Post
ImportError: cannot import name 'Post' from 'app.models' (/Users/janzaplatil/Desktop/taskmanager/app/models.py)

what to do ? 
I have copied one project that i started and modified it on to a new one....so i think that might be a problem...

**Comment by miguelgrinberg** [comment]
You don't have a `Post` class in models.py, remove `Post` from your import.

**Comment by JanZaplatil** [comment]
How do i do this ?

**Comment by miguelgrinberg** [comment]
As I said above, you don't have a `Post` class. Why are you importing this class?

**Comment by miguelgrinberg** [comment]
It's in your stack trace:

```
File "/Users/janzaplatil/Desktop/taskmanager/taskmanager.py", line 2, in 
from app.models import User, Post
```

**Comment by JanZaplatil** [comment]
Ow thanks. Now i fell stupid :).

**Comment by miguelgrinberg** [comment]
@JanZaplatil you need to review your code. If Python imports class `User` and fails to import class `Task`, I would be inclined to believe you are incorrect in your description. I can't really help you without seeing your source code, you need to debug this yourself.

**Comment by JanZaplatil** [comment]
I would just like to let you know i found  a solution. I deleted all .pyc files and imported it again.

**Comment by miguelgrinberg** [comment]
Oh I see. Do you know why your pyc files were out of sync with the corresponding .py files?

**Comment by JanZaplatil** [comment]
this was the answer given to me regarding the problem: 


It's compiled python bytecode. Python regenerates those. Every so often, for reasons (like renaming files), you'll end up with a stale .pyc that confuses things.

**Comment by Mael242-root** [comment]
ImportError: cannot import name 'Post' from 'blog.models' (C:\simpleblog\my_blog\blog\models.py)

**Comment by Sukumaran007** [comment]
@JanZaplatil Dont worry, bro you just import 'Post' on your routes.py 
"from app.models import Post"

**Comment by hannahakinwumi** [comment]
ImportError: cannot import name 'post' from 'django.apps' (C:\Users\customer\AppData\Local\Programs\Python\Python310\lib\site-packages\django\apps\__init__.py) . please assist

**Comment by Manuzs** [comment]
I'm getting the same error for the following code on entering the command - 
from app import User, Post

**the code -**
`from flask import Flask, render_template, url_for, flash, redirect
from flask_sqlalchemy import SQLAlchemy
from forms import RegistrationForm, LoginForm
from datetime import datetime

app = Flask(__name__)
app.config['SECRET_KEY'] = '5ef9e49a4ece37050f2aefeea1a965c3'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///site.db' 
db = SQLAlchemy(app)

class User(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(20), unique =True, nullable = False)
    email = db.Column(db.String(120), unique =True, nullable = False)
    image_file = db.Column(db.String(20), unique =True, default = 'default.jpg')
    password = db.Column(db.String(60), nullable = False)
    posts = db.relationship('Post', backref = 'author', lazy = True)

    def __repr__(self) :
        return f"User('{self.username}','{self.email}', '{self.image_file}')"


class Post(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(100), nullable = False)
    date_posted = db.Column(db.DateTime, nullable = False, default = datetime.utcnow)
    content = db.Column(db.Text, nullable = False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable = False)

    def __repr__(self) :
        return f"Post('{self.title}','{self.date_posted}')"`
**the error - **
**ImportError: cannot import name 'Post' from 'app' (C:\Users\shrikant\Desktop\new_app\app.py)**

**Comment by zhangli1014** [comment]
@Manuzs  Have you adressed the issue? please supply the solution, thanks.
