### ISSUE TITLE
load_user 是什么东西啊。我登录后，一直无法正常进入，一直跳转到登录页

### ISSUE THREAD

**Issue by lovefox666** [miguelgrinberg/microblog#135]
```
@login.user_loader
def load_user(id):
    print('=========load_user===========')
    user = User.query.get(int(id))
    print('USER_LOADER', user)
    return user
```

models.py

`

from datetime import datetime
from time import time
from hashlib import md5
# 用户模型的密码，采用哈希散列值
from werkzeug.security import generate_password_hash, check_password_hash
from flask import jsonify, current_app
# 用户登录
from flask_login import UserMixin
from hashlib import md5
#import jwt
from app import db, login

#关注者关联表
followers = db.Table(
    'followers',
    db.Column('follower_id', db.Integer, db.ForeignKey('user.id')),
    db.Column('followed_id', db.Integer, db.ForeignKey('user.id'))
)

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(64))
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))

    about_me = db.Column(db.String(140))
    last_seen = db.Column(db.DateTime, default=datetime.utcnow)

    # 20181206 定义一部分微信用户数据
    #userid = db.Column(db.String(10),index = True, unique = True)
    #deptid = db.Column(db.Integer, db.ForeignKey('dept.id'))

    # 对于一对多关系，db.relationship字段通常在“一”侧定义，并且用作访问“多”的便捷方式。
    # 举例，如果有一个用户存储 u，表达式u.posts将运行一个数据库查询，返回该用户的所有帖子。
    # db.relationship的第一个参数 表示关系“多”的模型类。
    # 第二个参数backref定义将添加到“多”类的对象的字段的名称，该类指向“一”对象。
    # 第三个参数lazy定义了如何发布对关系的数据库查询    
    # posts = db.relationship('Post', backref='author', lazy='dynamic')
    posts = db.relationship('Post', backref='author',lazy='dynamic')

    followed = db.relationship(
		'User',
        secondary=followers,
        primaryjoin=(followers.c.follower_id==id),
        secondaryjoin=(followers.c.followed_id==id),
        backref=db.backref('followers', lazy='dynamic'),
        lazy='dynamic'
	)

    #__repr__ 方法用于告知Python如何打印此类的对象，这对调试很有用。
    def __repr__(self):
        #return '<User {}>'.format(self.username)
        return '<User {}, Email {}, Password_Hash {}, Posts {}>'.format(self.username, self.email, self.password_hash, self.posts)
    
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)
    
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)
    #头像
    def avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(digest, size)
    
    
    #关注
    def follow(self, user):
        if not self.is_following(user):
            self.followed.append(user)
    
    #取消关注
    def unfollow(self, user):
        if self.is_following(user):
            self.followed.remove(user)

    #正在关注的
    def is_following(self, user):
        return self.followed.filter(followers.c.followed_id==user.id).count()>0

    #获取关注的帖子
    def followed_posts(self):
        followed = Post.query.join(followers, (followers.c.followed_id == Post.user_id)).filter(followers.c.follower_id == self.id)
        own = Post.query.filter_by(user_id=self.id)
        return followed.union(own).order_by(Post.timestamp.desc())

    # 获取用户的上级部门-次于顶级部门的部门名称
    """
    def get_dept(self):
        dept = Dept.query.filter_by(id = self.deptid).first_or_404()
        #print(dept.name)
        while True:
            if (dept.parentid != 1):
               dept = Dept.query.filter_by(id = dept.parentid).first()
               #print(dept.name)
            else:
                break
            
        #print(dept)
        return dept.name
    """

class Post(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	body = db.Column(db.String(140))
	timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
	user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

	def __repr__(self):
		return '<Post {}>'.format(self.body)

class Dept(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20))
    parentid = db.Column(db.Integer)
    order = db.Column(db.Integer)
    
    def __repr__(self):
        return '<Dept {}>'.format(self.name)

@login.user_loader
def load_user(id):
    print('=========load_user===========')
    user = User.query.get(int(id))
    print('USER_LOADER', user)
    return user
`

**Comment by lovefox666** [comment]
已经解决了，是我在config里设置了APPLICATION_ROOT = '/blog'，NGINX设置可能有问题，导致表单提交的时候TOKEN异常，CSRF不匹配，错误。
去掉APPLICATION_ROOT就好了。
不过NGINX的配置，我要研究一下，如何配置二级目录（非二级域名）

**Comment by mxyzptlk-cn** [comment]
> 已经解决了，是我在config里设置了APPLICATION_ROOT = '/blog'，NGINX设置可能有问题，导致表单提交的时候TOKEN异常，CSRF不匹配，错误。
> 去掉APPLICATION_ROOT就好了。
> 不过NGINX的配置，我要研究一下，如何配置二级目录（非二级域名）

解决了就把问题关闭呀= =
