### ISSUE TITLE
python test.py error FAILED (failures=2)

### ISSUE THREAD

**Issue by fengssq** [miguelgrinberg/microblog#138]
$ python tests.py 
test_avatar (__main__.UserModelCase) ... ok
test_follow (__main__.UserModelCase) ... FAIL
test_follow_posts (__main__.UserModelCase) ... FAIL
test_password_hashing (__main__.UserModelCase) ... ok

======================================================================
FAIL: test_follow (__main__.UserModelCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 43, in test_follow
    self.assertTrue(u1.is_following(u2))
AssertionError: False is not true

======================================================================
FAIL: test_follow_posts (__main__.UserModelCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 80, in test_follow_posts
    self.assertEqual(f1,[p2,p4,p1])
AssertionError: Lists differ: [<Post Post from john>] != [<Post Post from susan>, <Post Post from david>, <Post Post from john>]

First differing element 0:
<Post Post from john>
<Post Post from susan>

Second list contains 2 additional elements.
First extra element 1:
<Post Post from david>

- [<Post Post from john>]
+ [<Post Post from susan>, <Post Post from david>, <Post Post from john>]

----------------------------------------------------------------------
Ran 4 tests in 0.216s

FAILED (failures=2)

**Comment by fengssq** [comment]
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from datetime import datetime
from app import db, login
from hashlib import md5

followers=db.Table('followers',db.Column('follower_id',db.Integer,db.ForeignKey('user.id')),
                       db.Column('followed_id',db.Integer,db.ForeignKey('user.id'))
                       )

class User(UserMixin,db.Model):
    id=db.Column(db.Integer,primary_key=True)
    username=db.Column(db.String(64),index=True,unique=True)
    email=db.Column(db.String(120),index=True,unique=True)
    password_hash=db.Column(db.String(128))
    posts = db.relationship('Post', backref='author', lazy='dynamic')
    about_me=db.Column(db.String(140))
    last_seen=db.Column(db.DateTime,default=datetime.utcnow)

    followed=db.relationship(
        'User',secondary=followers,
        primaryjoin=(followers.c.follower_id == id),
        secondaryjoin=(followers.c.follower_id == id),
        backref=db.backref('followers',lazy='dynamic'),lazy='dynamic'
    )


    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self,password):
        self.password_hash=generate_password_hash(password)

    def check_password(self,password):
        return check_password_hash(self.password_hash,password)

    def avatar(self,size):
        digest=md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(digest,size)

    def follow(self,user):
        if not self.is_following(user):
            self.followed.append(user)
    def unfollow(self, user):
        if self.is_following(user):
            self.followed.remove(user)

    def is_following(self, user):
        return self.followed.filter(followers.c.followed_id == user.id ).count() >0

    def followed_posts(self):
        followed=Post.query.join(followers, (followers.c.followed_id ==Post.user_id)).filter(followers.c.follower_id ==self.id)
        own=Post.query.filter_by(user_id=self.id)
        return followed.union(own).order_by(Post.timestamp.desc())

class Post(db.Model):
    id=db.Column(db.Integer,primary_key=True)
    body=db.Column(db.String(140))
    timestamp=db.Column(db.DateTime,index=True,default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Post {}>'.format(self.body)
@login.user_loader
def load_user(id):
    return User.query.get(int(id))

**Comment by fengssq** [comment]
cat test.py #


from datetime import datetime,timedelta
import unittest
from app import app, db
from app.models import User,Post


class UserModelCase(unittest.TestCase):
    def setUp(self):
        app.config['SQLALCHEMY_DATABASE_URI']='sqlite://'
        db.create_all()

    def tearDown(self):
        db.session.remove()
        db.drop_all()

    def test_password_hashing(self):
        u=User(username='susan')
        u.set_password('cat')
        self.assertFalse(u.check_password('dog'))
        self.assertTrue(u.check_password('cat'))

    def test_avatar(self):
        u=User(username='john',email='john@gr.g')
        self.assertEqual(u.avatar(128),('https://www.gravatar.com/avatar/'
                                        '83efa74afb9c94ff31c8fbfda3278016?d=identicon&s=128'))

    def test_follow(self):
        u1=User(username='john',email='john@gr.g')
        u2=User(username='susan',email='susan@gr.g')
        db.session.add(u1)
        db.session.add(u2)
        db.session.commit()
        self.assertEqual(u1.followed.all(), [])
        self.assertEqual(u1.followers.all(), [])

        u1.follow(u2)
        db.session.commit()
        self.assertTrue(u1.is_following(u2))
        self.assertEqual(u1.followed.count(),1)
        self.assertEqual(u1.followed.first().username, 'susan')
        self.assertEqual(u2.followers.count(),1)
        self.assertEqual(u2.followers.first().username, 'john')

        u1.unfollow(u2)
        db.session.commit()
        self.assertFalse(u1.is_following(u2))
        self.assertEqual(u1.followed.count(),0)
        self.assertEqual(u2.followers.count(),0)

    def test_follow_posts(self):
        u1=User(username='john',email='john@gr.g')
        u2=User(username='susan',email='susan@gr.g')
        u3=User(username='mary',email='mary@gr.g')
        u4=User(username='david',email='david@gr.g')
        db.session.add_all([u1,u2,u3,u4])

        now=datetime.utcnow()
        p1=Post(body='Post from john',author=u1,timestamp=now+timedelta(seconds=1))
        p2=Post(body='Post from susan',author=u2,timestamp=now+timedelta(seconds=4))
        p3=Post(body='Post from mary',author=u3,timestamp=now+timedelta(seconds=3))
        p4=Post(body='Post from david',author=u4,timestamp=now+timedelta(seconds=2))
        db.session.add_all([p1,p2,p3,p4])
        db.session.commit()

        u1.follow(u2)
        u1.follow(u4)
        u1.follow(u3)
        u1.follow(u4)
        db.session.commit()

        f1=u1.followed_posts().all()
        f2=u2.followed_posts().all()
        f3=u3.followed_posts().all()
        f4=u4.followed_posts().all()
        self.assertEqual(f1,[p2,p4,p1])
        self.assertEqual(f2,[p2,p3])
        self.assertEqual(f3, [p3, p4])
        self.assertEqual(f4, [p4])

if __name__=='__main__':
    if __name__ == '__main__':
        unittest.main(verbosity=2)

**Comment by fengssq** [comment]
>>> u1.is_following(u2)
False
>>> u1.follow(u2)
>>> u1.is_following(u2)
False
>>> u1.is_following(u1)
False
>>> u1
<User john>
>>> u2
<User susan>
>>> u1.follow(u2)
>>> u1.is_following(u2)
False
>>> u1.follow(u2)
>>> db.session.commit()
>>> u1.is_following(u2)
False
>>>

**Comment by miguelgrinberg** [comment]
You have a problem with your follower logic, the problem is likely not in the test but in the application. Compare your code against mine to see if you can find what's wrong.

**Comment by fengssq** [comment]
> 您的跟随者逻辑存在问题，问题可能不在测试中，而是在应用程序中。将您的代码与我的代码进行比较，看看您是否能找到错误的代码。

ok，thanks,I'm checking
