### ISSUE TITLE
paginated page return 404

### ISSUE THREAD

**Issue by wedojava** [miguelgrinberg/microblog#139]
if I never use filter,everything is work right.

but if I use filter for query like below, paginated page will raise a 404 error.In document, it said 404 means no pages or .....

I printed logs before use filter,it was same after use filter.

I tracked, `logs.paginate()` will return error after use filter and click paginated pages.

```
words_email = ["%" + form.email.data + "%"]
rule = and_(*[LogImported.sender_address.like(w) for w in words_email])
logs = LogImported.query.filter(rule)
pagination = logs.paginate(page, per_page=50, error_out=True)
```

how to solve this problem please?

**Comment by miguelgrinberg** [comment]
try setting `error_out=False`

**Comment by wedojava** [comment]
> try setting `error_out=False`

I known and tried this option before,but it cannot solve this.paginated pages' response is nothing,is blank.
I mean I can only get the first page, other pages generated right,but unusable.

Maybe, paginate cannot use filter:
```python
LogImported.query.filter(rule).paginate(page, per_page=50, error_out=True)
```
only can use for `LogImported.query.paginate(page, per_page=50, error_out=True)`?

**Comment by wedojava** [comment]
> The reason you don't get additional pages is that the number of results are less than the size of the first page.

@miguelgrinberg 
yes, but how to get it? I'm sure, the result must has many pages. pages number also generate right,but click any one receive empty page.I print `LogImported.query.filter(rule)`, it same's right.

this is my code: https://github.com/wedojava/exloger

Thank you.

**Comment by miguelgrinberg** [comment]
This is likely a problem with the contents of your database, not with the code. Debug your query by running it without pagination, until you get the desired result. Then add pagination back.
