### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by DanielSank** [miguelgrinberg/microblog#14]
The (excellent!) [tutorial](http://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world) for which this project appears to be a working example is currently unavailable because of an internal server error. To avoid this in the future, it might be nice to just put the tutorial in the same repo.

**Comment by miguelgrinberg** [comment]
Must have been a temporary issue, everything works fine now.
