### ISSUE TITLE
how not to log exceptions in log file ?

### ISSUE THREAD

**Issue by zlbabe** [miguelgrinberg/microblog#140]
Hi Miguel,

First, thank you for your great work.
Can you please tell me how can I prevent the logger to store exceptions in the log file ? I'm using Sentry to catch all exceptions and I'm using the logger to log my own messages.

this is my logging configuration.

```

...

def create_app(config_file=None):
 ...

    if not app.debug:
        pathlib.Path('logs').mkdir(exist_ok=True)
        file_handler = RotatingFileHandler(
            filename='logs/website.log', maxBytes=1024*1024*10, backupCount=5)
        file_handler.setFormatter(
            logging.Formatter('%(asctime)s %(levelname)s: %(message)s'))
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)
        app.logger.setLevel(logging.INFO)

```

thanks

**Comment by miguelgrinberg** [comment]
Use a different logger for your own messages and leave the Flask logger without any handlers.

**Comment by zlbabe** [comment]
Thanks for your answer.

**Comment by simanacci** [comment]
I'm running the same code and it only logs `{"asctime": "2019-04-03 19:04:47,652", "name": "flask.app", "levelname": "INFO", "message": "Kura startup"}`. What I'm I missing?
