### ISSUE TITLE
wtforms+flask today's date as a default value

### ISSUE THREAD

**Issue by lovefox666** [miguelgrinberg/microblog#143]
`
import datetime

class EditHolidayJobForm(FlaskForm):
    jobdate = DateField(
        label='startdate',
        format='%Y-%m-%d',
        default = datetime.date.today(),
        validators = [DataRequired('please select startdate')]
    )

`
I did a small Flask app with a form with two date fields, and this is how I populate the values:
However, this is generated only once, server-side, which means that tomorrow I'll still get yesterday's date.

**Comment by miguelgrinberg** [comment]
Set the date in the constructor, not in the field definition. Something like this:

```python
class EditHolidayJobForm(FlaskForm):
    jobdate = DateField(
        label='startdate',
        format='%Y-%m-%d',
        validators = [DataRequired('please select startdate')]
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.jobdate.data:
            self.jobdate.data = datetime.date.today()
```

**Comment by lovefox666** [comment]
The problem still exists. 
`
class EditHolidayJobForm(FlaskForm):
    jobdate = DateField(
        label='startdate',
        format='%Y-%m-%d',
        validators = [DataRequired('please select startdate')]
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.jobdate.data:
            self.jobdate.data = datetime.date.today()
`
jinja2 html template like this：
`
<form action="" method="POST" class="form">
            {{ form.hidden_tag() }}
            <div class="col-xs-6 col-lg-3">
                <div class="input-group date form_date" data-date="" data-date-format="yyyy-mm-dd" data-link-field="jobdate" data-link-format="yyyy-mm-dd">
                    <input class="form-control" id="jobdate" name="jobdate" size="16" type="text" value="{{ 
form.jobdate.data }}" readonly>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                </div>
            </div>
......
`
I changed the system time of the server, Refresh Web Page. But jobdate is not  changed.

**Comment by lovefox666** [comment]
Based on your program, I modified it.
The problem has been solved. Thank you very much
