### ISSUE TITLE
 search result order by time

### ISSUE THREAD

**Issue by yuz835** [miguelgrinberg/microblog#144]
looks like the current search result is random,
how to change to list the search result order by time?

**Comment by miguelgrinberg** [comment]
Search results are sorted by relevance, not random. The SQLAlchemy query that results from the search can be modified with an `order_by` clause if you want to sort in a different way.

**Comment by yuz835** [comment]
Is this line?

class SearchableMixin(object):
    @classmethod
    def search(cls, expression, page, per_page):
        ids, total = query_index(cls.__tablename__, expression, page, per_page)
        if total == 0:
            return cls.query.filter_by(id=0), 0
        when = []
        for i in range(len(ids)):
            when.append((ids[i], i))
        **return cls.query.filter(cls.id.in_(ids)).order_by(
            db.case(when, value=cls.id)), total**

**Comment by miguelgrinberg** [comment]
It would be better if you leave the search utility functions and classes alone and code your sorting in the route:

```python
@bp.route('/search')
@login_required
def search():
    if not g.search_form.validate():
        return redirect(url_for('main.explore'))
    page = request.args.get('page', 1, type=int)
    posts, total = Post.search(g.search_form.q.data, page,
                               current_app.config['POSTS_PER_PAGE'])
    posts = posts.order_by( ... your sorting criteria here ... )             # <-----
    next_url = url_for('main.search', q=g.search_form.q.data, page=page + 1) \
        if total > page * current_app.config['POSTS_PER_PAGE'] else None
    prev_url = url_for('main.search', q=g.search_form.q.data, page=page - 1) \
        if page > 1 else None
    return render_template('search.html', title=_('Search'), posts=posts,
                           next_url=next_url, prev_url=prev_url)
```
