### ISSUE TITLE
Is threading Timer Object a bad practice?

### ISSUE THREAD

**Issue by valentin-ballester** [miguelgrinberg/microblog#148]
Hello Miguel, i have been testing in real life the app i made from your tutorials and all the flask community tutorials. I think i have never been so proud in my life like the day it was working smooth. My question is very clear, im adding a new functionality for giving a timeout for a order to live (it a app like uber, but for other industry than transportation). The thing is as im using socket i want to emit to the client that the order has timeouted and also to the delivery man, i think that threading TImer wont be as harmful to the scalability of the project because the function that is scheduled is really really small (just 2 emits and a db writing and commit) so i thought that it was ok to use it calling the timer function after a order begins. the other alternative is not to use threading but i doesnt occur to me right now how to do it without using the client front end code to send a request asking if the order he/she is seeing still exist, so what would you do ? 

PD: i ask you this on the blog comment section earlier but here i make the question more complete.

**Comment by miguelgrinberg** [comment]
Using a Timer is okay I guess, but you will need to keep track of the user that is timing out somehow. Also keep in mind that if you end up using eventlet or gevent you will need to make sure the Timer isn't blocking the async operations.

A more manageable solution is, in my opinion, to have a background task that runs at regular intervals and runs a query to find all the clients that are timed out.

**Comment by valentin-ballester** [comment]
That option seems fine, it wont be as precise as creating a timer object (but i dont really need that presition because this functionality is just for jobs that because a system overload didnt have the chance to start), but it will solve me a lot of pain in other parts of the app using something like a crontab... is crontab a possible solution ?  that runs for example every 5 minutes that loops for the orders made in the last hour and check in a 'for loop' for timeouted orders and then emits to the creator id room ? so if there is a exeptional timeout (the one im currently trying to detect) the user would notice at most 5 minutes later from the real order timeout but again, that delay is tolerable. Other option is to have a rq job with a loop on it but that seems like a waste of resources, thanks.

**Comment by valentin-ballester** [comment]
Other benefit of a cron job is that instead of a independent thread for every order i would have just one cron every 5 minutes that runs a function, maybe the cron function is a bit bigger(beause i would loop for all the orders in the last hour) but only in comparison with one of the singular function i was planning to run for every order because it really seems more eficient the crontab than if you sum the cost of computing independent threads for every order creation. so, resuming, a cron job could be factible and more efficient. dont you agree?

**Comment by valentin-ballester** [comment]
This timeout ability for my app is escential and internet is fill with different aproaches and the mayority of them dont event talk about flask. I have other parts where maybie i cant avoid using backgrounds or real timers and just use validations when neccesary but i want to explore the most common posibilities.

**Comment by miguelgrinberg** [comment]
Flask isn't really concerned with this type of thing, but this is a very common use case. As a microservice, Flask is only concerned with your HTTP routes, you need to look in general at solution that are available within Python or even the operating system. Adding a cron job seems like a good option to me!
