### ISSUE TITLE
Translation out of range error

### ISSUE THREAD

**Issue by pjdoro** [miguelgrinberg/microblog#151]
I am still receiving the error described in issue 63

'Translate' appears on posts in my language and when clicked it prints:
ArgumentOutOfRangeException: 'from' must be a valid language Parameter name: from : ID=0639.V2_Json.Translate.492EF0CB

I am using the code directly from git without any modifications -- any ideas?

**Comment by miguelgrinberg** [comment]
Does it appear on old posts, or also on new posts that you enter now?

**Comment by pjdoro** [comment]
All new posts!

**Comment by miguelgrinberg** [comment]
What is an example post that gives you this problem?

**Comment by pjdoro** [comment]
Post:
This post is in English

The translate appears as a hyperlink even though as far as I'm aware my browser is set to English
When clicked it prints the error above

**Comment by miguelgrinberg** [comment]
Can you check what language(s) your browser is set to instead of just making an assumption?

Also, try this post: `The quick brown fox jumped over the lazy dog.`. Do you get the translate link on this one too?

**Comment by pjdoro** [comment]
First off thanks for the tutorial and support you're the man!

1- Settings confirmed in Chrome>Language

2. Interestingly enough - a post with that exact text does not show the translate link. furthermore, when I google translate it to Spanish and post again the translate link renders and functions as intended (returning the English text below! Thanks so much for the help; I would love to know what you think the issue may have been. Additionally, to ensure this doesn't happen later is there a way to purge all old blog posts?

**Comment by miguelgrinberg** [comment]
The problem is in the package that detects the language, which apparently gets all confused with your example post:

```
>>> from guess_language import guess_language
>>> guess_language('This post is in English')
'la'
>>> guess_language('The quick brown fox jumped over the lazy dog.')
'en'
```

So this appears to be a language detection bug.

**Comment by pjdoro** [comment]
Thanks for walking me through that. Closing!
