### ISSUE TITLE
Error: Could not import "app. microblog"

### ISSUE THREAD

**Issue by kapoorkaran** [miguelgrinberg/microblog#155]
Hi Can you help me with the following 
 C:\Users\KaranKapoor\Desktop\microblog\app>flask run
 * Serving Flask app " microblog.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: Could not import "app. microblog".

**Comment by miguelgrinberg** [comment]
@kapoorkaran it appears you have a space before microblog in your `FLASK_APP` variable. Make sure that space is removed when you set this environment variable.

Also, you seem to be in the app directory. You should be in the microblog directory, and microblog.py should be there as well, not inside app.

**Comment by tomjjoy** [comment]
I have a similar error. Please let me know what im doing wrong. Thanks!

(venv) Thomass-MacBook-Air:microblog thomasjoy$ flask run
 * Serving Flask app "microblog.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: Could not import "microblog".

**Comment by miguelgrinberg** [comment]
@tomjjoy do you have a microblog.py file in the current directory?

**Comment by nagarajnms** [comment]
I see exactly the same issue too:

(venv) C:\Users\nagar\Desktop\microblog>flask run
 * Serving Flask app "microblog.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: Could not import "microblog".

**Comment by nagarajnms** [comment]
Wonder if this has got anything to do with the Flask Version I'm using. I have Flask 1.0.2

**Comment by miguelgrinberg** [comment]
@nagarajnms open a python shell (just type `python`) and then enter `import microblog` in the prompt. Do you get any errors?

**Comment by nagarajnms** [comment]
Hey @miguelgrinberg , I figured out the error or rather the mistake I did. :) I Had the microblog.py inside the app package. I brought it one level up and the issue got fixed.! Thanks.

**Comment by AB-Yusuf** [comment]
> Hey @miguelgrinberg , I figured out the error or rather the mistake I did. :) I Had the microblog.py inside the app package. I brought it one level up and the issue got fixed.! Thanks.

This worked!

**Comment by AB-Yusuf** [comment]
> Hey @miguelgrinberg , I figured out the error or rather the mistake I did. :) I Had the microblog.py inside the app package. I brought it one level up and the issue got fixed.! Thanks.

For those that still did not understand the solution being mentioned here, he meant put your microblog.py  in your microblog folder or directory  not in the app directory. Move the microblog.py file from the app directory to the microblog directory.

![flaskTutorial](https://user-images.githubusercontent.com/45397477/64922068-9716ec80-d7c2-11e9-9567-53317a9b3e9f.JPG)

**Comment by AB-Yusuf** [comment]
@nagarajnms   and anyone that is exploring flask newly like me. Let's communicate and build together using the microblog as a starting point. You can  Dm me via twitter:@MaestroAby

**Comment by Protosskrz** [comment]
**！Thanks to the developer！**
Error：
Usage: flask db init [OPTIONS]
Error: Could not import "microblog".

解决方法：
给英文不好的朋友留下一个解决方法，【flask db init】这个指令需要在你的项目的根目录下运行，例如你的项目路径是 【C:/migrations】,而你的终端开启的时候路径默认是【C:/】你就需要使用CD migrations进入它根目录来运行该指令

**Comment by harshitkochar20** [comment]
set FLASK_ENV=development
if this problem still exists try the above method, including all other answers .
It worked for me

**Comment by RutujaGurav07** [comment]
> Hey @miguelgrinberg , I figured out the error or rather the mistake I did. :) I Had the microblog.py inside the app package. I brought it one level up and the issue got fixed.! Thanks.

thanks it worked !!

**Comment by saraems** [comment]
I have this problem as well. My react project contains api-rest folder for the backend. But Heroku scresms: Error: Could not import "api".
<img width="180" alt="Screenshot 2021-04-09 at 13 55 11" src="https://user-images.githubusercontent.com/43315389/114176390-5ac65680-993b-11eb-8d83-3854e57df2b7.png">

**Comment by miguelgrinberg** [comment]
@saraems your `api-rest` folder needs to be in the Python import path. Did you set this up?

**Comment by saraems** [comment]
Hm, well yes. But they are in a conflict Dockerfile vs .flaskenv: <img width="451" alt="Screenshot 2021-04-09 at 17 00 51" src="https://user-images.githubusercontent.com/43315389/114200180-3bd4be00-9955-11eb-8f6b-03f742e3b80e.png">
<img width="671" alt="Screenshot 2021-04-09 at 17 01 13" src="https://user-images.githubusercontent.com/43315389/114200186-3c6d5480-9955-11eb-923f-656e32ac9127.png">

**Comment by miguelgrinberg** [comment]
@saraems This is on Heroku, right? Then the Dockerfile and .flaskenv have nothing to do with it, what matters is what's on your Procfile, which I assume has a gunicorn command? You really haven't answered my question. You have your main Flask file in a sub-directory. Have you configured Python to have that sub-directory in the import path? If you didn't, then `import api` is not going to work.

**Comment by saraems** [comment]
Ok. I think I didn't answer you @miguelgrinberg  because I didn't understand the question. 
Yes, I am trying to deploy on Heroku. 
My Procfile: `web: gunicorn api:app`
Is is the configuration for Python `heroku config:add PYTHONPATH=api-rest` ?  If so I just added. Or it's something else ?

**Comment by saraems** [comment]
Ok. Heroku sees my `api.py` now. I still have some troubles with PORT `Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch`, but I'll try to solve it. Thank you @miguelgrinberg I've been struggling with that since last week.
