### ISSUE TITLE
ImportError on Flask-Babel

### ISSUE THREAD

**Issue by Jobenas** [miguelgrinberg/microblog#156]
Hi Miguel,

I'm having trouble working with the flask_babel module. While running the whole project locally using directly the python script I can run it correctly. However, when I try to run it behind nginx, via uwsgi I get the following traceback on the uwsgi service:

`uwsgi[8342]: Traceback (most recent call last):
uwsgi[8342]:   File "./wsgi.py", line 1, in <module>
uwsgi[8342]:     from server  import app
uwsgi[8342]:   File "./server.py", line 7, in <module>
uwsgi[8342]:     from flask_babel import Babel, lazy_gettext as _l
uwsgi[8342]: ImportError: No module named flask_babel
`
I'm using virtualenv to run python and all the modules, I've already tested that the Flask-Babel module is installed by importing it in the console (while on the virtual environment). I've also tested it outside the virtual environment and have corroborated that the module is indeed installed there as well. 

I understand this is not a direct issue with Flask-Babel or any of the sort, but was wondering if you had encountered a similar issue before. Thanks a lot!

Jorge.

PS: I'm not attaching code at this point as it is my understanding that it might be some configuration issue, if it is necessary I can post my code.

**Comment by miguelgrinberg** [comment]
Did you tell uwsgi to use your virtualenv?

**Comment by Jobenas** [comment]
Hi Miguel,

Yes I did. Couldn't figure what was wrong, so I reinstalled the whole virtualenv with all the modules from scratch. That seemed to have fixed the problem. However, I couldn't figure out what was causing the problem.
