### ISSUE TITLE
Error on running individual files in the app package.

### ISSUE THREAD

**Issue by vivekanand1101** [miguelgrinberg/microblog#16]
Hi, I'm new to python and also this might not be the best place to ask this but, i am struggling.
When i run the the app by executing the run.py file, it works fine.
But, before this i tried to run views.py, just to check if i had made any syntax error, it gave this:

ImportError: No module named app

Can we import the package inside the package itself ?

**Comment by miguelgrinberg** [comment]
The `views.py` file is not meant to be executed as main script. Since `run.py` imports `views.py`, any syntax errors on that file will show up when you run the application normally.
