### ISSUE TITLE
CHAPTER 8. FOLLOWERS 

### ISSUE THREAD

**Issue by playgoods** [miguelgrinberg/microblog#160]
Dear Miguel , 

class User(UserMixin, db.Model):
# ...
followed = db.relationship(
'User', secondary=followers,
primaryjoin=(followers.c.follower_id == id),
secondaryjoin=(followers.c.followed_id == id),
backref=db.backref('followers', lazy='dynamic'), lazy='dynamic')

followers.c.follower_id == **id**    (id) What their source and why not use self.id

**Comment by miguelgrinberg** [comment]
there is no `self` in this context, that is only available when you are in a method. The `id` in this context refers to the `Column` instance.

**Comment by playgoods** [comment]
thank you :)
