### ISSUE TITLE
Elasticsearch error

### ISSUE THREAD

**Issue by 4rtcrt** [miguelgrinberg/microblog#162]
What happens if there are no results in the search? (FullText Search by Elasticsearch)
On this [your code link](https://github.com/miguelgrinberg/microblog/blob/5e9a8d7da8ffed36df9cc8735813da2dbfa10341/app/models.py#L20) variable 'ids' be empty list

**Comment by miguelgrinberg** [comment]
Nothing happens, you just get zero results in your query. Are you getting an error or some other type of problem?

**Comment by 4rtcrt** [comment]
Yes, I get an error, but I suppose this is due to the fact that I have a python 3.7 and the latest version of Elasticsearch
[However, the error occurs around here.](https://github.com/miguelgrinberg/microblog/blob/5e9a8d7da8ffed36df9cc8735813da2dbfa10341/app/models.py#L26)
For myself, I fixed this condition
`if ids == []:
    ids = [0]`

**Comment by miguelgrinberg** [comment]
Can you share the error please?

**Comment by 4rtcrt** [comment]
Yes of course
Mistake to be in the pastebin [link](https://pastebin.com/UMDbiFwr) 

You can also find all dependencies with versions in my repository in this [brach](https://github.com/4rtcrt/flask_examples/tree/code-factoring)
I am going along your guides and stopped on deployment part (I completely repeated your actions excluding pairs of trifles and parts with translation and Microsoft)

**Comment by miguelgrinberg** [comment]
Are you sure your code is identical to mine? when `ids == []` you should also have `total == 0`. There is a specific check for `total == 0` that avoids running a database query. Why isn't that condition working on your side?

**Comment by 4rtcrt** [comment]
I think problem in the version of the elasticsearch
In my case, in the `ids, total = query_index(cls.__tablename__, expression, page, per_page)`  in `total` will be dictionary with the keys `value` and `relation`
I literally immediately corrected it in the routes [(here](https://github.com/4rtcrt/flask_examples/blob/69817f6d9ed0ba97288653c4be6de1473a82d743/flask-miguel-book/microblog/main/routes.py#L145) but missed into the model.
So, now I just need to check not the `total` but the `total['value]` as I did earlier
Why so? I am almost sure that the reason is my version of Elasticsearch (or Windows specifics)

**Comment by miguelgrinberg** [comment]
@4rtcrt sorry it took me so long to catch up with you and understand.

I think I've found the problem: https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#_literal_hits_total_literal_is_now_an_object_in_the_search_response

They've changed the format of the search response in version 7, the `total` field used to be a number, now it is an object. So you did the right thing here.

I'll need to figure out how to update the code so that it works with the two versions.

**Comment by 4rtcrt** [comment]
@miguelgrinberg 
Oh, great!
You found it! As I expected, the problem is in the Elasticsearch version
Thank you, so much!
Good luck in finding a solution!
Also, you have a link to my repository and the correct branch.
I initially started working with the latest version of Python, the latest versions of all libraries and the necessary third-party software.
Use It!
