### ISSUE TITLE
Data not getting stored into the Database.

### ISSUE THREAD

**Issue by Nooria999** [miguelgrinberg/microblog#166]
I've been working on a similar project like your microblog, where I created a "personal details" (an alternative registration form) table instead of a "posts table", My web App is working perfectly, but when I try to access the stored data through the shell, I'm not getting any output or error, it just returns NULL. I've tried recreating my databases multiple times , but i'm getting the same error. Could you please help me out.

models.py :
```python
from newapp import login
from newapp import db,login
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


@login.user_loader
def load_user(id):
    return User.query.get(int(id))


class Pdetails(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    firstname = db.Column(db.String(64), index=True)
    lastname = db.Column(db.String(64), index=True)
    email = db.Column(db.String(120), index=True, unique=True)
    phone = db.Column(db.Integer, index=True, unique=True)
    gender = db.Column(db.Boolean, nullable=False, default=True)
    age = db.Column(db.Integer)
    occupation = db.Column(db.String)
    salary = db.Column(db.Integer, index=True)

    def __repr__(self):
        return '<Pdetails {}>'.format(self.firstname)
```

routes.py:
```python
from newapp import newapp, db
from flask import render_template, flash, redirect, url_for, request
from newapp.forms import LoginForm, RegistrationForm, ResetPasswordRequestForm, PdetailsForm
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.urls import url_parse
from newapp.models import User, Pdetails

.....

@newapp.route('/pdetails',methods=['GET','POST'])
def pdetails():
    form =PdetailsForm()
    if form.validate_on_submit():
        pdetails = Pdetails(email=form.email.data,firstname=form.firstname.data,lastname=form.lastname.data, phone=form.phone.data, salary=form.salary.data)
        db.session.add(pdetails)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('home'))
    return render_template('details.html', title='Personal Details',form=form)
```

**Comment by miguelgrinberg** [comment]
Please include a copy of a shell session.

**Comment by Nooria999** [comment]
![shell](https://user-images.githubusercontent.com/49098006/60015991-80209c80-96a2-11e9-88d4-b1fdc90c27fd.PNG)

**Comment by miguelgrinberg** [comment]
Al that is saying is that there is no record in this table with id=1. Have you saved an entry in your database? If yes, then after saving it you can check what id was assigned to it. Once you know the id, use it to retrieve the record back from the database.

**Comment by Nooria999** [comment]
We tried saving the data through the WebApp and then explicitly through shell as well, it isn't returning the data. Also, We tried retrieving the Id and it is returning nothing.

**Comment by miguelgrinberg** [comment]
> We tried saving the data through the WebApp and then explicitly through shell as well

Once again, please show me what you've done. A copy of your shell session would suffice.

There is a mistake that you've made, so unless you show me exactly what you've done I can't tell you where it is.

**Comment by mrbiggleswirth** [comment]
### 1. Python shell operations
@Nooria999 First of all you never commited any data entries into your database manually.

```
# Add users to database.
>>> u = User(username='john', email='john@example.com')
>>> db.session.add(u)
>>> db.session.commit()

>>> u = User.query.get(1)
>>> u
<User john>
```

.

### 2. Inspect your database
Assuming you are using SQLite database for development you can use the **SQLite Manager** web browser plugin to inspect what your database content looks like.

**2.1**
File > Open a Database

**2.2**
Manage > Inspect selected database

**2.3**
SELECT * FROM user;

.

### 3. forms.py
@Nooria999 You mentioned in your **routes.py** file these imports.

```
from newapp.models import User
from newapp.models import Pdetails
from newapp.forms import PdetailsForm
```
Can you update your original post with the relevant code from your **forms.py** file?
```
class PdetailsForm(Flaskform):

    ...
    ...
```
