### ISSUE TITLE
Unable to import 'flask_migrate' pylint(import-error)

### ISSUE THREAD

**Issue by aksharadyuti** [miguelgrinberg/microblog#167]

**Comment by aksharadyuti** [comment]
![IMG_20190630_134723](https://user-images.githubusercontent.com/47235698/60394161-a9777780-9b3d-11e9-93cb-c80747647c26.jpg)

**Comment by miguelgrinberg** [comment]
First of all, an error shown by PyCharm is not proof that there is actually an error. If the application works fine, then the problem is with PyCharm's linter, not with Flask-Migrate.

**Comment by alexdavidkim** [comment]
When receiving this pylint error, change the interpreter in VSCode. 

Ctrl+Shift+P - Python: Select Interpreter - (directory with the venv currently using)
