### ISSUE TITLE
I'm getting an error on Chapter 16

### ISSUE THREAD

**Issue by Raqhea** [miguelgrinberg/microblog#171]
Hello, I spent few hours but couldn't find any solution. Here is my problem:
When I used reindex method with Post model, I got this error:
![image](https://user-images.githubusercontent.com/34214152/60748100-2ae26600-9f93-11e9-8945-d15ee6941aac.png)

Also I get this when I call query from Post or User model, I don't know what to do

**Comment by miguelgrinberg** [comment]
I think the problem happens because you are using a standard Python shell, not a Flask shell.

**Comment by Raqhea** [comment]
Yeah using flask shell solved the problem, thanks!
