### ISSUE TITLE
Elasticsearch error

### ISSUE THREAD

**Issue by miaoweiwei** [miguelgrinberg/microblog#173]
from elasticsearch import Elasticsearch
es = Elasticsearch('http://localhost:9200')
es.index(index='my_index', doc_type='my_index', id=1, body={'text': 'this is a test'})

elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x000001A8F01350B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x000001A8F01350B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。)

**Comment by miguelgrinberg** [comment]
Are you running Elasticsearch on your computer?

**Comment by miaoweiwei** [comment]
I found the reason, I did not install elasticsearch ![image](https://user-images.githubusercontent.com/20410007/61578643-eaefb700-ab2c-11e9-902e-d1a330c68a09.png)
