### ISSUE TITLE
Chapter 20 has a bug

### ISSUE THREAD

**Issue by miaoweiwei** [miguelgrinberg/microblog#175]
![image](https://user-images.githubusercontent.com/20410007/61579619-3f4d6380-ab3a-11e9-8b26-cbf0e4f37579.png)
![image](https://user-images.githubusercontent.com/20410007/61579629-5ab86e80-ab3a-11e9-9a71-44d4ea180bdc.png)

**Comment by miaoweiwei** [comment]
<code>  
It is recommended to add the following code before the popup  

     if ("{{ current_user.is_anonymous  }}" === "True") {
        return;
    }
</code>

**Comment by miguelgrinberg** [comment]
I think you haven't initialized the popover component from Bootstrap.

**Comment by miaoweiwei** [comment]
How to initialize the popover component.

**Comment by miguelgrinberg** [comment]
It's hard for me to tell what you are missing without seeing your code. I recommend that you try using my version of the application. Use the download link at the top of the chapter 20 article to get the code.

**Comment by miaoweiwei** [comment]
alright, thank you very much
