### ISSUE TITLE
CHAPTER 8. FOLLOWERS 'User' object has no attribute 'followers'

### ISSUE THREAD

**Issue by yiran7324** [miguelgrinberg/microblog#176]
Hi Miguel~

I came to meet this `no attribute` problem when just closed to the unittest in chapter 8.

And I check the repo, find out there is no `followers` things but `followed`relationship table in [User](https://github.com/miguelgrinberg/microblog/blob/master/app/models.py#L91). What's the problem?

```shell
test_avator (__main__.UserModelCase) ... ok
test_follow (__main__.UserModelCase) ... ERROR
test_password_hashing (__main__.UserModelCase) ... ok

======================================================================
ERROR: test_follow (__main__.UserModelCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 37, in test_follow
    self.assertEqual(u1.followers.all(), [])
AttributeError: 'User' object has no attribute 'followers'

----------------------------------------------------------------------
Ran 3 tests in 0.104s

FAILED (errors=1)
```

**Comment by miguelgrinberg** [comment]
The `followed` relationship has a `backref` set to `followers`. Maybe you did not include the backref in your version of the app?

**Comment by yiran7324** [comment]
Problem solved, it's a typo of params of backref. Thanks a lot.
