### ISSUE TITLE
Timestamps columns as db.Float is not good for MySQL?

### ISSUE THREAD

**Issue by c8huk** [miguelgrinberg/microblog#177]
https://github.com/miguelgrinberg/microblog/blob/ec3a9df344cbd71520eeab090983a90c83a71231/app/models.py#L196
Works fine in the SQLite test environment because SQLite uses the 8-byte REAL datatype:
https://www.sqlite.org/datatype3.html
Doesn't work as expected in production environment with MySQL because MySQL uses 4-byte FLOAT:
https://dev.mysql.com/doc/refman/5.7/en/floating-point-types.html
Resulting in data loss.
Should the column be a db.Float with precision specified? Or just a db.Integer?

**Comment by miguelgrinberg** [comment]
All floating point formats are inaccurate. The question is if the amount of error in the representation of the number is significant enough to cause problems. I believe the answer is no, regardless of 4 or 8-byte storage. Please show me examples if you disagree.

**Comment by c8huk** [comment]
I added a copy of the timestamp to the notification payload_json column to compare it to what's stored in the database.

To do this I changed as follows:
**app/tasks.py line 20:**
`    task.user.add_notification('task_progress', {'task_id': job.get_id(), 'progress':progress, 'debug_timestamp':time.time()})`

**app/main/routes.py line 169**
`    user.add_notification('unread_message_count', {'message_count': user.new_messages(), 'debug_timestamp':time.time()})`

**app/main/routes.py line 181**
`  current_user.add_notification('unread_message_count', {'message_count': 0, 'debug_timestamp':time.time()})`

Example output of the notifications route when deployed with MySQL:
`[
  {
    "data": {
      "debug_timestamp": 1565903577.5113404,
      "message_count": 1
    },
    "name": "unread_message_count",
    "timestamp": 1565900000
  },
  {
    "data": {
      "debug_timestamp": 1565903600.2387013,
      "progress": 70,
      "task_id": "7e658cbd-e518-48af-a427-8983b12ee4cc"
    },
    "name": "task_progress",
    "timestamp": 1565900000
  }
]`

It seems like there's a significant amount of accuracy lost when timestamps are held in MySQL floats (3600 seconds in this example).

It does still work as expected. I'm just wondering why you chose to use db.Float over:

- db.Int. A MySQL int would still use 4 bytes but would be accurate to the second. 
- db.DateTime like the Post and Message models

Not a criticism. I'm trying to understand for my learning.

**Comment by miguelgrinberg** [comment]
I don't understand why you get such a big difference. For example, the number 1565903600.2387013 can be converted to float as 1565903616, so it's just 16 seconds away from the original, not 3600 like in your case, for which I don't really have an explanation.

But still, even a 16 second drift was not something I intended to have. Either a Double, Integer or DateTime all should address it.
