### ISSUE TITLE
Error saying I can't import flask for request method()

### ISSUE THREAD

**Issue by gleagbothenoob** [miguelgrinberg/microblog#178]
Towards the end of "Requiring Users to Login" you imported flask and said that's where the request method comes from, but when I did it and ran the flask app, I received an error saying "cannot import name flask". The error makes sense, like why would I want to import the the flask web framework from the flask web frame work. Do you know what I was suppose to import instead to allow the request method in "request.args.get('next')".

**Comment by mrbiggleswirth** [comment]
Have you checked which of your files and section of codes differs from Grinberg's chapter 5 example code?
https://github.com/miguelgrinberg/microblog/archive/v0.5.zip

**Comment by miguelgrinberg** [comment]
@gleagbothenoob Please show your code and the error(s) that you get, including any stack traces.

**Comment by gleagbothenoob** [comment]
@miguelgrinberg @mrbiggleswirth , thank you guys, but I was able to figure it out. I changed it to 'request' and it worked.
