### ISSUE TITLE
ImportError: No module named migrate.versioning?

### ISSUE THREAD

**Issue by scheung38** [miguelgrinberg/microblog#18]
After pip install -r requirements.txt and python db_create.py, I still get the following? Which library is it taken from Flask-Migrate, Migrate?

```
    from migrate.versioning import api
ImportError: No module named migrate.versioning
```

I did get:

```
ld: library not found for -lgcc_s.10.5
collect2: ld returned 1 exit status
error: command '/usr/local/bin/gcc-4.2' failed with exit status 1
```

EDIT:
OK it is the sqlalchemy-migrate==0.9.2 not installed, but not sure why pip install -r requirements.txt didnt do it for me?

**Comment by miguelgrinberg** [comment]
Yes, the pip install -r requirements.txt should have included sqlalchemy-migrate. You may want to look at the output of the pip command to see why this package was not installed.

**Comment by eshijia** [comment]
@scheung38 I think the reason why you got the error is that you were not using the python binary of the virtualenv (flask/bin/python) to run the db_create.py.

**Comment by Charlie37** [comment]
Hello, and thanks for your awesome tutorial.
Sorry to reiterate, but we're having the same issue here, with a slight variation:

```
python3 db_create.py 
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2218, in _find_and_load_unlocked
AttributeError: 'module' object has no attribute '__path__'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "db_create.py", line 2, in <module>
    from migrate.versioning import api
ImportError: No module named 'migrate.versioning'; 'migrate' is not a package
```

The requirements.txt does contain sqlalchemy-migrate. The pip install -r requirements.txt ends with:
```
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-rdesxume/psycopg2
Storing debug log for failure in /home/goyave/.pip/pip.log
```

**Comment by miguelgrinberg** [comment]
@Charlie37 it looks like package psycopg2 failed to install. This is the postgres database client. If you don't need it, you can just comment that line out. Or else, you may need to install postgres on your machine so that the Python client can install.

**Comment by Charlie37** [comment]
@miguelgrinberg OK, thanks a lot.

**Comment by jcsm1th** [comment]
I ran into a similar problem with the migrate.versioning from api not being found.  did a pip install sqlalchemy-migrate and all is good now.

**Comment by ofsazib** [comment]
ImportError: No module named migrate.versioning problem in python3.What will be the solution?

**Comment by miguelgrinberg** [comment]
@ofsazib what's the output of `pip freeze`?

**Comment by ofsazib** [comment]
@miguelgrinberg  Babel==2.3.4
blinker==1.4
click==6.7
coverage==4.3.4
decorator==4.0.11
defusedxml==0.4.1
Flask==0.12
Flask-Babel==0.11.1
Flask-Login==0.4.0
Flask-Mail==0.9.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.1
Flask-WhooshAlchemy==0.56
Flask-WTF==0.14.2
flipflop==1.0
guess-language==0.2
itsdangerous==0.24
Jinja2==2.9.4
MarkupSafe==0.23
pbr==1.10.0
pkg-resources==0.0.0
python3-openid==3.0.10
pytz==2016.10
six==1.10.0
SQLAlchemy==1.1.5
sqlalchemy-migrate==0.10.0
sqlparse==0.2.2
Tempita==0.5.2
Werkzeug==0.11.15
Whoosh==2.7.4
WTForms==2.1

**Comment by miguelgrinberg** [comment]
are you using a virtualenv? If not, is there any chance you are using `pip` to install packages, but then using `python3` to run your application? In some OSes, you have to use `pip3` for Python3.

**Comment by ofsazib** [comment]
@miguelgrinberg  Yes i am using a virtualenv. I have used pip to install pakage.Now what is your suggestion to to.Should I reinstall all the pakages using pip3?Note that I am using Ubuntu 16.04.

**Comment by miguelgrinberg** [comment]
Did you remember to activate the virtualenv before running `pip`?

**Comment by ofsazib** [comment]
@miguelgrinberg  yes, I did.Now I am using python3 script.py instead ./script.py and it runs well as there is some warning.

**Comment by miguelgrinberg** [comment]
If `./script.py` does not work, you have to check the first line in the script, which is likely a shebang line that specifies what Python interpreter to use. If you change that to something like:

    #!/usr/bin/env python

Then the problem should be fixed.

**Comment by desmond75** [comment]
Hi Miguel nice tutorial i have problem with database migration i  get this error as i run the the code i am on windows using python 2.7 
Traceback (most recent call last):
  File "db_create.py", line 2, in <module>
    from migrate.versioning import api
ImportError: No module named migrate.versioning

**Comment by miguelgrinberg** [comment]
@desmond75 you don't seem to have the sqlalchemy-migrate project installed in your virtual environment.

**Comment by desmond75** [comment]
This is the path install it to with my vitualenv activated <flask>C:\project\microblog\flask\Scripts>

this my output of pip freeze
(flask) C:\project\microblog\flask\Scripts>pip
Babel==2.4.0
blinker==1.4
click==6.7
coverage==4.4.1
decorator==4.0.11
Flask==0.12.2
Flask-Babel==0.11.2
Flask-Login==0.4.0
Flask-Mail==0.9.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.2
Flask-WhooshAlchemy==0.56
Flask-WTF==0.14.2
flipflop==1.0
guess-language==0.2
itsdangerous==0.24
Jinja2==2.9.6
MarkupSafe==1.0
pbr==3.0.1
python-openid==2.2.5
pytz==2017.2
six==1.10.0
SQLAlchemy==1.1.10
sqlalchemy-migrate==0.11.0
sqlparse==0.2.3
Tempita==0.5.2
Werkzeug==0.12.2
Whoosh==2.7.4
WTForms==2.1

(flask) C:\project\microblog\flask\Scripts>

**Comment by miguelgrinberg** [comment]
With your virtualenv activated, try running `python db_create.py` instead of `./db_create.py` (Assuming that is what you were doing). Any difference?

**Comment by TYLERWAKEFIELD** [comment]
Hi Miguel, I am also getting this error. I have the virtaul system activated, using python 2.7
(flask) C:\microblog>python db_create.py
Traceback (most recent call last):
  File "db_create.py", line 3, in <module>
    from config import SQLALCHEMY_DATABASE_URI
ImportError: cannot import name SQLALCHEMY_DATABASE_URI

(flask) C:\microblog>pip freeze
Babel==2.4.0
blinker==1.4
click==6.7
coverage==4.4.1
decorator==4.0.11
Flask==0.12.2
Flask-Babel==0.11.2
Flask-Login==0.4.0
Flask-Mail==0.9.1
Flask-OpenID==1.2.5
Flask-SQLAlchemy==2.2
Flask-WhooshAlchemy==0.56
Flask-WTF==0.14.2
flipflop==1.0
guess-language==0.2
itsdangerous==0.24
Jinja2==2.9.6
MarkupSafe==1.0
pbr==3.1.1
python-openid==2.2.5
pytz==2017.2
six==1.10.0
SQLAlchemy==0.7.9
sqlalchemy-migrate==0.7.2
sqlparse==0.2.3
Tempita==0.5.2
Werkzeug==0.12.2
Whoosh==2.7.4
WTForms==2.1

i also get the ImportError: No module named migrate.versioning when i just use the db_create.py

**Comment by miguelgrinberg** [comment]
Closing this issue, as it does not apply anymore.
