### ISSUE TITLE
How to remove the text Timestamp when saving pandas DataFrame as Dictionary?

### ISSUE THREAD

**Issue by mrbiggleswirth** [miguelgrinberg/microblog#182]
Hi Microblog Community,

This question isn't directly related to any lessons from the Microblog book tutorial. But it derives from its lessons.

I need to save a pandas DataFrame as Dictionary in order to push my data into my database using Flask SQLAlchemy. But even when I change the DataType for column **Time** from Datetime to Object. My dictionary variable still contains the **text Timestamp**, how can I remove this text and parenthesis characters from my dictionary?

> ufo_dict_2
> 
> {0: {'City': 'Ithaca', 'Colors Reported': nan, 'Shape Reported': 'TRIANGLE', 'State': 'NY', 'Time': **Timestamp(**'1930-06-01 22:00:00'**)**}}

.

Below is my experiment code to reproduce in terminal what I have tried so far:

**x13_change_DataType_for_Series.py**
```
import pandas as pd

#_______________________________________________________________________________

ufo = pd.read_csv('http://bit.ly/uforeports')

print("")
print(ufo.head())
print("")
print(type(ufo))
print("")
print("ufo.dtypes")
print(ufo.dtypes)

print("")
print("_______________________________________________________________________")
print("")

#_______________________________________________________________________________

# Convert DataFrame to Dictionary.

ufo_dict_0 = ufo.to_dict('index')

print("ufo_dict_0")
print("")
print(dict(list(ufo_dict_0.items())[0:3]))
print("")
print(type(ufo_dict_0))

print("")
print("_______________________________________________________________________")
print("")

#_______________________________________________________________________________

# Convert Time datatype from Object to Datetime.

ufo['Time'] = pd.to_datetime(ufo.Time)

print(ufo.head())
print("")
print(type(ufo))
print("")
print("ufo.dtypes")
print(ufo.dtypes)

print("")
print("_______________________________________________________________________")
print("")

#_______________________________________________________________________________

# Convert DataFrame to Dictionary.

ufo_dict_1 = ufo.to_dict('index')

print("ufo_dict_1")
print("")
print(dict(list(ufo_dict_1.items())[0:3]))
print("")
print(type(ufo_dict_1))

print("")
print("_______________________________________________________________________")
print("")

#_______________________________________________________________________________

# Convert Time datatype from Datetime to Object.

# data[utc_time] = data.utc_time.astype(object)
ufo['Time'] = ufo.Time.astype(object)

print(ufo.head())
print("")
print(type(ufo))
print("")
print("ufo.dtypes")
print(ufo.dtypes)

print("")
print("_______________________________________________________________________")
print("")

#_______________________________________________________________________________

# Convert DataFrame to Dictionary.

ufo_dict_2 = ufo.to_dict('index')

print("ufo_dict_2")
print("")
print(dict(list(ufo_dict_2.items())[0:3]))
print("")
print(type(ufo_dict_2))

print("")
print("_______________________________________________________________________")
print("")

#_______________________________________________________________________________

```

**Comment by miguelgrinberg** [comment]
What type is your timestamp? My guess is that this object prints itself with the format `Timestamp(...)` so that is what you see when you print the dict.

**Comment by mrbiggleswirth** [comment]
Hi @miguelgrinberg 

After I converted the original Time column from **type Object** (string?) to **type DateTime** I automatically get that `Timestamp(...)` text baked into my time values.
I attempted to convert that DateTime back to Object (string?) before creating a dictionary but still the same result.

Do you know of any pandas magic that can clean my Time column from that baked in `Timestamp(...)` text?

Or do I need to clean that data after I have created the dictionary variable?
Which at first sight didn't seem like the most optimal way to explore this problem.
Given that I might be processing 10 000 - 1 000 000 rows of dictionary data in the future.

.

**0.**
When I read the original csv file into a pandas DataFrame the **Time column** looks like this:
```
6/1/1930 22:00

ufo.dtypes
Time object

ufo_dict_0
{0: { ... , ... , 'Time': '6/1/1930 22:00'}}
```

.

**1.**
When I change the time format in pandas DataFrame the **Time column** looks like this:
```
# Convert Time datatype from Object to Datetime.
ufo['Time'] = pd.to_datetime(ufo.Time)
```
```
1930-06-01 22:00:00

ufo.dtypes
Time datetime64[ns]

ufo_dict_1
{0: { ... , ... , 'Time': Timestamp('1930-06-01 22:00:00')}}
```

.

**2.**
When I change the time format from DateTime back to Object which I assume is the same as String in pandas DataFrame the **Time column** looks like this:
```
# Convert Time datatype from Datetime to Object.
ufo['Time'] = ufo.Time.astype(object)
```
```
1930-06-01 22:00:00

ufo.dtypes
Time object

ufo_dict_2
{0: { ... , ... , 'Time': Timestamp('1930-06-01 22:00:00')}}
```

**Comment by miguelgrinberg** [comment]
Isn't this strictly a Pandas question? At first I thought you were talking about SQLAlchemy columns, but this problem is entirely in the Pandas domain isn't it?

You'll get more useful replies in a Pandas forum, but looking at Pandas timestaps it looks like this is how they are rendered when they are converted to strings: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Timestamp.html. If you want to do the conversion in a different way then maybe you have to implement this conversion yourself?

**Comment by mrbiggleswirth** [comment]
Yes the particular problem I'm stuck with is isolated within the Pandas domain.
Yes I will try to get in touch with the Pandas forum. The StackOverflow explanations confuses me on this matter.

**Comment by mrbiggleswirth** [comment]
I found the solution! : D

```
# http://strftime.org/

ufo['Time'] = ufo.Time.apply(lambda x: x.strftime('%Y-%m-%d %H:%M'))
```
