### ISSUE TITLE
Ch 15 - Blueprints refactoring and Unit Testing reorganization issues.

### ISSUE THREAD

**Issue by mrbiggleswirth** [miguelgrinberg/microblog#183]
Hi, I have followed along the eBook to Chapter 15 where I have learnt how to refactor my Microblog code in order to better organize the files. Everything works ok after I refactored the code using Blueprints.

### My question is this:
If I want to move my Unit Testing file **tests.py** to a separate sub-folder called **testing** where I can organize several Unit Testing files in the future. How can I accomplish that?

I'm getting this Error after moving the tests.py file to **testing folder**. The file works when it's located directly under microblog folder.
```
/microblog$ ls -l

microblog
 |-- appz
 |-- config.py
 |-- logs
 |-- microblog.py
 |-- migrations
 |-- run_Flask_server.sh
 |-- testing
      |-- tests.py
```

```
/microblog/testing$ python3 tests.py

Traceback (most recent call last):
    File "tests.py", line 1, in <module>
        from appz import db
ModuleNotFoundError: No module named 'appz'
```
.
The **tests.py** file is basically the same as from the book's example code archive. Here's a snippet.
The only difference is that I have re-named my folder to **appz** instead of **app**.
```
from appz import db
from appz import create_app
from config import Config

from datetime import datetime
from datetime import timedelta
import unittest

# Database Models
from appz.models import Post
from appz.models import User


class TestConfig(Config):
    TESTING = True
    SQLALCHEMY_DATABASE_URI = 'sqlite://'


class UserModelCase(unittest.TestCase):

    def setUp(self):
        self.app = create_app(TestConfig)
        self.app_context = self.app.app_context()
        self.app_context.push()
        db.create_all()

    def tearDown(self):
        db.session.remove()
        db.drop_all()
        self.app_context.pop()

...
...

if __name__ == '__main__':
    unittest.main(verbosity=2)
```

**Comment by miguelgrinberg** [comment]
I think you will get this to work if you run your tests from the top-level directory of your project, not from testing.

Alternatively, you can set `PYTHONPATH` to the top-level folder, so that `import appz` works.

**Comment by mrbiggleswirth** [comment]
I changed my Unit Testing back to its original structure. The subject of Module file-folder management was way more complex than I could ever have imagined it. I will have to revisit this subject again in the very far future.
