### ISSUE TITLE
ImportError: cannot import name 'app' from 'app' (unknown location)

### ISSUE THREAD

**Issue by Elliot727** [miguelgrinberg/microblog#184]
I followed your instructions on the webpage and it used to work 
I recently changed python versions(3.5 to 3.7) and now it doesn't work

**Comment by mrbiggleswirth** [comment]
Where is your microblog.py file located?

/microblog/microblog.py
/microblog/app/microblog.py

**Comment by miguelgrinberg** [comment]
Nothing should have changed between python 3.5 and 3.7 except your own environment under which you run each python version. This is probably a difference in how you have your `PYTHONPATH` set.

**Comment by Elliot727** [comment]
(venv) Elliots-iMac:helloworld elliot$ flask run
 * Serving Flask app "microblog.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "microblog", an ImportError was raised:

Traceback (most recent call last):
  File "/Users/elliot/Code/helloworld/venv/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/elliot/Code/helloworld/microblog.py", line 1, in <module>
    from app import app
ImportError: cannot import name 'app' from 'app' (unknown location)

(venv) Elliots-iMac:helloworld elliot$ 

THIS IS THE FULL ERROR

**Comment by mrbiggleswirth** [comment]
### 1. Which Microblog chapter are you on?
The reason I ask this is because the Microblog code gets refactored into different ways the more lessons you have absorbed. Which can lead to dependency issues if something major changes. Knowing which version your Microblog project is currently at makes it easier to pinpoint the issue.

### 2. /helloworld/
What does your file `/helloworld/microblog.py` look like?

### 3. /helloworld/app/
What does your file `/helloworld/app/__init__.py` look like?

**Comment by abhijithvijayan** [comment]
I have the same issue.

I am trying to import and env variable declared under config class, accessed in another file

**Comment by Elliot727** [comment]
I am on chapter 1 it all of a sudden stopped working after days of success

**Comment by abhijithvijayan** [comment]
> I am on chapter 1 it all of a sudden stopped working after days of success

Try this https://github.com/miguelgrinberg/microblog/issues/188#issuecomment-566867801

**Comment by herrri** [comment]
Hello,

Was struggling with this in another context, using Flask to have a quick server setup. 

There is a sneaky little feature in Flask. If you happen to have a `.env` file in the parent directory or the  parent directories, by walking up the directory tree. It can be automatically imported and all goes *boom*, as the `flask-cli` tries to import your app from wrong directory.

This reuquires that `python-dotenv` is installed.

The whole thing is actually documented here: https://flask.palletsprojects.com/en/1.1.x/cli/?highlight=dotenv#environment-variables-from-dotenv

And there is an open issue about it also: https://github.com/pallets/flask/issues/3535

Flask source code reference: https://github.com/pallets/flask/blob/1.1.1/src/flask/cli.py#L596

Running on macOS 10.15.3:
```
Python 3.7.5 (pyenv 1.2.15)
Flask 1.1.1
Werkzeug 1.0.0
```

**Comment by ynadiv** [comment]
I encountered this error. It looks like my problem was was in naming the file _init_.py instead of __init__.py (with 2 underscores on either side). Same thing with app=Flask(__name__).

Perhaps it's as simple as that for you?

**Comment by michael-pptf** [comment]
So for anyone that's experiencing this problem, check your environment variables with this command in your terminal:
`$ echo $FLASK_APP`
if the result is empty or isn't your flask application name, you will need to edit your bash shell script to add this env var like so:
`$ export FLASK_APP=flaskapp(or your flask application name)`

**Comment by tony-medici** [comment]
Had the same error. It was as a result of me not using the right filename for "__init__.py".

Make sure to use double underscore and not a single underscore symbol.
Don't use "_init_.py", rather use "__init__.py".

**Comment by srinath-nanduri** [comment]
Why do we use dunders everywhere in python?

**Comment by miguelgrinberg** [comment]
> Why do we use double underscores everywhere in python?

Those are the rules. I did not make them!

**Comment by Havoac** [comment]
This is the error I am facing , Can you please help out

 


* Serving Flask app "microblog.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "microblog", an ImportError was raised:

Traceback (most recent call last):
  File "c:\flask_practice\microblog\venv\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "C:\flask_practice\microblog\microblog.py", line 1, in <module>
    from app import app
ImportError: cannot import name 'app' from 'app' (unknown location)

**Comment by miguelgrinberg** [comment]
@Havoac did you compare your code against this repository? You have things that are missing very likely. In the tutorial article there is a link to this repository at the chapter 1 stage. Use that to compare and find what you are missing.

**Comment by Havoac** [comment]
> @Havoac did you compare your code against this repository? You have things that are missing very likely. In the tutorial article there is a link to this repository at the chapter 1 stage. Use that to compare and find what you are missing.


I compared it several times but nothing is missing.
What shall I do now ??

**Comment by Havoac** [comment]
> @Havoac did you compare your code against this repository? You have things that are missing very likely. In the tutorial article there is a link to this repository at the chapter 1 stage. Use that to compare and find what you are missing.

Yeah got this 
I named the file as                  "_init_.py"        instead of                        "__init__.py"

**Comment by Havoac** [comment]
> @Havoac did you compare your code against this repository? You have things that are missing very likely. In the tutorial article there is a link to this repository at the chapter 1 stage. Use that to compare and find what you are missing.

yeag got this

**Comment by gwaiting** [comment]
> 有相同的错误。这是由于我没有使用正确的文件名为**"init.py"。**
> 
> 请务必使用双下划线，而不是单个下划线符号。
> `Don't use "_init_.py", rather use "__init__.py".`

nice success

**Comment by flybd5** [comment]
I battled with this yesterday, same problem. the layout and code is exactly like you said in the tutorial. This is what I don't like about Python, that something so simple can turn into a nightmare over Python's psychotic issues with packages, versions and environments that get in the way of doing very simple things.

**Comment by miguelgrinberg** [comment]
@flybd5 I'm sorry that the experience was not ideal for you. Can I make a small correction to what you have said? I have actually taken great care in having this repository 100% synchronized with the tutorial. Each chapter of the tutorial contains a link to the tag in this repository that contains the code that matches that part of the tutorial. So yes, if you clone the repo you will get the final version of the project, but all the previous steps are embedded in it, all you need to do is find the appropriate tag (run `git tag` in your cloned repo to see them all).

**Comment by flybd5** [comment]
@miguelgrinberg ...and the tutorial doesn't say a single word about this. Neither I nor anyone else on the entire planet is telepathic. I should not have to waste my time trying to find an issue, posting my frustration and waiting for you to reply with an undocumented fix to solve this, Miguel. I think I will find some other tutorial.

**Comment by miguelgrinberg** [comment]
@flybd5 If the tutorial does not work for you then by all means find something else. But you are incorrect once again. These two paragraphs are part of the introduction in Chapter 1 ([link](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world) if you want to verify for yourself):

> All the code examples presented in this tutorial are hosted on a GitHub repository. Downloading the code from GitHub can save you a lot of typing, but I strongly recommend that you type the code yourself, at least for the first few chapters. Once you become more familiar with Flask and the example application you can access the code directly from GitHub if the typing becomes too tedious.
> 
> At the beginning of each chapter, I'm going to give you three GitHub links that can be useful while you work through the chapter. The Browse link will open the GitHub repository for Microblog at the place where the changes for the chapter you are reading were added, without including any changes introduced in future chapters. The Zip link is a download link for a zip file including the entire application up to and including the changes in the chapter. The Diff link will open a graphical view of all the changes that were made in the chapter you are about to read.

**Comment by flybd5** [comment]
Wow. You really don't get what I am telling you, do you? Where in that text do you see the word "tag"? No more excuses. You just need to fix all the issues. I'm moving on.

**Comment by miguelgrinberg** [comment]
@flybd5 Good luck. Hope you find a tutorial that you like better.

**Comment by miguelgrinberg** [comment]
@sunandosamaddar this tutorial is up to date and actively maintained.

**Comment by sunandosamaddar** [comment]
<img width="218" alt="Capture12" src="https://user-images.githubusercontent.com/44464454/139672786-0c6491b8-7c64-489a-8a4c-53f14e819ce4.PNG">

Ok, this is my file tree, and it's got a .flaskenv with `FLASK_APP=myapplication.py`, yet it doesn't work.

**Comment by miguelgrinberg** [comment]
@sunandosamaddar "it doesn't work" is not sufficient information. Can you provide all the output that you get when you do whatever it is that you are doing that isn't working?

**Comment by sunandosamaddar** [comment]
Let me show you my files. This is just not how I thought it would be, and all this does not work at all. I hope you consider the suggestion.

- myapplication.py
`from app import app`

- app/__init__.py
```
from app import routes
from flask import Flask

app = Flask(__name__)
```

- app/routes.py
```
from app import app

@app.route('/')
def index():
    return "hello, world!"
```

- flask run
```
ImportError: cannot import name 'app' from partially initialized module 'app' (most likely due to a circular import)
```

**Comment by sunandosamaddar** [comment]
Ok, please pardon me. The issue is with 

> @sunandosamaddar "it doesn't work" is not sufficient information. Can you provide all the output that you get when you do whatever it is that you are doing that isn't working?
> 
> Also, here is your chapter 1 repo, it's linked in the article: https://github.com/miguelgrinberg/microblog/tree/v0.1.

Thanks a lot @miguelgrinberg! Wish you have a great year ahead!

**Comment by miguelgrinberg** [comment]
@sunandosamaddar is this a joke? You insulted me by insinuating that I'm out of touch with my own tutorial. Docker is an advanced topic that is covered much later in my tutorial. It's not in chapter 1 for a reason. So why would you insult me when you are unable to do something on your own that is not part of my tutorial? Why don't you follow the tutorial as I designed it instead of complaining that everything is broken?

**Comment by flybd5** [comment]
How did I know you would react like that, Miguel? Fix your tutorial and
stop whining. I'm out of this thread.

Sunando, there are other tutorials out there much better than this. Don't
bother.
