### ISSUE TITLE
cannot import flask

### ISSUE THREAD

**Issue by AkshithaKoppaka** [miguelgrinberg/microblog#185]
C:\Python\Python37-32>python -m flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: python -m flask run [OPTIONS]

Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "C:\Python\Python37-32\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "C:\Python\Python37-32\app\__init__.py", line 1, in <module>
    from flask import flask
ImportError: cannot import name 'flask' from 'flask' (C:\Python\Python37-32\lib\site-packages\flask\__init__.py)

Can you please help me? I don't understand this error.

**Comment by mrbiggleswirth** [comment]
@AkshithaKoppaka How did you solve this problem?
Would be helpful to others who trip on the same problem in the future.

**Comment by AkshithaKoppaka** [comment]
F in Flask should be capital while importing.

from flask import Flask

**Comment by mrbiggleswirth** [comment]
@AkshithaKoppaka Cool gg!
