### ISSUE TITLE
Problem with displaying the username

### ISSUE THREAD

**Issue by AkshithaKoppaka** [miguelgrinberg/microblog#186]
u=User(username='Susan', email='susan@example.com')
>>> u
<User (transient 24181488)>

Why am I not getting the username? Can you please tell me the solution for this?

**Comment by miguelgrinberg** [comment]
Please show me a complete Python session, from when you started the Python shell to the point where you get this transient message.

**Comment by AkshithaKoppaka** [comment]
C:\Python\Python37-32>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from app.models import User
>>> u=User(username='Susan', email='susan@example.com')
>>> u
<User (transient 24181488)>

**Comment by miguelgrinberg** [comment]
@AkshithaKoppaka is this an official Python release? If not, I suggest you try an official build. I'm honestly not sure why you get a different output, I cannot reproduce this here.

**Comment by AkshithaKoppaka** [comment]
Yes, it is the official build. I even tried updating it to the latest release of python but I am still getting the same output. Thanks for the response.

**Comment by miguelgrinberg** [comment]
Okay, this is something I've never seen before. What do you get when you type `u.name` after creating your user?

**Comment by AkshithaKoppaka** [comment]
I'm getting an AttributeError. It says that the User has no attribute 'name'.

**Comment by miguelgrinberg** [comment]
Are you using code that came directly from this repository or did you copy the code into your own version? I'm really confused about this issue, is there any chance you have a mistake? Can you show me the entire `User` class that you are using, for example?

**Comment by AkshithaKoppaka** [comment]
I'm using the same code from your repository. 

class User(db.Model):
    id=db.Column(db.Integer, primary_key=True)
    username=db.Column(db.String(64), index=True, unique=True)
    email=db.Column(db.String(120), index=True, unique=True)
    password_hash=db.Column(db.String(128))

    def ___repr__(self):
        return '<User {}>'.format(self.username)

**Comment by miguelgrinberg** [comment]
Well, you see, that's the key here. You copied the code, which of course is totally fine, but there could be some small difference hidden in the code that could be causing this. Can I ask you to actually install my code on another directory and run it in the same way you are running yours? Let me know if the problem persists when using my code directly.

Sorry to have to ask you to do this, I'm honestly completely lost as to what could be causing this behavior, so we have to start eliminating things.

**Comment by AkshithaKoppaka** [comment]
I don't know what mistake I have made while typing but I did it again by copying your code and it is working fine. Thanks for the help.

**Comment by mrbiggleswirth** [comment]
> I'm using the same code from your repository.
> 
> ```
> class User(db.Model):
>     id=db.Column(db.Integer, primary_key=True)
>     username=db.Column(db.String(64), index=True, unique=True)
>     email=db.Column(db.String(120), index=True, unique=True)
>     password_hash=db.Column(db.String(128))
> 
>     def ___repr__(self):
>         return '<User {}>'.format(self.username)
> ```

Which lesson of the Microblog chapter were you working on when this issue occurred?
Could you also include what your imports looked like from your **models.py** file when you still had this issue?

**Comment by AkshithaKoppaka** [comment]
@mrbiggleswirth I was working on the fourth lesson of the Microblog chapter.
This is my previous models.py file:

from app import db

class User(db.Model):
    id=db.Column(db.Integer, primary_key=True)
    username=db.Column(db.String(64), index=True, unique=True)
    email=db.Column(db.String(120), index=True, unique=True)
    password_hash=db.Column(db.String(128))

    def ___repr__(self):
        return '<User {}>'.format(self.username)

**Comment by mrbiggleswirth** [comment]
I remember seeing that word **transient** as well when I was learning **Chapter 4: Database**. Didn't understand it at that time nor do I know how to reproduce that error.

But I bet some Flask-SQLAlchemy config settings got messed up in these files:
**/microblog/config.py**
**/microblog/app/__init__py**

Or your **SQLite database file** got corrupted somehow while experimenting for the first time.
