### ISSUE TITLE
Error: Could not import "microblog".

### ISSUE THREAD

**Issue by rajagennu** [miguelgrinberg/microblog#188]
I have tried everything I could but still getting the same issue. 

Code
**microblog.py**
`from app import app`

**__init__.py**
```
from flask import Flask

app = Flask(__name__)

from app import routes
```
**routes.py**
```
from app import app
@app.route("/")
@app.route("/index")
def index():
  return "Hello World!"

```
```
$ flask --version
Python 3.7.1
Flask 1.1.1
Werkzeug 0.16.0

$ echo $FLASK_APP
microblog.py

```
Directory structure 

```
$ ls . app
.:
__pycache__  app          microblog.py venv

app:
__init__.py __pycache__ routes.py
```
Using Visual Studio Code as the editor, any help greatly appreciated.

Thank you.

**Comment by mrbiggleswirth** [comment]
@rajagennu 
What command did you perform to get that error message in terminal?

**Comment by rajagennu** [comment]
@mrbiggleswirth 

```
$ flask run 
 * Serving Flask app "microblog.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: Could not import "microblog".
```
And interestingly, I am not sure what I am missing here but from Python console it is working.

```
>>> import microblog
>>> from app import app
>>> app.run()
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [25/Oct/2019 02:01:45] "GET / HTTP/1.1" 200 -
```

**Comment by mrbiggleswirth** [comment]
@rajagennu 
I compared your files with the Book's example codes for Chapter 1. Everything looks identical even the execution messages basically looks the same.

The only difference when I try your code on my end, is that my system doesn't allow the use for a virtual environment `venv`. So I have installed all my Python pip packages straight into my Linux system.

Perhaps you haven't activated your `venv` environment correctly yet. Please post how you activate your virtual environment before running the Flask server.

**Comment by rajagennu** [comment]
@mrbiggleswirth 

$ source venv/bin/activate

**Comment by mrbiggleswirth** [comment]
### 1.)
I'm looking through old tickets with the same error message but cannot find the relevant remedy for your situation:
https://github.com/miguelgrinberg/microblog/issues/155
https://github.com/miguelgrinberg/microblog/issues/181

.

### 2.)
Did you export the server file after you activated your virtual environment? Perhaps you only exported that file before venv activation.
`(venv) $ export FLASK_APP=microblog.py`

.

### 3.)
Other than these leads I have no idea what went wrong for your system. Perhaps one last thing you could try is to execute the Flask server like below command. Because I had issues running the server the regular way in the past when I was stuck on a Python 2.7 environment.

**Python 2 Environment**
`$ python -m flask run`

**Python 3 Environment**
`$ python3 -m flask run`

**Comment by rajagennu** [comment]
I am using Mac where default Python is 2.7. 
But my env is 3.7

Whats happening behind screen, I am not understanding here because explicit invoke as python3 is working. 

```
$ python3 -m flask run 
 * Serving Flask app "microblog.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [25/Oct/2019 10:37:05] "GET / HTTP/1.1" 200 -
```
```
$ python --version
Python 3.7.1
```

**Comment by mrbiggleswirth** [comment]
@rajagennu 
> I am using Mac where default Python is 2.7.
> But my env is 3.7
> 
> Whats happening behind screen, I am not understanding here because explicit invoke as python3 is working.
> 

That's the confusion that most likely will arise to all newcomers learning Python. When being forced to juggle both Python2 and Python3 on the same system. _(Not talking about virtual environments.)_

.

### Checking which Python versions you are using on Linux
Don't know if this procedure is applicable for Mac systems. Judging from your previous terminal outputs it seems like Mac is behaving slightly different compared to **old Linux distros** on this issue. 

However the most **recent Linux distros** also behaves like your Mac version. So it's hard to write a one-suit-fits-all guide to cover all possible hardware and system setups. _(Not talking about virtual environments.)_
```
$ which python
/usr/bin/python # Python 2

$ which python3
/usr/bin/python3 # Python 3

```

Having multiple Python versions on the same system then leads to another confusion. Pip package installer which one did you use to install your packages. _(Not talking about virtual environments.)_
```
# pip for Python 2
$ pip --version

# pip for Python 3
$ pip3 --version
```

**Comment by maxlang** [comment]
I'm not using microblog, but I ran into a similar issue and what fixed things for me was adding a `.env` file. Honestly I'm not sure why and not sure if it's relevant but I thought it might help someone.

**Comment by mrbiggleswirth** [comment]
@maxlang It depends on what the instructions and files looked like from the tutorial you followed.

The original poster followed **Microblog's Chapter 1** instructions. In **"Chapter 15.5 Environment Variables"** the Microblog has instructions on how to configure your Flask project using the `.env` file. They do the same thing just a difference in complexity with how you want to order and arrange your files, configs and passwords.

**Comment by mustaqimM** [comment]
> I'm not using microblog, but I ran into a similar issue and what fixed things for me was adding a `.env` file. Honestly I'm not sure why and not sure if it's relevant but I thought it might help someone.

I had the same issue and this actually works. Though `flask run` should be run from outside the `app` dir, then the error won't show up.

**Comment by abhijithvijayan** [comment]
I had similar error trying to access the environment variable inside a blueprint.
There was some circular dependency between the imports

Try changing
```
from app import app
```

to 

```
from flask import current_app as app
```

**Comment by vintagecruzz** [comment]
you need to navigate into your application folder were the microblog.py file is stored 
after that u can now run 'flask run'
