### ISSUE TITLE
config not found - **** Fixed move to the file to the level above /app *****

### ISSUE THREAD

**Issue by curtismu7** [miguelgrinberg/microblog#189]
(venv) cmuir-r:app cmuir$ flask run
 * Serving Flask app "microblog.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "app.microblog", an ImportError was raised:

Traceback (most recent call last):
  File "/Users/cmuir/Documents/python/micrblog/venv/venv/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/cmuir/Documents/python/micrblog/venv/app/__init__.py", line 2, in <module>
    from config import Config
ModuleNotFoundError: No module named 'config'

(venv) cmuir-r:app cmuir$ 

***

But I have config.py in the /app directory

I copied it from your this github.  Can not figure out why it can not find this module. Does it go somewhere else?

**Comment by miguelgrinberg** [comment]
@curtismu7 microblog.py and config.py go in the top-level directory, not inside the app sub-directory.

**Comment by braintho** [comment]
having the same issue here. config.py is in the top level directory.  I'm not sure how __init__.py is supposed to find config.py though.  Should we be using a relative path?
from config import Config isn't working in the __init__.py file.

**Comment by miguelgrinberg** [comment]
@braintho config.py is in the current directory, so it should be automatically in the python path. If you are starting your application from a different directory, or if your way of starting the python interpreter is different in a way that alters the default python path settings, then you can try setting the `PYTHONPATH` environment variable to the directory where config.py is.

**Comment by braintho** [comment]
on page 24 of The new and Improved Flask Mega-Tutorial you have:
>>> from microblog import app
>>>app.config['SECRET_KEY']
'you-will-never-guess

What folder are you in when you start python? I would imagine that you would be in the folder above microblog. Looks like I need to be in the microblog folder?
Sorry I'm new to creating packages so the init files are a bit new to me.

**Comment by braintho** [comment]
Yep got it working by running python in the top-level with the config file in that folder.  Thanks for you help, and the awesome book!
