### ISSUE TITLE
Edit .gitignore

### ISSUE THREAD

**Issue by adelminayi** [miguelgrinberg/microblog#191]
Hi everyone
please add ".idea" to ".gitignore" file.

**Comment by miguelgrinberg** [comment]
I prefer to keep this repository IDE agnostic. Some people prefer to ignore PyCharm or Code project files like you, others prefer to add them to git and track them along with the source code. It's really impossible to please everyone.

**Comment by onlinejudge95** [comment]
@adelminayi any thing that is specific to your own **dev** environment should be **your** responsibility. I would like to extend what @miguelgrinberg said to the version-controlled code repo also. I would **like** dev env related files to be ignored in `.git/info/exclude`. What are your thoughts @miguelgrinberg ?

**Comment by miguelgrinberg** [comment]
@onlinejudge95 what files are you talking about specifically?

**Comment by onlinejudge95** [comment]
let's say `.idea` or any dev env specific files like `.vscode` etc

**Comment by miguelgrinberg** [comment]
As I said above, I don't want to tell people how they should or should not handle their IDE files. We all do it in different ways, and I don't want this project to show a preference for one method or another.

**Comment by onlinejudge95** [comment]
Not specific to this project, in general how do you do it

**Comment by miguelgrinberg** [comment]
If I work on a project using an IDE, then I commit the IDE files with it.
