### ISSUE TITLE
bootstrap directory missing?

### ISSUE THREAD

**Issue by rkazak** [miguelgrinberg/microblog#194]
I don't see the bootstrap directory has this setup changed recently?

**Comment by rkazak** [comment]
I see that it's picking it up from somewhere outside the app directory.

**Comment by miguelgrinberg** [comment]
The Flask-Bootstrap library references the CSS and JS files from a CDN by default. You can configure it to serve the files from your local application if you like.

**Comment by rkazak** [comment]
Thanks!
