### ISSUE TITLE
TypeError: 'int' Object is not subscriptable

### ISSUE THREAD

**Issue by Anandoham** [miguelgrinberg/microblog#198]
In Ch. 16: https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xvi-full-text-search

When you tell us to write the search.py file (which is identical to the search.py file found here in the final version), the last line is:

`return ids, search['hits']['total']['value']` 

Which consistently caused a TypeError to return in the interpreter upon execution of:

`query_index('posts', 'testing', 1, 100)` (I replaced your search text with 'testing' as this was more relevant to the posts in my index)

I looked up an example of the dictionary which returns from the `elasticsearch.search()` method to see that there is a value assigned to `['hits']['total']` to realize that the code was trying to get the `['value']` index of `['total']` which is an integer and is obviously not subscriptable. 

I could not move on/resolve this until I removed `['value']` from the last line of the `query_index` function defined in app/search.py

**Comment by Anandoham** [comment]
This took me a long time to find and fix, and was mind-numbingly frustrating but also forced me to learn SO. MUCH. MORE. about what was happening here, list comprehension in python, problem solving, debugging, etc. I'm not sure if I'm missing something/if it should somehow work with `['value']` still in there, considering it has remained in your final project -- but I thought to open an issue in case it is pertinent/helpful to point out or assist anyone else going through this to learn. 


P.s. Thank you for this tutorial, it is amazing and I've learned a ton already. I highly appreciate you putting in the work and offering this to those of us who are beginning.

**Comment by Anandoham** [comment]
My elasticsearch version:

```
{
  "name" : "VwGa4rY",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "y671ORXfQziDcTxt51NRaQ",
  "version" : {
    "number" : "6.8.5",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "78990e9",
    "build_date" : "2019-11-13T20:04:24.100411Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.2",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

(as I am suspecting since no one else has brought this up, it somehow is supposed to work but maybe in a different version of something? I'm quite new to all this)

**Comment by miguelgrinberg** [comment]
@Anandoham You are correct. The tutorial is designed to work with Elasticsearch version 7 and up. The format of that search response is different in this version from previous versions unfortunately, this is the reason you are seeing this error.

The change that you've made is actually correct for the old releases of ES. There was another thing that was used in older versions called doc_type that you needed to provide every time you added a document. I don't recall, but maybe that one had a default and for that reason you did not experience that problem.

**Comment by Anandoham** [comment]
Thank you @miguelgrinberg ! Do you know what I have done incorrectly/how I could have ensured Elasticsearch version 7 was installed? (I realize this may be vague and difficult to answer but am also unsure what info to include to make it more clear)

Might it have been since when I first attempted to `brew install elasticsearch` I was told I needed to install `Adoptopenjdk8` in order to get around not having Java installed -- and then from there Elasticsearch is forced to install an older version as it is the one compatible with `Adoptopenjdk8`? 

(my best guess as I think everything else I've done followed the tutorial)

**Comment by jalexray** [comment]
@miguelgrinberg I had the same problem as @Anandoham, resulting from `brew install elasticsearch` on my Mac. I fixed it by installing from the elastic tap, `brew install elastic/tap/elasticsearch-full`
