### ISSUE TITLE
Possible bug in "/user/<username>" route in v0.6 tag corresponding to Part 6 of tutorial

### ISSUE THREAD

**Issue by deveshks** [miguelgrinberg/microblog#199]
I was trying out the Part 6 of the mega tutorial and found that I can easily replace a known username which is different that the logged in username, and can view his information, which is the function https://github.com/miguelgrinberg/microblog/blob/v0.6/app/routes.py#L75

I think we need to check if the id of the user we get from the URL matches the id of the current user, and if that happens, we show the profile, else we can perhaps redirect him to the `index` page, so something along the lines of

```
@app.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    if user.id != current_user.id:
        return redirect(url_for('index'))
    posts = [
        {'author': user, 'body': 'Test post #1'},
        {'author': user, 'body': 'Test post #2'}
    ]
    return render_template('user.html', user=user, posts=posts)
```

**Comment by deveshks** [comment]
Correct me if I am wrong, but I just realised that the logged in user can view blog posts of other users, hence you are not checking for the username passed with the current user.

**Comment by miguelgrinberg** [comment]
Blog posts are not meant to be private, anybody can see them. Likewise, the profile pages for all users are public. Thee is nothing wrong with deciding that these pages are private and a user can only see their own profile page, but that's not what I intended in this application.

**Comment by deveshks** [comment]
Thanks for the response @miguelgrinberg. In that case, this issue can be closed.
