### ISSUE TITLE
NameError: name 'followers' is not defined in chapter 8

### ISSUE THREAD

**Issue by DestinedDeveloper** [miguelgrinberg/microblog#200]
Hi Miguel, while running the test.py, I encounter the following error. Can you please help?

![Untitled](https://user-images.githubusercontent.com/44229794/71721546-7d6de380-2e4b-11ea-9618-89188597767b.png)

**Comment by miguelgrinberg** [comment]
The `followers` table is defined here: https://github.com/miguelgrinberg/microblog/blob/master/app/models.py#L84.

You do not appear to have this table defined in models.py.

**Comment by DestinedDeveloper** [comment]
from datetime import datetime
from werkzeug import generate_password_hash, check_password_hash
from app import db, login
from flask_login import UserMixin
from hashlib import md5

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(64), index = True, unique = True)
    email = db.Column(db.String(120), index = True, unique = True)
    password_hash = db.Column(db.String(128))
    posts = db.relationship('Post', backref='author', lazy='dynamic')
    about_me = db.Column(db.String(140))
    last_seen = db.Column(db.DateTime, default=datetime.utcnow)
    followers = db.Table('followers',
                db.Column('follower_id', db.Integer, db.ForeignKey('user.id')),
                db.Column('followed_id', db.Integer, db.ForeignKey('user.id'))
                )
    followed = db.relationship('User', secondary='followers',
                primaryjoin=(followers.c.follower_id == id),
                secondaryjoin=(followers.c.followed_id == id),
                backref=db.backref('followers', lazy='dynamic'),
                lazy='dynamic'
                )

    def __repr__(self):
        return '<User {}>'.format(self.username)
    
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)
    
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)
    
    def avatar(self, size):
        digest = md5(self.email.lower().encode('UTF-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/d=identicon'

    def follow(self, user):
        if not self.is_following(user):
            self.followed.append(user)
    
    def unfollow(self, user):
        if self.is_following(user):
            self.followed.remove(user)
    
    def is_following(self, user):
        return self.followed.filter(followers.c.followed_id == user.id).count() > 0

    def followed_posts(self):
        Post.query.join(
            followers, (followers.c.followed_id == Post.user_id)).filter(
                followers.c.follower_id == self.id)
        own = Post.query.filter_by(user_id = self.id)
        return followed.union(own).order_by(Post.timestamp.desc())

class Post(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.Integer, index = True, default = datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Post {}>'.format(self.body)

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

**Comment by miguelgrinberg** [comment]
You put the `followers` table as an attribute of the `User` model. Compare that against the code I linked above and you will realize the mistake.

**Comment by DestinedDeveloper** [comment]
Thank you very much, this solved the problem.
