### ISSUE TITLE
SMTPNotSupportedError at / SMTP AUTH extension not supported by server.

### ISSUE THREAD

**Issue by obedsayyad123** [miguelgrinberg/microblog#201]
Im getting this error in django to send email using office 365

**Comment by miguelgrinberg** [comment]
This isn't a Django repository, sorry.

**Comment by obedsayyad123** [comment]
> This isn't a Django repository, sorry.

Okay sir, I had a question, how to send Email using sendGrid Template in Django ?


thank you

**Comment by miguelgrinberg** [comment]
@obedsayyad123 I'm not sure why you are asking me Django questions, I really do not have much experience with it, I use Flask. Maybe this StackOverflow questions tells you what you need to know? https://stackoverflow.com/questions/30140940/how-to-use-designed-template-in-django-using-sendgrid-api.
