### ISSUE TITLE
Error when flask runs 

### ISSUE THREAD

**Issue by Elliot727** [miguelgrinberg/microblog#202]
![image](https://user-images.githubusercontent.com/39097740/72822335-d326f600-3c69-11ea-8162-f6b84c13ea55.jpg)
New error message
WHAT DO I DO

**Comment by miguelgrinberg** [comment]
What do you have in microblog.py? The error suggests you don't have `app` defined there.

**Comment by Elliot727** [comment]
from flask import current_app as app

**Comment by miguelgrinberg** [comment]
@Elliot727 how did you come up with that? Have you followed Chapter 1 of the tutorial?

**Comment by Elliot727** [comment]
I have done chapter 1 and then tried to make my own stuff

**Comment by Elliot727** [comment]
I looked on other forums and it said to write that instead of FROM APP IMPORT APP

**Comment by miguelgrinberg** [comment]
@Elliot727 I can't really help with some out of context thing you copied from another resource, sorry. Not sure why this is done on that other tutorial, you need to ask the author.

**Comment by Elliot727** [comment]
If I change it back it says CAN’T IMPORT APP

**Comment by miguelgrinberg** [comment]
What else did you change? You need to have `app` defined in `app/__init__.py`, as shown in my tutorial.

**Comment by Elliot727** [comment]
I changed nothing else

**Comment by miguelgrinberg** [comment]
I don't understand. You put back this change in microblog.py and that's it, there are no other changes? That's not possible, the tutorial works well, your error indicates you are not defining `app` in the correct way.

**Comment by Kunal614** [comment]
@Elliot727 can you show the code ?
