### ISSUE TITLE
Chapter 6 error

### ISSUE THREAD

**Issue by felipedeaquino** [miguelgrinberg/microblog#203]
Hi! First of all, I am really thankfull for the great tutorial that you gave to us, newbies. Amazing content.

Now about my issue, that's actually a comment for a strange "reaction" of my code. I really have no idea of what on Earth has happened in my @app.route('/user/<username>') part. I was getting an error until I wrote that bold part on my text editor. Pause. I'm so insecure about my English skills that I didn't want to write to you about this error and, realising that my code was ok after this I just moved on. Now that I thought that maybe someone could face the same problem, I decided to write about that error and deleted the "username=current_user.username" part just to receive back the same error and... nothing wrong happened. I have no idea why nor what was the error message before. Duh.

Thanks anyway. Best regards from Brazil.

(I just stopped my code at the Unit Testing the User Model part. Right before).

@app.route('/user/<username>')
@login_required
def user(username):
	user = User.query.filter_by(username=username).first_or_404()
	posts = [
		{'author': user, 'body': 'Test Post#1'},
		{'author': user, 'body': 'Test Post#2'}
	]
	return render_template('user.html', user=user, posts=posts, **username=current_user.username**)

**Comment by miguelgrinberg** [comment]
Your English is perfectly fine. :)

The error must have been caused by a reference you had in the user.html template to `username`. Note that I use `user.username`, which is fine because we are also passing `user` as a template argument.
