### ISSUE TITLE
Form not loading in Chapter 3

### ISSUE THREAD

**Issue by d8aninja** [miguelgrinberg/microblog#205]
There seems to be quite a bit of difference between what [you have](https://github.com/miguelgrinberg/microblog/blob/v0.3/app/routes.py) tagged as `v0.3` and what is in [Chapter 3](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-iii-web-forms):

```
from flask import render_template
from app import app
from app.forms import LoginForm

# ...

@app.route('/login')
def login():
    form = LoginForm()
    return render_template('login.html', title='Sign In', form=form)
```

Additionally, neither of the examples above will let me `from app.forms import LoginForm` and throw the error: `ModuleNotFoundError: No module named 'app.forms'`.  If instead I `from forms import LoginForm` the app runs and I can access `localhost:5000/index` and `/login` but they do not look like your screenshot on the blog:

![image](https://user-images.githubusercontent.com/3494773/73418298-4a96fe00-42d8-11ea-9ecd-640483921469.png)

Am I missing something?

My codebase is [here](https://github.com/d8aninja/persCode/tree/master/python/microblog).

**Comment by d8aninja** [comment]
Ah, I see that the additional items (eg, `validate_on_submit`, the methods) are below where I am; but I am still not getting that form loaded correctly with either of those `routes.py`s...

**Comment by miguelgrinberg** [comment]
When you get to these situations, my advice is that you check my code carefully. Note that forms.py is inside the app folder, not outside like you have it.
