### ISSUE TITLE
Error Handling with Email (Gmail)

### ISSUE THREAD

**Issue by braintho** [miguelgrinberg/microblog#206]
I followed your instructions in chapter 7 to configure the logging to email, specifically gmail.  However, I am getting this error:
    "STARTTLS extension not supported by server.")
smtplib.SMTPNotSupportedError: STARTTLS extension not supported by server.

not sure what I'm doing wrong here.  I was able to send the email to the console using your instructions, but it only worked once.  Without changing any code, the console will now not receive the  email log, and I am getting the same traceback regarding "STARTTLS extension... any ideas on what I can be doing wrong.

Thanks for the assistance, and great book.

**Comment by miguelgrinberg** [comment]
My guess is that you have problems with your settings. Are you running your application in debug mode? If you are, then Flask-Mail shows additional logging on your terminal that could give you more clues about the problem.

**Comment by braintho** [comment]
when you say settings you mean the variables that I set like MAIL_SERVER etc.?

**Comment by braintho** [comment]
after resetting my variables I am getting a new message:
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials b15sm2226168otl.60 - gsmtp')

I reset all of my variables multiple times and I'm 100% sure the username and password are correct.  After looking at the link provided in the error my settings should look like this:

Outgoing Mail (SMTP) Server	
smtp.gmail.com
Requires SSL: Yes
Requires TLS: Yes (if available)
Requires Authentication: Yes
Port for SSL: 465
Port for TLS/STARTTLS: 587
Full Name or Display Name	Your name
Account Name, User name, or Email address	Your full email address
Password	Your Gmail password

Do you think that I need to do something with the SSL port? It's not defined in my variables anywhere

**Comment by braintho** [comment]
Feel free to close this one.  I figured out my issue.  The username needs to equal the complete email address.
