### ISSUE TITLE
Instance of 'SQLAlchemy' has no 'Column' member

### ISSUE THREAD

**Issue by Sharan-Athiyadath** [miguelgrinberg/microblog#213]
Hi i was following your flask mega tutorial, In chapter 22 (Database Models) i came into the following issue. `Instance of 'SQLAlchemy' has no 'Column' member pylint(no-member)`

code : 

```
from datetime import datetime
from app import db


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128)) 

    def __repr__(self):
        return '<user {}>'.format(self.username)
```

Please help

**Comment by miguelgrinberg** [comment]
This isn't an issue, you are mistaken. Pretty sure if you run the code it will run just fine, yes?

Your issue is that pylint is flagging a problem in a piece of code that is correct. Pylint is wrong here.

**Comment by braian87b** [comment]
you should add

```
# pylint: disable=no-member
```
at the begginning of the file between shebang/coding encoding definition and the imports
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# pylint: disable=no-member
"""
this is a file blah blah
"""
import os
```
and that will ensure pylint stop complaining about that.

**Comment by miguelgrinberg** [comment]
@braian87b that is going to eat up all the `no-member` errors in your file. While this particular one was a false positive, you would not want to silence any others that may be correctly flagged.
