### ISSUE TITLE
ImportError: cannot import name 'app' from 'app' 

### ISSUE THREAD

**Issue by rodaarg** [miguelgrinberg/microblog#218]
Hello everyone, I'm Roda from Argentina.
Having reached chapter 7 I find this import problem that has not happened to me before.
The only caveat is that I called the folder and the file "proyectpepiroda" instead of Microblog.
I repeat, I had no problem until after creating errors.py and adding it to the import in __init__.py

(venv) roda@roda-Swift-SF314-52G:~/proyectpepiroda$ flask run
 * Serving Flask app "proyectpepiroda.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "proyectpepiroda", an ImportError was raised:

Traceback (most recent call last):
  File "/home/roda/proyectpepiroda/venv/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/roda/proyectpepiroda/proyectpepiroda.py", line 2, in <module>
    from app import db
  File "/home/roda/proyectpepiroda/app/__init__.py", line 6, in <module>
    from app import app
ImportError: cannot import name 'app' from 'app' (/home/roda/proyectpepiroda/app/__init__.py)

**Comment by miguelgrinberg** [comment]
Why do you have `from app import app` in `__init__.py`?

You should be creating the `app` instance in this file, not import it: https://github.com/miguelgrinberg/microblog/blob/7a60858dbb9e5e1fae7e7fab820433c854f19027/app/__init__.py#L7
