### ISSUE TITLE
some problems on validating the global searching keywords in The Flask Mega-Tutorial Part XVI: Full-Text Search

### ISSUE THREAD

**Issue by milolou** [miguelgrinberg/microblog#219]
```
@bp.route('/search')
@login_required
def search():
    if not g.search_form.validate():
        return redirect(url_for('main.explore'))
    page = request.args.get('page', 1, type=int)
    posts, total = Post.search(g.search_form.q.data, page,
                               current_app.config['POSTS_PER_PAGE'])
    next_url = url_for('main.search', q=g.search_form.q.data, page=page + 1) \
        if total > page * current_app.config['POSTS_PER_PAGE'] else None
    prev_url = url_for('main.search', q=g.search_form.q.data, page=page - 1) \
        if page > 1 else None
    return render_template('search.html', title=_('Search'), posts=posts,
                           next_url=next_url, prev_url=prev_url)

```
######

Hello,I got some problem here,after a lot of times of trying,i found that the validation won't work,
everything else works fine,so i think there must be something wrong here:

```
from flask import request

class SearchForm(FlaskForm):
    q = StringField(_l('Search'), validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata'] = request.args
        if 'csrf_enabled' not in kwargs:
            kwargs['csrf_enabled'] = False
        super(SearchForm, self).__init__(*args, **kwargs)

```
could you please explain this for me? by the way i have try another way to do the global searching,
i'm using the "request.args.get" method to get the "q" parameter directly.waiting for your ansewers,thanks!

**Comment by miguelgrinberg** [comment]
What do you mean by "the validation won't work" exactly?

**Comment by milolou** [comment]
I mean the validation on the form didn't catch the data ，so the 'validate'
function doesn't work well.

在 2020年3月31日星期二，Miguel Grinberg <notifications@github.com> 写道：

**Comment by miguelgrinberg** [comment]
What is the validation error?

**Comment by milolou** [comment]
@bp.route('/search')
@login_required
def search():
      try:
          exp = request.args.get('q')
      except:
          return redirect(url_for('main.explore'))
      page = request.args.get('page',1,type=int)
      posts,total = Post.search(exp,page,current_app.config['POSTS_PER_PAGE'])
      next_url = url_for('main.search',q=exp,page=page + 1) \
              if total > page * current_app.config['POSTS_PER_PAGE'] else None
      prev_url = url_for('main.search',q=exp,page=page - 1) if page > 1 else None
      return render_template('search.html',title=_('Search'),posts=posts,
             next_url=next_url,prev_url=prev_url)

I've change the function into this way,the old way can't catch the 'q' parameter from the request in "g.search_form.validate()",so i think the function 'validate' might have something wrong,Function encapsulation have made me some hard understanding the process of getting the 'q' parameter and validating the data,by the way, i think this 'kwargs['formdata'] = request.args' didn't help to get the 'q' parameters in the url,

def __init__(self, *args, **kwargs):
    if 'formdata' not in kwargs:
        kwargs['formdata'] = request.args
    if 'csrf_enabled' not in kwargs:
        kwargs['csrf_enabled'] = False
    super(SearchForm, self).__init__(*args, **kwargs)

this one, i don't know how the 'csrf' would be sent,it's really wierld, i think i may check the source code of 'db.Model'.

**Comment by milolou** [comment]
`123 @bp.route('/search')
124 @login_required
125 def search():
126     try:
127         exp = request.args.get('q')
128     except:
129         return redirect(url_for('main.explore'))
130     page = request.args.get('page',1,type=int)
131     posts,total = Post.search(exp,page,current_app.config['POSTS_PER_PAGE'])
132     next_url = url_for('main.search',q=exp,page=page + 1) \
133             if total > page * current_app.config['POSTS_PER_PAGE'] else None
134     prev_url = url_for('main.search',q=exp,page=page - 1) if page > 1 else None
135     return render_template('search.html',title=_('Search'),posts=posts,
136             next_url=next_url,prev_url=prev_url)
`

**Comment by miguelgrinberg** [comment]
The validate method comes with Flask-WTF, I'm 100% certain it works well. I suggest you compare your code against mine, something on your side must be different.

**Comment by milolou** [comment]
Fine，
