### ISSUE TITLE
First migration not working

### ISSUE THREAD

**Issue by Alexis-benoist** [miguelgrinberg/microblog#22]
Hey,

First of all, I want to thank you for the wonderful tutorial 👍 

On my computer, when I run the [first migration](https://github.com/miguelgrinberg/microblog/blob/master/db_repository/versions/001_migration.py).

I don't have the same file as you. I do the order explained on the blog post:
1. Create class user
2. python db_create.py
3. python db_migrate.py

I have an empty migration file.

If I do:
1. python db_create.py
2. Create class user
3. python db_migrate.py

The file is the good one. It seems logical to me. What do you think?

Cheers,
Alexis.

**Comment by miguelgrinberg** [comment]
Closing this issue, as it does not apply anymore.
