### ISSUE TITLE
cannot import name 'current_app'

### ISSUE THREAD

**Issue by Elfreezy** [miguelgrinberg/microblog#221]
Can you help me with it, pls.
I also tried to run the original repository v0.15 with your requirements, but it gave the same error

Traceback (most recent call last):
  File "/home/sergey/documents/Flask/run.py", line 6, in <module>
    app = create_app(Config)
  File "/home/sergey/documents/Flask/app/__init__.py", line 42, in create_app
    from app.auth import bp as auth_bp
  File "/home/sergey/documents/Flask/app/auth/__init__.py", line 5, in <module>
    from app.auth import routes
  File "/home/sergey/documents/Flask/app/auth/routes.py", line 9, in <module>
    from app.auth.mail import send_password_reset_email
  File "/home/sergey/documents/Flask/app/auth/mail.py", line 3, in <module>
    from app.mail import send_email
  File "/home/sergey/documents/Flask/app/mail.py", line 2, in <module>
    from app import mail, current_app
ImportError: cannot import name 'current_app'

[requirements.txt](https://github.com/miguelgrinberg/microblog/files/4434336/requirements.txt)
Python 3.6.9

**Comment by miguelgrinberg** [comment]
Are you following the tutorial? It does not look like you are.

**Comment by Elfreezy** [comment]
I only skipped Ajax and made small edits in the code
![изображение](https://user-images.githubusercontent.com/56732709/78548394-68696d80-7809-11ea-9080-c24fc301aadc.png)

**Comment by Elfreezy** [comment]
When app was a global variable it worked

**Comment by miguelgrinberg** [comment]
Your small edits include a brand new file called mail.py that I cannot help you with because it's not part of the tutorial. You are importing `current_app`. Review that part, that seems wrong. At least you may want to import it from `flask`, not from `app`.

**Comment by Elfreezy** [comment]
> At least you may want to import it from flask, not from app.

thx, it helped
