### ISSUE TITLE
Request for implementation of Flask-SocketIO

### ISSUE THREAD

**Issue by xtlc** [miguelgrinberg/microblog#223]
The microblog tutorial is great, but creates a very static page. One way to change that is using your package SocketIO, but honestly I have a huge struggle with implementing it to refresh the "posts" page for example. Could you maybe extend the tutorial to do so?

EDIT: Some code for a working table update written in JS:

**routes.py**
_create a route that is called from the jQuery function:_

```
@app.route('/refreshTableRoute', methods=['GET'])
@login_required
def update_data():
	updatedata= [{"id": 0, "content": "hello world"}, {"id": 1, "content": "foo/bar"}, 
	return jsonify(updatedata)

_th index page is very slim now:_
@app.route('/')
@app.route('/index')
@login_required
def index(messages=None):
	return render_template("index.html", title="Home")
```

**base.html**
_this is where the magic happens - a few includes **before** the bootstrap includes are necessary:

```
<!-- include for a jQuery environment -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>

<script type="text/javascript">
   function refreshTableRoute()  {  
       var tableupdate = function(data) {              
           var rows = "";
           $.each( JSON.parse(data), function(i, item) { 
               rows = rows + "<tr><td>" + item.status + "</td> \
                                  <td>" + item.id+ "</td> \
                                  <td>" + item.content+ "</td></tr>";
           } );
           $("#tablerow").html(rows);
       }                                                                                             
       $.get( "/refreshTableRoute", "", tableupdate, "html" ) // rest aufruf 
   };
   window.setInterval(refreshTable, 10000)
</script>
```

**The index.html**
_this is fairly simple, just be sure to include a table with the correct Ids from the jQuery script_

```
<div class="container">
    <table class="table sortable table-striped table-hover" style="width: 100%"> 
        <thead> <tr> <th>status</th> <th>serial</th> <th>gbc</th> <th>smof</th> <th>ip</th> <th>mac</th> <th>devices</th> <th>step</th> </tr> </thead> 
            <tbody id="tablerow">
            </tbody>
        </table>
</div>
```

So this was my first attempt, and I also went for a smarter one once I understood that concept with a little forum reading and help: [datatables](www.datatables.net) and I used the [Data array location 2nd example in the ajax section](https://datatables.net/manual/ajax#Data-array-location):

**base.html**
_more includes, way less messy code_
```
<script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.20/sl-1.3.1/datatables.min.css"/> 
<script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.20/sl-1.3.1/datatables.min.js"></script> 


<script type="text/javascript">
$(document).ready( function () {        
    var table = $('#live_table').DataTable( {
        "ajax": {
            url: "/refreshTableRoute",
            dataSrc: ""
        },
        columns: [
            { data: "id" },
            { data: "content" },
        ],
    });
    setInterval( function () {
        table.ajax.reload( null, false ); 
    }, 10000 );
} );
</script>
```

**index.html**
_looks much easier now:_
```
<div class="container">
	<table id="live_table" class="table sortable table-striped table-hover" style="width: 100%"> 
		<thead> <tr><th>id</th> <th>content</th></tr> </thead> 
			<tbody>
			</tbody>
		</table>
</div>
```

I really hope this helps some of you to improve their code. Maybe @miguelgrinberg you can add the datatables setup in your guide, as it is only a few lines of code and fairly simple? Please also keep in mind that I am quite novice in jQuery and some bad practices might have been applied.

**Comment by miguelgrinberg** [comment]
Dynamically updating a list of posts is not a good UX design in my opinion, users will find it distracting and annoying when the contents move around on their own to make space for new posts. Did you notice that Twitter/Facebook/etc don't do this?

What I suggest is that you extend the notifications framework shown towards the end of the tutorial to have the page show a small and non-intrusive "new posts available" or similar that the user can click to refresh the page and see the new stuff. This should be a small extension, not a major change.

**Comment by xtlc** [comment]
From an UX perspective you are probably right. Nevertheless as a flask beginner I am struggling to understand how to implement an update on values of an HTML table dynamically and I thought I could maybe use socketIO to do so. I know it could be done using jQuery, but I am struggeling with that.

**Comment by miguelgrinberg** [comment]
@xtlc I'm 100% with you on dynamic page updates being hard, specially if you are beginner.

The task could be separated into two big parts: one is the dynamic communication between server and clients, and the other is making dynamic updates to a page. These two are fairly independent of each other.

The first is the problem that Flask-SocketIO attempts to solve, though the notifications solution in the Flask Mega-Tutorial is also a valid approach.

The second part is the part that you may find more difficult, and this is entirely in the JavaScript/browser domain, so it is a completely different range of skills that you will need to learn. If all you want to do is modify some table cells, then the easiest way to do this is to wrap each cell in a `<div id="some-unique-id"> ... </div>`. Then you can use jQuery to replace the contents of the cell with something like `$('#some-unique-id').html('<p>some new stuff here!</p>')`.

**Comment by xtlc** [comment]
First, thanks a lot for spending effort here!
My goal was to update the table every few seconds, as the table gets it's information from an SQL database from another process and I did not want to fiddle with triggers ... 
I thought I could maybe add a jQuery that does that by getting the content of the database in a json or so and refresh that every few secs to avoid complicated socket implementation. 

I know I need a new route or something, but I could not yet wrap my head around it and I will try to update this post as soon as I have something, so others can find help here.

**Comment by miguelgrinberg** [comment]
@xtlc have you seen the posts on REST APIs on my blog? Those will give you a good idea of how to return JSON data from Flask. In jQuery you can use `$.ajax()` to send the request, and then in the success callback you can do your table updating using jQuery's `$('#id').html(...)` function. Hope this send you well on your way to success. By all means do post your solution here for others to benefit from.

**Comment by xtlc** [comment]
I updated my first post to represent two solutions I made so far.
