### ISSUE TITLE
Testing routes

### ISSUE THREAD

**Issue by kylepw** [miguelgrinberg/microblog#225]
Hi Miguel,

Question about testing views. I'm having trouble writing a test for a route that modifies the database. The test checks that the database was modified after the request. Let's say for your route that adds followers.
```
@bp.route('/follow/<username>')
@login_required
def follow(username):
...
```
Given  test_client, login, and pre-loaded database fixtures initialized with the same app instance:

```
def test_follow(client, db, login):
r = client.post('/follow/howard', data=(...), follow_requests=True)
assert r.status_code == 200

me = User.query.filter_by(username='me').first()
howard = User.query.filter_by(username='howard').first()
assert  howard in me.followed
```
Would this be the right way to go? Also, would this work in case of a view function that adds users to the database?

Thanks in advance,
Kyle

**Comment by miguelgrinberg** [comment]
It should work, I think. Have you tried it?

The only thing you need to keep in mind is that if you use the database in your test you may inadvertently modify a database session that then is used by the server code. In general this isn't a problem, but sometimes it can affect the way the server code runs in strange ways.

**Comment by kylepw** [comment]
So, I tried to add a test on the follow view like so, but the last two assertions fail. Any tips?

```
def test_follow_view(self):
        # create two users
        u1 = User(username='john', email='john@example.com')
        u1.set_password('johnspass')
        u2 = User(username='susan', email='susan@example.com')
        db.session.add_all([u1, u2])

        self.assertEqual(len(u1.followed.all()), 0)
        self.assertNotIn(u2, u1.followed.all())

        with self.app.test_client() as client:
            r = client.post('/auth/login', data=dict(
                username='john',
                password='johnspass',
                remember_me=False,
                submit='Sign In'
            ), follow_redirects=True)
            self.assertEqual(r.status_code, 200)
        
            r = client.get('/follow/susan', follow_redirects=True)
            self.assertEqual(r.status_code, 200)

            self.assertEqual(len(u1.followed.all()), 1)
            self.assertIn(u2, u1.followed)
```

**Comment by miguelgrinberg** [comment]
Failed how? I assume it was an obscure session related error?

This is related to the "strange" side effects I mentioned above. You created `u1` at the top of the test. Then sent a bunch of requests, which started new database sessions. At the bottom of the test, the original session under which `u1` existed is long gone, so `u1` is likely an orphan object without a session.

The easiest way to avoid session problems is to query the object from the database when you need it. Do not rely on objects loaded earlier.

**Comment by kylepw** [comment]
The error I got was 
```Traceback (most recent call last):
  File "/Users/kylepw/dev/microblog/tests.py", line 125, in test_follow_view
    self.assertEqual(len(u1.followed.all()), 1)
AssertionError: 0 != 1
```
I tried grabbing new objects right before the assertion tests at the end (while still in the same `app.test_client()` context as the requests, but still same error.
```
...
u1 = User.query.filter_by(username='john').first()
u2 = User.query.filter_by(username='susan').first()

self.assertEqual(len(u1.followed.all()), 1)
self.assertIn(u2, u1.followed)
```

**Comment by miguelgrinberg** [comment]
I haven't seen your implementation of the `follow()` method. Does it commit the session?

**Comment by miguelgrinberg** [comment]
What you should have done is make your checks more robust. When you send a request the only thing you check is that you've got a 200 response. But in a web app even when something does not work the code is 200. Consider you send bad login credentials. The response is going to be 200, and somewhere in the page there is going to be an alert line with the error message.

I looked at the output of your tests and found that the follow request was failing with a "Please login to do this operation". Then I looked at the output of the login request and it said "CSRF token is missing", which makes sense, all forms have an extra hidden field that implement the CSRF protection.

The solution is to disable CSRF checks during tests:

```python
class TestConfig(Config):
    TESTING = True
    SQLALCHEMY_DATABASE_URI = 'sqlite://'
    ELASTICSEARCH_URL = None
    WTF_CSRF_ENABLED = False
```

Then your test works fine.

**Comment by kylepw** [comment]
Great stuff. Thanks, @miguelgrinberg !
