### ISSUE TITLE
Problem in Chapter 3 using flask-wtf

### ISSUE THREAD

**Issue by TriumphTodd** [miguelgrinberg/microblog#228]
Hi, This is not really an issue but FYI, in working through chapter 3, I had trouble using the current version of flask-wtf or, technically, werkzeug.  There was apparently a change to the way werkzeug handled url encoding as documented in [this link](https://github.com/pallets/flask/issues/3481).  The solution (albeit temporary I guess) is to downgrade to a prior version of werkzeug as noted in that link.

Here is my stack trace:

[werkzeug_error.txt](https://github.com/miguelgrinberg/microblog/files/4536379/werkzeug_error.txt)

**Comment by miguelgrinberg** [comment]
This is caused by Werkzeug deprecating some symbols. Instead of downgrading werkzeug try upgrading Flask-WTF to the latest release.
