### ISSUE TITLE
tutorial heroku deployment - heroku-postgresql:dev updated to heroku-postgresql:hobby-dev

### ISSUE THREAD

**Issue by ghost** [miguelgrinberg/microblog#23]
When creating a Heroku database on this page of the tutorial - http://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xviii-deployment-on-the-heroku-cloud

heroku addons:add heroku-postgresql:dev

should now be

heroku addons:add heroku-postgresql:hobby-dev

**Comment by Himanshi-Khandelwal** [comment]
the heroku addons comand is:
heroku addonns:create heroku-postgresql:hobby-dev

**Comment by miguelgrinberg** [comment]
Closing this issue, as it does not apply anymore.
