### ISSUE TITLE
Error: Could not import "app". 

### ISSUE THREAD

**Issue by TimEulink** [miguelgrinberg/microblog#231]
I've made a flask API in visual studio code, now I moved my app to a git folder. But when I want to run it from my git folder I get the following error. 

> Error: Could not import "app"

Both applications are the exact same, I just ctrl + c / ctrl +v them.
Does anyone know why this error appears?. Thanks in advance.

**Comment by miguelgrinberg** [comment]
I suggest you review chapter 1 of the tutorial. In particular, make sure you set FLASK_APP correctly and that you do not have any missing imports that could be causing this error. You can also start a Python shell and run `import app` in the prompt to see what error(s) you get.

**Comment by TimEulink** [comment]
Thanks for your comment, the error was in the launch.json I deleted the file and restarted visual code. then running the application as a Flask application. Thanks for your help
