### ISSUE TITLE
(Question) wrong logic  flask/wtf -> sqlite <- flask/wtf  date/datetime objects

### ISSUE THREAD

**Issue by littlegreenbean33** [miguelgrinberg/microblog#233]
This is actually asking for help. I am doing the Flask megatutorial (paid), currently in chapter 12.

In parallel I am building a similar, but different application just to build on my own example. Changed posts for prods(products)
This is the set up

models.py
```
.......
f_compra = db.Column(db.DateTime, index=True)
f_consumo = db.Column(db.DateTime)
......
```
forms.py
```
f_compra = Datefield("f.compra",validators=[DataRequired()])
f_consumo = Datefield("f.compra",validators=[DataRequired()])
```
When I add an element I noticed that in the database the information is already represented differently
f_compra --> "2020-05-29 00:00:00.000000"
f_consumo --> "2020-05-29"

I presume this is because f_compra is a primary index

Now when I pull the data from the database to show in a template using moment I get into trouble because when I issue a 
```
prods = current_user.prods.order_by(Prod.f_compra.desc())
```
f_compra is retrieved as a **datetime** object, however f_consumo is retrieved as a **string**

Hence when later I render the page using moments
```
.....
 moment(prod.f_compra).format("L") #is OK but
 moment(prod.f_consumo).format("L")      # blows up
.....
```

This was unexpected for me. My expectation is that if my datamodel says a column is datetime, it is stored and retrieved as datetime. In no case a conversion is done into str (at least without warning)

am I missing anything ???

Thanks

JC

**Comment by littlegreenbean33** [comment]
I tested the index hypothesis ...and it is incorrect. Even in f_consumo and f_compra are index in the database, even if I exchange the query to "by f_consumo" I still get a datetime object in one variable and a string in the other one,

**Comment by miguelgrinberg** [comment]
Did you check the schema in your database? Are these two columns represented with the same type there? I suspect you must have an inconsistency between the schema and your models.

**Comment by littlegreenbean33** [comment]
Miguel,

you were right. For reasons beyond my understanding the schema generated did not match the right type for that field. I just do not know why. Everything else is fine

I delete migrations folder and the data base.

Did a complete init/migrate/upgrade cycle (no code changes) and now the schema is consistent with the models.py

I am still confused about what happen, but many many thanks for pointing me into the right direction.

Cheers.

JC
