### ISSUE TITLE
Flask starter code

### ISSUE THREAD

**Issue by lakshaykhatter** [miguelgrinberg/microblog#237]
Hi Miguel,

I was hoping to ask if you could make a flask starter project. The reason is I love the way you've set the book up and I use it as a starting point for many of my projects but I have to get rid things like translate and search to adapt it to the new project. The book itself is great!

**Comment by miguelgrinberg** [comment]
I don't think creating one more starter project is going to help. There are a million or more out there already, and they are always "almost" perfect, and people feel the need to create one more!

I recommend that you create the structure that works for you and keep it handy to reuse. What I think is the best starter structure is not going to satisfy everyone.
