### ISSUE TITLE
html issues.maybe jinja....

### ISSUE THREAD

**Issue by garryforgit** [miguelgrinberg/microblog#24]
I almost write the demo with your  mega-flask tutorial except the localization.

one month ago,i just run the demo perfectly,but when i rewrite it recently ,i made a exception.

here it is:
>File "/home/fly/dev/py2/microblog/app/templates/base.html", line 28, in top-level template code
$(destId).text("{{_('Error: Could not contact server.') }}");
UndefinedError: '_' is undefined

so i just delete the '_' on line 28 (in your program is line 31) on base.html 

but , it occurs a new exception,i also delete '_' in the line.

> File "/home/fly/dev/py2/microblog/app/templates/post.html", line 6, in template
<p>{{ ('%(nickname)s said %(when)s:', nickname='<a href="%s">%s</a>' % (url_for('user', nickname=post.author.nickname), post.author.nickname), when=momentjs(post.timestamp).fromNow() ) }}</p>
TemplateSyntaxError: expected token ')', got '='

I googled it but can't find a similar answer,so could your test it ?maybe jinja's grammer has changed?

my environment is debian8_64bit, python 2.7.9, chrome51, jinja2.8 
Thanks !

**Comment by miguelgrinberg** [comment]
Does the code checked out from this repository give you the same error?

**Comment by garryforgit** [comment]
No, i just  reset it using git....
Now it is perfect running in local, anaway, thanks for everything~
