### ISSUE TITLE
pytesting Microblog v0.23 - KeyError: 'ELASTICSEARCH_URL'

### ISSUE THREAD

**Issue by mrbiggleswirth** [miguelgrinberg/microblog#240]
Hi @miguelgrinberg I wanted to start implementing pytest on the Microblog v.023 code.
https://github.com/miguelgrinberg/microblog/releases/tag/v0.23

### Flaskr pytest guide
I followed FlaskPalletsProjects.com Flaskr **pytest example** guide. Which I then wanted to refactor and use on my Microblog code. I managed to make their Flaskr installation work, but their documentation and boilerplate template code is difficult to untangle and understand for Microblog **"Borg assimilation"**.
https://github.com/pallets/flask/tree/1.1.2
https://github.com/pallets/flask/blob/1.1.2/examples/tutorial/tests/test_factory.py
https://flask.palletsprojects.com/en/1.1.x/testing/#logging-in-and-out - Pytesting Flask Apps

### My Microblog pytest failure
I'm getting this KeyError: 'ELASTICSEARCH_URL' pytest failure when copying Flaskr's pytest code for use on Microblog v.023. **Do you have any clues how I can make this test pass without disabling or removing the Elasticsearch code?**

https://github.com/pallets/flask/blob/1.1.2/examples/tutorial/tests/test_factory.py
```
ubuntu@Matrix:/microblog-0.23$ pytest -v tests/setup/
==================== test session starts =================
platform linux -- Python 3.6.9, pytest-5.4.1, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: xxx
collected 1 item

tests/setup/test_factory.py::test_config FAILED                                     [100%]

==================== FAILURES ======================
________________________________ test_config ____________________________________

    def test_config():
        """ Test 'create_app' without passing test config. """
        assert not create_app().testing
>       assert create_app({'TESTING': True}).testing

tests/setup/test_factory.py:12:
#_______________________________________________________________________________
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
project/__init__.py:47: in create_app
    initialize_extensions(app)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

app = <Flask 'project'>

    def initialize_extensions(app):
        # Since the application instance is now created, pass it to each Flask
        # extension instance to bind it to the Flask application instance (app).

        db.init_app(app)
        migrate.init_app(app, db)
        login.init_app(app)
        mail.init_app(app)
        bootstrap.init_app(app)
        moment.init_app(app)
        babel.init_app(app)
        app.elasticsearch = Elasticsearch([app.config['ELASTICSEARCH_URL']]) \
>           if app.config['ELASTICSEARCH_URL'] else None
E       KeyError: 'ELASTICSEARCH_URL'

project/__init__.py:113: KeyError

------------------------------ Captured log call ---------------------------------

INFO     project:__init__.py:85 Microblog startup
================== warnings summary ==================
tests/setup/test_factory.py::test_config
  /home/ubuntu/.local/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:814: 
    * UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set.
    Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
    'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '

tests/setup/test_factory.py::test_config
  /home/ubuntu/.local/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:835:
    * FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds
      significant overhead and will be disabled by default in the future.
    Set it to True or False to suppress this warning.
    'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '

-- Docs: https://docs.pytest.org/en/latest/warnings.html

================ short test summary info =================
FAILED tests/setup/test_factory.py::test_config - KeyError: 'ELASTICSEARCH_URL'
================ 1 failed, 2 warnings in 0.37s ==============
ubuntu@Matrix:/microblog-0.23$

```

**Comment by miguelgrinberg** [comment]
The `ELASTICSEARCH_URL` config option isn't defined. Do you know what that is? It should have been defined [here](https://github.com/miguelgrinberg/microblog/blob/master/config.py#L22). Do you know why it isn't defined in your test run?

**Comment by mrbiggleswirth** [comment]
Flaskr guide wanted to perform a pytest forcing not loading the config values by intention. Which I don't fully understand, the Flaskr team didn't provide any explanations in docs I can see why they wanted to test such a behavior.

I'm thinking if config failed to load in Production then the entire web app wouldn't work anyways.

https://github.com/pallets/flask/blob/1.1.2/examples/tutorial/tests/test_factory.py
```
from flaskr import create_app

def test_config():
    """Test create_app without passing test config."""
    assert not create_app().testing
    assert create_app({"TESTING": True}).testing
```

Hmm... it looks like I need to drill deeper into the Flaskr config setup code to understand how to assimilate that pytest test into Microblog.
https://github.com/pallets/flask/tree/1.1.2/examples/tutorial

**Comment by mrbiggleswirth** [comment]
### Mega Long Summary

```
ubuntu@Matrix:/microblog-0.23$ pytest -v tests/setup/

============ test session starts =========================
platform linux -- Python 3.6.9, pytest-5.4.1, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /microblog-0.23
collected 1 item

tests/setup/test_factory.py::test_config PASSED    [100%]

=========== 1 passed in 0.25s ==========================

```
There seems to be 3 common ways of setting up configs for a Flask app:
1. Hard coded config values.
2. Class based config style.
3. File based config style.


- **Hard coding config values** here and there. Earlier Microblog chapter versions used this style.

- Until **"Chapter 15: A Better Application Structure"** where later Microblog chapter versions uses class based config style.

- **Patrick Kennedy's "Testing a Flask app using pytest"** tutorial uses file based config style.
https://www.patricksoftwareblog.com/testing-a-flask-application-using-pytest/

- **Flaskr's pytest example code** seems to be a mix of hard coded config values and file based config style. Not sure what's going on there.
https://flask.palletsprojects.com/en/1.1.x/testing/#logging-in-and-out


That's why it has been a struggle copy-pasting pytest tests from other tutorials into Microblog. Because things occur in different orders when the dealing with configs. This is what I had to do in order to "borg assimilate" Flaskr's first pytest for Microblog.


`/microblog-0.23/config.py`
```
import os
from dotenv import load_dotenv

# Get the folder of the top-level directory of this project.
BASEDIR = os.path.abspath(os.path.dirname(__file__))

# load_dotenv(os.path.join(basedir, '.env'))
load_dotenv(os.path.join(BASEDIR, '.flaskenv'))

#_______________________________________________________________________________

class Config(object):
    # Uses 'staging' MySQL database server.

    ..
    ..

#_______________________________________________________________________________

class ProductionConfig(Config):
    # Uses 'production' database server.
    TESTING = False
    DEBUG = False

#_______________________________________________________________________________

class TestingConfig(Config):
    # Uses 'testing' SQLite database file.
    TESTING = True
    DEBUG = True

    # --- SQLAlchemy: SQLite database file. ---
    SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(BASEDIR, 'app_test.db')

    # --- SQLAlchemy: in-memory SQLite database. ---
    # SQLALCHEMY_DATABASE_URI = 'sqlite://'

    SQLALCHEMY_TRACK_MODIFICATIONS = False

    # WTF_CSRF_ENABLED = False # Will be Deprecated by WTF!
    CSRF = False
```

`/microblog-0.23/conftest.py`
```
import pytest
from config import TestingConfig
from project import create_app
from project import db
from project.models import User

@pytest.fixture
def microblog_app():
    """ Create and configure a new app instance for each test. """
    # Create the Flask application and load TestingConfig class.
    app = create_app(TestingConfig)

    with app.app_context():
        pass

    yield app
```

`/microblog-0.23/tests/unit/test_models.py`
..

`/microblog-0.23/tests/functional/test_users.py`
..

`/microblog-0.23/tests/setup/test_factory.py`
```
"""
This file contains the 'Setup Tests' for the application.

"""
from project import create_app

#_______________________________________________________________________________

def test_config(microblog_app):
    """
    Flaskr - Test 'create_app' without passing test config.
    """
#   assert not create_app().testing
#   assert create_app({"TESTING": True}).testing


    """
    Microblog v.0.23 - Test 'create_app' initializing TestingConfig class.
    """
    assert microblog_app.testing
```
https://github.com/pallets/flask/blob/1.1.2/examples/tutorial/tests/test_factory.py - diff
