### ISSUE TITLE
docker ps

### ISSUE THREAD

**Issue by datagene-github** [miguelgrinberg/microblog#242]
Hi Miguel, please when I build the docker using 
docker run --name microblog -d -p 8000:5000 --rm microblog:latest it appears to be ok , because it returns an id, but when i run docker ps it does not return any container.

I have checked the container using docker images and it returns the images, is there a way to trouble shoot it, i tr checking the logs using docker logs microblog, but it says no container with that name.

**Comment by miguelgrinberg** [comment]
The container is ending immediately, for some reason. Remove the `--rm` flag so that it isn't deleted automatically, then check the logs.

**Comment by datagene-github** [comment]
Thanks for the suggestion, I was able to see the log to spot the problem. after that I cleared the container with 
docker system prune -a
and rebuilt , and I can see the container running . Thanks
