### ISSUE TITLE
install microblog project with conda environment in pycharm FAILED

### ISSUE THREAD

**Issue by Adolf-L** [miguelgrinberg/microblog#243]
![image](https://user-images.githubusercontent.com/10137107/85815141-3d544180-b79a-11ea-8c31-f49b8ccd743b.png)
1. As you can see, I create a new conda environment. (microblogenv)
2. I changed PIPY repo images sources in Pycharm. ( default sources are super slow in my country)
3. I install all the requirements as Pycharm notified.
4. problem coming..

NOTE: I know this isusse comes from conda configuration. I should use `pip install` command to install all the libraries. not `conda install -p`

**Comment by miguelgrinberg** [comment]
Not sure what I can do about it. Your conda configuration needs to be fixed, that's all this is as far as I can see.

**Comment by canartuc** [comment]
Conda is not pip as well as yarn is not npm. So use the installation as suggested. You can also use pip in conda environment but conda is not drop in replacement of pip: https://www.anaconda.com/blog/understanding-conda-and-pip
