### ISSUE TITLE
FLASK RUN [ERROR: Could not import "app".]

### ISSUE THREAD

**Issue by redwine629** [miguelgrinberg/microblog#244]
(env) C:\Users\PLAYER1\Documents\flask_app>set FLASK_APP=app.py

(env) C:\Users\PLAYER1\Documents\flask_app>flask run
 * Serving Flask app "app.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: Could not import "app".

(env) C:\Users\PLAYER1\Documents\flask_app>

**Comment by miguelgrinberg** [comment]
What is app.py? That is not part of this tutorial. Shouldn't FLASK_APP by set to `microblog.py`?

**Comment by arohde69** [comment]
if this tutorial serves as a template for your own project, please check the filename in your project-folder. sometimes it is called "runserver.py" for example...so you have to correct the environment variable FLASK_APP to this filename

**Comment by alextoritsin** [comment]
I have the same error. I'am currently going throught VS Code Flask  [tutorial](https://code.visualstudio.com/docs/python/tutorial-flask#_run-the-app-in-the-debugger) and reseaving this error massege after starting debug mode, but server is working properly.
![error](https://user-images.githubusercontent.com/80985067/126904984-90f6cafd-64ba-4ddc-83da-9e24a5c3a215.jpg)

**Comment by edocbuhtig** [comment]
@alextoritsin Your ```app.py``` should be outside your (venv) folder. "Could not import" error is related to the where your app.py resides.

**Comment by chanderbhanu096** [comment]
> I have the same error. I'am currently going throught VS Code Flask [tutorial](https://code.visualstudio.com/docs/python/tutorial-flask#_run-the-app-in-the-debugger) and reseaving this error message after starting debug mode, but server is working properly. ![error](https://user-images.githubusercontent.com/80985067/126904984-90f6cafd-64ba-4ddc-83da-9e24a5c3a215.jpg)
I think Problem is with the directory 
Suppose your directory is like this /A/B/app.py
You need to cd into B then enter the directory where your app.py file is located. then export  then run
pip install flask
export FLASK_APP=app.py(for linux)
flask run

**Comment by maxmenaarguedas** [comment]
Yes @chanderbhanu096 In may case I was running flask outside the folder where the app.py was located. Once I cd to that folder and ran flask from there the WSGA worked

**Comment by lycheebbe** [comment]
I had the same issue, but after I move app.py out of all the folder it seems to work. I encounter a new problem that the page shows 404 not found right now.

**Comment by jmorris236** [comment]
Remember to name file "__init.py__" and not "_init.py_"

**Comment by LAMRA7** [comment]
> I have the same error. I'am currently going throught VS Code Flask [tutorial](https://code.visualstudio.com/docs/python/tutorial-flask#_run-the-app-in-the-debugger) and reseaving this error message after starting debug mode, but server is working properly. ![error](https://user-images.githubusercontent.com/80985067/126904984-90f6cafd-64ba-4ddc-83da-9e24a5c3a215.jpg)

in Windows you can try this solution https://youtu.be/1gLTE6Zvb-Q

**Comment by LAMRA7** [comment]
Could import app error while flask run in Windows you can try this Solution https://youtu.be/1gLTE6Zvb-Q
