### ISSUE TITLE
Cannot import name 'flask' from 'flask' SOLVED

### ISSUE THREAD

**Issue by boarity** [miguelgrinberg/microblog#245]
```
  File "C:\Users\Username\JustPys\flask\application.py", line 1, in <module>
    from flask import flask
ImportError: cannot import name 'flask' from 'flask' (c:\users\Username\appdata\local\programs\python\python38\lib\site-packages\flask\__init__.py)
``
Problem solved with editing my python file. In the Flask home page they teach you to use this line to import: "from flask import Flask"

But it didn't work for me. After bunch of errors I was saved by changing the import to: "from flask import * "

**Comment by miguelgrinberg** [comment]
The correct way to do this is as follows:

    from flask import Flask

The lowercase `flask` and the uppercase `Flask` are important. It must be exactly as shown above.

If that does not work for you, then you have an issue with your Flask installation. Your solution is not something I would recommend. Star imports are not a good practice, they should be avoided.

**Comment by Codynw42** [comment]
> The correct way to do this is as follows:
> 
> ```
> from flask import Flask
> ```
> 
> The lowercase `flask` and the uppercase `Flask` are important. It must be exactly as shown above.
> 
> If that does not work for you, then you have an issue with your Flask installation. Your solution is not something I would recommend. Star imports are not a good practice, they should be avoided.

this is it. the lowercase F. you are a life saver

**Comment by CyberIsPunk** [comment]
> The correct way to do this is as follows:
> 
> ```
> from flask import Flask
> ```
> 
> The lowercase `flask` and the uppercase `Flask` are important. It must be exactly as shown above.
> 
> If that does not work for you, then you have an issue with your Flask installation. Your solution is not something I would recommend. Star imports are not a good practice, they should be avoided.

I tried all the possible methods, including yours, but it does not work. I even tried reinstalling flask and writing the same code that you wrote, but it's not working.

**Comment by Gmonga08** [comment]
I have created venv in vs code, activated it and then installed flask using -
`pip install flask`
Then in a file i tried -
`from flask import Flask`
But it didn't work. It says import not resolved. 
What should i do now?

**Comment by miguelgrinberg** [comment]
@Gmonga08 The Flask Mega-Tutorial provides detailed instructions on how to do this from the terminal. If you are going to deviate from these instructions, then you need to find a tutorial that is appropriate to VScode that shows you how to do this.
