### ISSUE TITLE
pytesting Microblog v0.23 - def test_connect_close_db(app)

### ISSUE THREAD

**Issue by mrbiggleswirth** [miguelgrinberg/microblog#246]
Hi Miguel, I would like to incorporate the `def test_get_close_db(app)` pytest function from Flaskr's pytest example repo into my Microblog v0.23 project.
https://github.com/pallets/flask/blob/1.1.2/examples/tutorial/tests/test_db.py

---

The thing is that Flaskr's example code doesn't use SQLAlchemy which makes the refactoring process confusing to me.
* _I'm wondering do I just copy the relevant database functions from this file **/Flaskr_tutorial/flaskr/db.py** or will that conflict with my Microblog project setup?_
https://github.com/pallets/flask/blob/1.1.2/examples/tutorial/flaskr/db.py

Since **/microblog-0.23/project/__init__.py** file contains this variable configuration I'm thinking it might conflict with how Flaskr wrote their database check test.
```
db = SQLAlchemy()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    db.init_app(app)
```

---

My Microblog test file **/microblog-023/tests/setup/test_db.py**.
* _How do you write a check that can confirm if Microblog database is connected like Flaskr database check does?_
```
def test_connect_close_db(app):
    with app.app_context():
        # Check if database is connected.

        # db = ?
        # assert db is ?
```
Flaskr's test file **/Flaskr_tutorial/tests/test_db.py**.
https://github.com/pallets/flask/blob/1.1.2/examples/tutorial/tests/test_db.py

**Comment by miguelgrinberg** [comment]
I honestly don't know what would be a meaningful equivalent test. In the Flask tutorial the database is managed by hand. The application makes the connections, so it makes sense that there is a test to check that connections are created and destroyed appropriately. With Flask-SQLAlchemy the application doesn't do any of that, so there is really nothing in the application that you can test. If anything, you would be writing tests for the Flask-SQLAlchemy extension, not for your application.

**Comment by mrbiggleswirth** [comment]
I finally understood what you meant. 🙂
