### ISSUE TITLE
How to translate this part of page?

### ISSUE THREAD

**Issue by n0r8as** [miguelgrinberg/microblog#248]
https://github.com/miguelgrinberg/microblog/blob/22fe46f615bd398a8cc69d64e20e8f0ef66e7d01/app/templates/base.html#L42

**Comment by miguelgrinberg** [comment]
Apply the `_('text')` in the code where all the messages are generated, so that the message reaches the template after it was translated. This is done in this tutorial.

**Comment by n0r8as** [comment]
Ok, Thank You

sob., 11 lip 2020 o 18:51 Miguel Grinberg <notifications@github.com>
napisał(a):
