### ISSUE TITLE
Why do we need to use followers.c.followed_id == user.id in is_following method?

### ISSUE THREAD

**Issue by sevanp** [miguelgrinberg/microblog#249]
Hi, 
Thanks for the great tutorial!
Im watching the videos and Im currently at chapter 8.

noticed you are using 
```
def is_following(self, user):
        return self.followed.filter(followers.c.followed_id == user.id).count()>0
```

Im just doing some experiments in flask shell and I'm getting the same results if I do
```
def is_following2(self, user):
        return self.followed.filter(User.id == user.id).count()>0
```
to me using filter expression User.id == user.id is more intuitive.
wondering if I'm missing something here.

Thanks!

**Comment by miguelgrinberg** [comment]
I'm not completely sure, but yes, it seems it could give you the same results as my filter.
