### ISSUE TITLE
http: error

### ISSUE THREAD

**Issue by pythonkid888** [miguelgrinberg/microblog#25]
I have learned chapter 14 in your book 《Flask Web Development》，about use HTTPie test Web Server。when I input "http GET http://127.0.0.1:5000/api/v1.0/posts"  on Windows. I get 
    "http: error: ConnectionError: HTTPConnectionPool(host:'127.0.0.1', port=5000):Max retries exceeded with url:/api/v1.0/posts (Caused by <class 'socket.'error>:[Errno 10061])

    I don't know how to slove this problem。 Thank you !

**Comment by miguelgrinberg** [comment]
Error 10061 suggests that the server isn't running, or that it isn't running on the address or port you are trying to connect to.

**Comment by pythonkid888** [comment]
The problem is that I forgot to run the server,Thank you very much!
