### ISSUE TITLE
test_follow fails as of 7/30/2020

### ISSUE THREAD

**Issue by snaxattax** [miguelgrinberg/microblog#251]
In the test case, you have u1 follow u2, but then assert that u2 has one follower. Only u1 has followers, and the test fails.

https://github.com/miguelgrinberg/microblog/blob/master/tests.py#L53

Maybe it was intended that u2.follow(u1) as well?

Also, thank you very much for this excellent tutorial.

**Comment by miguelgrinberg** [comment]
I'm confused. If u1 follows u2, then u2 does have one follower. So the test is correct, and it actually passes for me.

**Comment by snaxattax** [comment]
You're right, I had a typo and was checking asserts on u2.followed.count instead of u2.followers.count - I appreciate the response, and will close my issue.
