### ISSUE TITLE
Chapter 9 - jinja2 error

### ISSUE THREAD

**Issue by TrustBen** [miguelgrinberg/microblog#253]
Hi,

When I'm moving to the Explore page I'm getting this error:

`  File "D:\Python\microblog\venv\app\templates\_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
jinja2.exceptions.UndefinedError: 'None' has no attribute 'avatar'
`

Since receiving the error I've copied the files in the chapter 9 commit and I still get the error. The _post.html sub template works absolutely fine on the index page.

**Comment by miguelgrinberg** [comment]
You probably have a post in your database that does not have an author assigned.

**Comment by TrustBen** [comment]
thank you! Searched the database and found the unassigned post, deleted and it all works as intended
