### ISSUE TITLE
Translator: might need to specify region

### ISSUE THREAD

**Issue by rebeccamichelle27** [miguelgrinberg/microblog#254]
I was following chapter 14 on translation services and ran into the following problem. When I created the translator in Azure, I wasn't allowed to use the 'Global' option for the region (Microsoft appears to have broken part of their web UI for this), so I had to pick something else. I arbitrarily chose 'australiaeast', but then ran into a problem like so:

```
>>> r = requests.get('https://api.microsofttranslator.com/v2/Ajax.svc/Translate?text=hola como estas?&from=es&to=en', headers={'Ocp-Apim-Subscription-Key': app.config['MS_TRANSLATOR_KEY']})
>>> r.status_code
200
>>> r.content
b'\xef\xbb\xbf"ArgumentException: Invalid Azure Subscription key. : ID=V2_Json_Translate.BNZE.0329.0815T2247.4022172"'
```

(Note that the translator service violates good HTTP practices by returning a 200 status code :woman_shrugging:)

After some sleuthing, I found that I just needed to specify another header indicating the non-default region for my translator resource:

```
>>> r = requests.get('https://api.microsofttranslator.com/v2/Ajax.svc/Translate?text=hola como estas?&from=es&to=en', headers={'Ocp-Apim-Subscription-Key': app.config['MS_TRANSLATOR_KEY'], 'Ocp-Apim-Subscription-Region': 'australiaeast'})
>>> r.status_code
200
>>> r.content
b'\xef\xbb\xbf"Hi, how are you?"'
```

Specifically, I had to add: `'Ocp-Apim-Subscription-Region': 'australiaeast'`

(Where `'australiaeast'` is the region I used when creating the translator service.)

Just figured I'd give you a heads up, and possibly help some others googling for a solution :).

**Comment by miguelgrinberg** [comment]
This is now fixed in the code and in the text of the tutorial.
