### ISSUE TITLE
MySQL warning: cannot change directory to /nonexistent: No such file or directory

### ISSUE THREAD

**Issue by mrbiggleswirth** [miguelgrinberg/microblog#256]
Hi Miguel, I just recently switched and moved my project files from WSL 1 to the **WSL 2** environment.

Specs:
- Ubuntu 20.04 LTS

- Python 3.8.2

.

But I'm having problems starting **MySQL** in **(venv)** environment please see the below warning message. Is this an issue that you have seen in the past? When starting **MySQL** outside of **(venv)** it runs ok.

When I check if **MySQL** is installed in both inside and outside of **(venv)** environment the terminal says that they are installed in both.

```
(venv)$ sudo service mysql start
  * Starting MySQL database server mysqld
    su: warning: cannot change directory to /nonexistent: No such file or directory
    sleep: cannot read realtime clock: Invalid argument

$ sudo service mysql start
  * Starting MySQL database server mysqld

$ mysql --version
  mysql  Ver 8.0.21-0ubuntu0.20.04.4 for Linux on x86_64 ((Ubuntu))

(venv)$ mysql --version
  mysql  Ver 8.0.21-0ubuntu0.20.04.4 for Linux on x86_64 ((Ubuntu))
```

**Comment by mrbiggleswirth** [comment]
I tried to start MySQL again today, but this time only outside of **(venv)** and got the same error as when I  got this error inside of **(venv)** a few days ago.

Then I tried the old "Back to the Future" **Biff Tannen** trick and jiggled the ignition twice and it worked! :)

```
$ source venv/bin/activate

(venv)$ sudo service mysql start
  * Starting MySQL database server mysqld
    su: warning: cannot change directory to /nonexistent: No such file or directory
    sleep: cannot read realtime clock: Invalid argument

(venv)$ sudo service mysql start
  * Starting MySQL database server mysqld     [ OK ]
```

**Comment by CHINOBv** [comment]
How can resolve this? :/

**Comment by mrbiggleswirth** [comment]
> 
> 
> How can resolve this? :/

The problem seems to originate from WSL 1 & 2, have to wait for the Microsoft team to fix this.
If you just want to make MySQL 8 run, then execute this command twice ignoring the first error you see in terminal!

```
(venv)$ sudo service mysql start
  * warning blah blah blah...
(venv)$ sudo service mysql start
  * Starting MySQL database server mysqld     [ OK ]
```

**Comment by krowe** [comment]
I've just confirmed that this is still an issue on a fresh install. In the time since mybiggleswirth answered this someone found a workaround (but it is less secure...something a WSL user probably isn't terribly concerned with, I'd image):

```
sudo service mysql stop
sudo usermod -d /var/lib/mysql/ mysql
sudo service mysql start
```

Source: https://serverfault.com/questions/755763/mysql-nonexistent-home-vs-no-directory-logging-in-with-home/942422
