### ISSUE TITLE
email send

### ISSUE THREAD

**Issue by ogahozy** [miguelgrinberg/microblog#257]
I am testing the forget password post of this microblog. when i try to send email for registered user to reset his password. i get this error

    File "/root/ogahslab/app/auth/routes.py", line 66, in reset_password_request
    send_password_reset_email(user)
  File "/root/ogahslab/app/auth/email.py", line 9, in send_password_reset_email
    sender=current_app.config['WEB_ADMIN'][0],
TypeError: 'NoneType' object is not subscriptable.
how to get about this error.
I am using fully autenticated email from twilio sendgrid.
below is my config.py as describe in sendgrid blog

   MAIL_SERVER = os.environ.get('MAIL_SERVER', 'smtp.sendgrid.net')
    MAIL_PORT = int(os.environ.get('MAIL_PORT', '587'))
    MAIL_USE_TLS = os.environ.get('MAIL_USE_TLS', 'true').lower() in ['true', 'on', '1']
    MAIL_USERNAME = os.environ.get('MAIL_USERNAME', 'apikey')
    MAIL_PASSWORD = os.environ.get('MAIL_PASSWORD')
    WEB_ADMIN = os.environ.get('WEB_ADMIN')

**Comment by miguelgrinberg** [comment]
Did you set a `WEB_ADMIN` environment variable?

**Comment by ogahozy** [comment]
Yes. I did export WEB_ADMIN="admin@ogahslab.com"

ogahozy

**Comment by miguelgrinberg** [comment]
Look at the error. It is saying that `current_app.config['WEB_ADMIN']` is `None`. I understand that you think you've set this variable correctly, but the error indicates that you are mistaken. You need to find why this variable is not defined in this process environment.

**Comment by ogahozy** [comment]
Ok. Thanks

ogahozy
