### ISSUE TITLE
How to integrate Microblog project with the React/Flask setup?

### ISSUE THREAD

**Issue by mrbiggleswirth** [miguelgrinberg/microblog#258]
Hi Miguel great React/Flask integration tutorials!

I managed to follow along Part 1 without problems. I also skimmed through Part 3 skipping the deployment sections since I'm not ready yet for any deployment procedures.

**Part 1:** https://blog.miguelgrinberg.com/post/how-to-create-a-react--flask-project
**Part 3:** https://blog.miguelgrinberg.com/post/how-to-deploy-a-react-router-flask-application

### Microblog
Next thing I wanted to do was to integrate your **microblog-0.6.zip** project with this React/Flask setup. But I'm not sure how to plan and think about the URL routing logics. Since Microblog project uses a bunch of its own URL routing logics and React handles a lot of routing logics itself. **Do I keep writing new Microblog pages the same way as the book has taught previously or do I need to make adjustments going forward when working with this React/Flask setup?**

.
### Example/Question 1
https://github.com/mrbiggleswirth/react-flask-microblog

```
# Terminal 1: Frontend
$ yarn start

    http://localhost:3000

# Terminal 2: Backend
$ yarn start-api

    http://localhost:5000
```
On the main page I see these 3 links:
- Home
- Page2
- Flask login

How do I make the Flask login link go to `localhost:5000/login` page?

.
### Example/Question 2
How do I make the React main page go directly to Microblog's `localhost:5000/index` pages?

**Comment by miguelgrinberg** [comment]
The microblog project as it is would not work well with a React frontend, I honestly don't see how you could make it work, because Flask-Login is not a proper auth model to use for a single-page application.

**Comment by mrbiggleswirth** [comment]
I think I understand what you mean. So when using a React frontend I basically let React handle all of the page template code, instead of letting Flask's Jinja template engine do it? And only use Flask for functions and procedures that doesn't exist in React?

**Comment by miguelgrinberg** [comment]
Yes, you would just use functions such as those shown in the API chapter.
