### ISSUE TITLE
Ch09 - form = EmptyForm() in guide but not in repository causes exception

### ISSUE THREAD

**Issue by GreyArea765** [miguelgrinberg/microblog#259]
I'm not really very experienced in Flask (hence reading the guide!) or Python, but this felt like a bug:

In the guide [https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-ix-pagination](url) at the section; **Pagination in the User Profile Page** the code block for;

```app/routes.py: Pagination in the user profile view function.```

Appears to erroneously contain the ```form = EmptyForm()``` statement.  This line is not in the code repository for the v0.9 tagged commit (89ae809e08e3742d941d7653a41f5f28cb378596)

Putting this line in the code (following the guide) makes it throw the following exception:
```
NameError: name 'EmptyForm' is not defined
```
**Steps to reproduce**

`git clone` the project
`git checkout v0.9`
Insert the `form = EmptyForm()` statement into line 104 of `routes.py` as per the guide.
Run the flask app
Click on the Profile link from the title bar
Exception (NameError: name 'EmptyForm' is not defined) is thrown.

p.s. I just realised that `,form=form)` should also not be present - it isn't in the repo but again, is in the guides code block for the same as above.

**Comment by miguelgrinberg** [comment]
The 0.9 tag points to a8800271547e5cd961817b3b4f347c9f863b0835, which does have `EmptyForm`. I think you are looking at an older version of this repository.
