### ISSUE TITLE
Database Models - from flask_migrate import Migrate

### ISSUE THREAD

**Issue by NZ26-06** [miguelgrinberg/microblog#261]
Hi all

I m followinf video Database Models
I have made everything typing correct, I believe
Still I got "ModuleNotFoundError: No module named 'flask_migrate'

On python 3 I cannot run commande from app.models import Models
and I have set just before calling python
set FLASK_APP=microblog.py

I have unistall flask_migrate and install it again using pip3, still same issue

In case someone already encountered this, I would appreciate some help

I

Thanks

**Comment by miguelgrinberg** [comment]
Did you create and activate the virtual environment as shown near the start of the tutorial?

**Comment by NZ26-06** [comment]
Yes I did

**Comment by miguelgrinberg** [comment]
Okay, then try recreating the virtualenv from scratch, something isn't right there.

**Comment by P26Puteaux** [comment]
Sorry for delay
You were right, it s working now. We can close the issue
