### ISSUE TITLE
ModuleNotFoundError: No module named 'app'

### ISSUE THREAD

**Issue by HarshitaMav** [miguelgrinberg/microblog#263]
Getting this error while checking for configuration in the following command:
"from microblog import app"

**Comment by miguelgrinberg** [comment]
Do you have an `app` sub directory in the directory from where you run the application? Is the current directory in the Python import path?

**Comment by HarshitaMav** [comment]
Yes it is in python path and also I don't have any other sub directory other than taught in the tutorial

**Comment by miguelgrinberg** [comment]
Okay, and how did you confirm that your directory is in the import path? I can't really think of any other possibilities, so something must be missing in your set up.

**Comment by HarshitaMav** [comment]
Can you tell me what might be missing I can try that way

**Comment by miguelgrinberg** [comment]
Sorry, let me ask the questions. Only then I can maybe guess what's missing. I asked if the current directory was in the Python import path and you said yes. How did you confirm this?

**Comment by HarshitaMav** [comment]
Thank you sir, problem solved.
My microblog.py was in app folder so it was not able to access app from inside app, Silly mistake!!!
Thank you once again.
