### ISSUE TITLE
MarkupSafe version in requirements file breaks with latest version of setuptools

### ISSUE THREAD

**Issue by jesusroncal94** [miguelgrinberg/microblog#264]
Hello, I am following the course and in order to test the final project, I had the following error when installing the requirements:

`from setuptools import setup, Extension, Feature`
`ImportError: cannot import name 'Feature' from 'setuptools'`

_**Doing a bit of research, I found the version 46.0.0 of setuptools removed _Feature_ which apparently was a long-deprecated class. This class is used by the MarkupSafe library, at least in version 1.0 specified in the requirements file. Also, it is known that in the version of the library MarkupSafe 1.1.1 it no longer requires this class.**_

**Ways to deal with the inconvenience:**

1. Specify a version of the setuptools library lower than 46.0.0 at the beginning of the requirements file. The closest version is 45.3.0.
2. Install the lower version of the library manually and then install the libraries from the requirements file.
`pip install setuptools==45.3.0`
`pip install -r requirements.txt`
5. This last way consists of updating the version specified in the MarkupSafe library requirements file from 1.0 to 1.1.1, because of it is no longer dependent on the class obtained from the setuptools library.

**If there is anything to correct or further explain, please let us know.**

I hope it will be of great help.

Greetings.

Source 1: https://github.com/pallets/markupsafe/issues/116
Source 2: https://bk.tencent.com/s-mart/community/question/909

**Comment by miguelgrinberg** [comment]
I have updated the requirements to use version 1.1.1. Thanks.
