### ISSUE TITLE
[Question] messages.po includes translations from further chapters, expected? 

### ISSUE THREAD

**Issue by thecircleoflifefree** [miguelgrinberg/microblog#265]
First, outstanding tutorial Miguel!

The question is intended more as a clarification. I noticed that the messages.po from CH13 GH repo contains translations from files that are yet to appear in future files from future chapters, such as search.html that appears in Chapter 16.

Is this intended this way to have it already set and going as to avoid revisiting the same topic in future chapters?

Best Regards

**Comment by miguelgrinberg** [comment]
No, this could be a mistake on my part. The contents of messages.po are generated from your source code, so new texts added after chapter 13 should be introduced only when you update the translations as you move through the chapters.

**Comment by thecircleoflifefree** [comment]
Great, pretty much the expected flow that has been throughout the chapters, piece-by-piece. Better to confirm than assume, in case there was a 'catch' I had missed =)

Best Regards
