### ISSUE TITLE
Part III: Web Forms - flask.ext.wtf

### ISSUE THREAD

**Issue by DirtGrubDylan** [miguelgrinberg/microblog#27]
Since flask.ext.wtf.Form is deprecated, maybe this chapter/tutorial should update to using `from flask_wtf import FlaskForm` instead.

**Comment by miguelgrinberg** [comment]
Agreed, I updated a bunch already but missed this one.

**Comment by miguelgrinberg** [comment]
This has now been fixed on this repo. I will also update the articles on my blog. Thanks!

**Comment by DirtGrubDylan** [comment]
No worries man. Thank you for the great tutorial!
