### ISSUE TITLE
Need advice - Different login grant access 

### ISSUE THREAD

**Issue by NZ26-06** [miguelgrinberg/microblog#270]
Hello,

I m willing to differentiate access to users to contents based on their profile.
I m going to use tokens, and loginrequired decorators.

BUT i wonder how can I generate set of tokens to create 2 different groups.

Thanks for your advice
Br
NZ26

**Comment by miguelgrinberg** [comment]
@NZ26-06 I don't understand what specifically you need advice on. If you have two types of users, then checking the user's information will tell you what content the user can access, so there is no need to use different types of tokens.

**Comment by NZ26-06** [comment]
Thanks Miguel, indeed differentiation has to be done through DB info
