### ISSUE TITLE
Login and Data breach warning on Chrome

### ISSUE THREAD

**Issue by NZ26-06** [miguelgrinberg/microblog#271]
Hi,

I have (I belive) just copied Login function from tutorial.
Now I have a Chrome warning on Loggin - see picture. 
Is there something missing on my code ?

class LoginForm(FlaskForm):
    username = StringField('Username')
    password = PasswordField('Password')
    next = HiddenField()

    def get_authenticated_user(self):
        user = User.query.get(self.username.data)
        if user is None:
            return None
        m = sha256()
        m.update(self.password.data.encode())
        passwd = m.hexdigest()
        return user if passwd == user.password else None

class User(db.Model, UserMixin):
    username = db.Column(db.String(50), primary_key=True)
    password = db.Column(db.String(64))
    company = db.Column(db.String(64))

    def get_id(self):
        return self.username

Thanks a lot

**Comment by NZ26-06** [comment]
![sent](https://user-images.githubusercontent.com/71227725/103202420-a7d56e00-48f2-11eb-9904-217c9e0073f4.jpg)

**Comment by miguelgrinberg** [comment]
The warning from Chrome has nothing to do with the application that you are building. Chrome is telling you that your password appears on password lists from hacked sites. Stop using that password and change it on any sites in which you are still using it. Also, do not reuse your passwords on multiple web sites.

**Comment by NZ26-06** [comment]
Thanks Miguel for guidance.
It s a test version, and so a test password
It s kind from Google to warn me, still I feel akwards that they extract my password (even ecrypted) without my consent...

Thanks a lot

**Comment by miguelgrinberg** [comment]
The password is not encrypted nor hashed when you type it into Chrome. The server creates a password hash and stores it in the database. This warning is all generated within the client-side.
