### ISSUE TITLE
8.10: jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'unfollow'

### ISSUE THREAD

**Issue by nicdan** [miguelgrinberg/microblog#272]
Hi Miguel,
Must be something easy I'm missing. For my second go through your excellent tutorial, I am adapting it to make an almost Instagram-like clone as a portofolio project. First time through was fine, but now this error.

Here is my user.html:

![user](https://user-images.githubusercontent.com/1263622/103244476-d9d3e800-4965-11eb-8c48-288fb77ec0b0.jpg)

Many thanks for your work!

**Comment by nicdan** [comment]
Maybe this is also useful:
![user2](https://user-images.githubusercontent.com/1263622/103244845-ed338300-4966-11eb-959f-e0e02e6a7671.jpg)

Thank you

**Comment by miguelgrinberg** [comment]
In the first form (to follow a user) the submit call has a  string argument that is missing the closing quote.

**Comment by nicdan** [comment]
Thank you!
