### ISSUE TITLE
Pb at jsonify in return from Class

### ISSUE THREAD

**Issue by NZ26-06** [miguelgrinberg/microblog#274]
Hi,

I have successfully (almost, I guess) manage to build a start of api.
Unfortunately when I wrap my function into a class I guess an error message. I cannot find explanation for that.

Works fine:

from flask import Flask, jsonify, request, url_for, abort
from flask import make_response
from tuto import app
from tuto.app import db
from tuto.api import bp
from tuto import models
from tuto.models import Entreprise, Offre, User, Candidate
from flask_restx import Resource, Api, fields

app = Flask(__name__)

message = {}

![b](https://user-images.githubusercontent.com/71227725/103422064-dc218680-4b9f-11eb-9ac6-6df8351dd9e4.jpg)

When I wrap it as a method of a class:, I have message:
The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a Candidates.

![a](https://user-images.githubusercontent.com/71227725/103422073-e3e12b00-4b9f-11eb-8afe-2eb7a21fe66a.jpg)
Thanks

**Comment by miguelgrinberg** [comment]
Well, it looks like you are using your own approach to building the API, not the approach described in my tutorial. So I really don't know, you must be doing something that is incorrect, but I don't really know what that is. Check the documentation of the package from where you imported the `Resource` class to see how they recommend you build your API.
