### ISSUE TITLE
Chap23 - Users.py modifications - PUT makes no change on database

### ISSUE THREAD

**Issue by NZ26-06** [miguelgrinberg/microblog#276]
Hi,

I m adapting code of chap23, on file similar to users.py.
I have GET/ POST working fine. but when I make a PUT for an update (def update_user(id):), 
function below return is the expected one. Just that database is not updated.

Also I had to create a second db = SQLAlchemy(app) in this file, as otherwise Flask claims is has db not defined. while being already present in parent folder for the graphic version of the app. Same happens if I add it in __init__.py of the api folder.

I would be gratefull if someone has some idea for this, already spent whole day in this... surely I have not correct understanding of something

**api folder**
**candidates.py, modifications of users.py**

from flask import Flask, jsonify, request, url_for, abort
from flask import make_response
from tuto.api.errors import bad_request
import os
from tuto.api import bp
from tuto import models
from tuto.models import Entreprise, Offre, User, Candidate

import os

app = Flask(__name__)

from flask_sqlalchemy import SQLAlchemy

def mkpath(p):
&nbsp;    return os.path.normpath(
 &nbsp;&nbsp;       os.path.join(os.path.dirname(__file__),
 &nbsp;&nbsp;           p))
db = SQLAlchemy(app)

@bp.route('/candidates', methods=['GET'])
def get_candidates():
&nbsp;    result = {}
&nbsp;    data_result= {}
&nbsp;    data = Candidate.query.limit(240).all()
&nbsp;    print(data)
&nbsp;    i = 1
&nbsp;    for x in data:
&nbsp;&nbsp;        data_result['username'] = x.username
&nbsp;&nbsp;        data_result['email'] = x.email
  &nbsp;&nbsp;      result[i]= data_result
 &nbsp;&nbsp;       data_result= {}
 &nbsp;&nbsp;       i = i + 1
&nbsp;    return jsonify(result)

@bp.route('/candidates/<int:id>', methods=['GET'])
def get_candidate(id):
&nbsp;    return jsonify(Candidate.query.get_or_404(id).to_dict())

**api folder:**
 **__init__.py**
from flask import Blueprint
bp = Blueprint('api', __name__)
from flask import Flask
from tuto.api import candidates, errors

**parent folder:**
**__init__.py**
from .app import app
import tuto.views
import tuto.commands
import tuto.models
from flask_sqlalchemy import SQLAlchemy

**parent folder:**
**app.py**
from flask import Flask
from flask_login import LoginManager

app = Flask(__name__)

login_manager = LoginManager(app)
login_manager.login_view = "login"

app.config['MAX_CONTENT_LENGTH'] = 2048 * 2048
app.config['UPLOAD_EXTENSIONS'] = ['.jpg', '.png', '.jpeg']
app.config['UPLOAD_PATH'] = 'tuto/static/images'

import os.path

from flask_bootstrap import Bootstrap
Bootstrap(app)
app.config['BOOTSTRAP_SERVE_LOCAL']=True

def mkpath(p):
&nbsp;     return os.path.normpath(
&nbsp; &nbsp;         os.path.join(os.path.dirname(__file__),
 &nbsp; &nbsp;            p))

from flask_sqlalchemy import SQLAlchemy
app.config['SQLALCHEMY_DATABASE_URI']= (
&nbsp;     'sqlite:///'+mkpath('../myapp.db'))
db = SQLAlchemy(app)

from tuto.api import bp as api_bp
app.register_blueprint(api_bp, url_prefix='/api')

models.py
class Candidate(db.Model, UserMixin):
&nbsp;    id = db.Column(db.Integer, primary_key=True)
 &nbsp;   username = db.Column(db.String(50))
&nbsp;    password = db.Column(db.String(64))
&nbsp;    email = db.Column(db.String(64))

&nbsp;    def set_password(self, password):
&nbsp;&nbsp;        self.password_hash = generate_password_hash(password)

&nbsp;    def check_password(self, password):
 &nbsp;&nbsp;       return check_password_hash(self.password_hash, password)

  &nbsp;  def to_dict(self, include_email=False):
 &nbsp;&nbsp;       data = {
   &nbsp;&nbsp;         'id': self.id,
   &nbsp;&nbsp;         'username': self.username,
   &nbsp;&nbsp;         'password': self.password,
  &nbsp;      }
    &nbsp;    if include_email:
    &nbsp;&nbsp;        data['email'] = self.email
    &nbsp;    return data

  &nbsp;  def from_dict(self, data, new_user=False):
  &nbsp; &nbsp;     for field in ['username', 'email', 'password']:
     &nbsp;&nbsp;&nbsp;       if field in data:
    &nbsp;&nbsp;&nbsp;&nbsp;            setattr(self, field, data[field])
   &nbsp;&nbsp;     if new_user and 'password' in data:
   &nbsp;&nbsp;&nbsp;         self.set_password(data['password'])

&nbsp;    def get_id(self):
&nbsp;&nbsp;        return self.username
![c](https://user-images.githubusercontent.com/71227725/103445975-a2717e00-4c7a-11eb-9741-2637c752b731.jpeg)

I belive duplicate of db can be issue, but it s only way I got the 3 other functions work GET/POST

Hope someone can help me
Thanks

**Comment by miguelgrinberg** [comment]
You can't define multiple databases. You have to use a single one, as shown in the tutorial.

**Comment by NZ26-06** [comment]
Yes, it was a workaround due to "db not define" messages.

Finally solved it, I just change your **"from app import db"** from users.py file to point to my app folder then to my app file.
So changed into from **tuto.app import db**
Too many app words there, I managed to find a rational in it :-)

Thanks for putting me back to origin of issue
