### ISSUE TITLE
v0.23 401 Error on ~/api/users GET REQUEST: {"error":"Unauthorized"}

### ISSUE THREAD

**Issue by Nick-Benz** [miguelgrinberg/microblog#277]
Miguel,

First of all, awesome tutorial. I've been referencing this tutorial for years as I use Flask for various small web app projects. The Video Lecture component is especially well done. 

When testing the API (GET REQUEST ~/api/users)  from my web browser I get a `{"error":"Unauthorized"}` 401 error. Performing this same request from the command line `http GET http://localhost:8000/api/users/1 Authorization:"Bearer $TOKEN"
` yields the following:

`HTTP/1.1 401 UNAUTHORIZED`
`Connection: close`
`Content-Length: 25`
`Content-Type: application/json`
`Date: Fri, 01 Jan 2021 21:46:10 GMT`
`Server: gunicorn/20.0.4`
`WWW-Authenticate: Bearer realm="Authentication Required"`
`{
    "error": "Unauthorized"
}`

I am running a fresh Ubuntu 20.04 Server with Python 3.8.5 on my private LAN. All packages and dependencies are current (addressing previous issues with werkzeug, SQLAlchemy, and Flask-Babel). The web app runs great from `git checkout v0.23` in everyway except API functionality.

I apologize for not having a more concise question to ask other than: how do I adjust my code so that the API works? From what I can research, it appears as though the token auth is not being handed-off correctly.

**Comment by miguelgrinberg** [comment]
The most obvious explanation is that the token that you are sending is incorrect or expired.

**Comment by Nick-Benz** [comment]
How would you recommend that I remedy this? Extend the token expiration time?

**Comment by miguelgrinberg** [comment]
I would recommend that you first find out if your token is incorrect or expired. Are you sure it is expired or are you guessing?

**Comment by Nick-Benz** [comment]
I do not know if the token is expired (and I do not know how to check if it has). I am simply guessing that the issue is related to the token.

**Comment by miguelgrinberg** [comment]
The API chapter covers how to generate tokens in detail. I suggest you review that chapter to learn how to generate a valid token.
