### ISSUE TITLE
Why the gunicorn use a module name runp-heroku?

### ISSUE THREAD

**Issue by cielpy** [miguelgrinberg/microblog#28]
It seem like there does not exist a module named runp-heroku

**Comment by miguelgrinberg** [comment]
That is an oversight. The correct command is in the blog article, it should read `app:app` instead of `runp-heroku:app`. I'll fix it.

**Comment by cielpy** [comment]
😂 Thanks

**Comment by miguelgrinberg** [comment]
Closing this issue, as it does not apply anymore.
