### ISSUE TITLE
Getting this to run

### ISSUE THREAD

**Issue by adrianblakey** [miguelgrinberg/microblog#280]
What's the process once this has been git cloned to get this to run?

I followed the tutorial to a point where I wanted to run the complete solution. I fired it up in PyCharm with a venv 3.9 on MacOs.

Whether or not I install the latest modules the traceback on run is:

/Users/ajb/microblog/venv/bin/python /Users/ajb/microblog/app/__init__.py
Traceback (most recent call last):
  File "/Users/ajb/microblog/venv/lib/python3.9/site-packages/werkzeug/http.py", line 23, in <module>
    from email.utils import parsedate_tz
  File "/Users/ajb/microblog/app/email.py", line 2, in <module>
    from flask import current_app
ImportError: cannot import name 'current_app' from partially initialized module 'flask' (most likely due to a circular import) (/Users/ajb/microblog/venv/lib/python3.9/site-packages/flask/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ajb/microblog/app/__init__.py", line 4, in <module>
    from flask import Flask, request, current_app
  File "/Users/ajb/microblog/venv/lib/python3.9/site-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/Users/ajb/microblog/venv/lib/python3.9/site-packages/werkzeug/__init__.py", line 151, in <module>
    __import__('werkzeug.exceptions')
  File "/Users/ajb/microblog/venv/lib/python3.9/site-packages/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/Users/ajb/microblog/venv/lib/python3.9/site-packages/werkzeug/wrappers.py", line 27, in <module>
    from werkzeug.http import HTTP_STATUS_CODES, \
  File "/Users/ajb/microblog/venv/lib/python3.9/site-packages/werkzeug/http.py", line 25, in <module>
    from email.Utils import parsedate_tz
  File "/Users/ajb/microblog/app/email.py", line 2, in <module>
    from flask import current_app
ImportError: cannot import name 'current_app' from partially initialized module 'flask' (most likely due to a circular import) (/Users/ajb/microblog/venv/lib/python3.9/site-packages/flask/__init__.py)

Process finished with exit code 1

**Comment by adrianblakey** [comment]
Step 1. Update all the packages ot the newest versions.
Step 2. Add email-validator==1.1.2 to requirements.txt and install it.
Step 3. flask db upgrade
...?

**Comment by miguelgrinberg** [comment]
Have you tried not upgrading all packages to their latest? The whole point of having a requirements file is to include the list of tested dependencies. In fact you've already found the one requiring the email_validator package to be installed. There might be others.

**Comment by adrianblakey** [comment]
Yes - I left requirements.txt alone to begin with - that's the first post. The first thing I did was add email_validator. I am running Python 3.9 - I wonder if that might be an issue. For grins I ran the docker build/run (Py 3.6) - which executes successfully but is not listening on 5000 ...

**Comment by adrianblakey** [comment]
Yes - I left requirements.txt alone to begin with - that's the first post. The first thing I did was add email_validator. I am running Python 3.9 - I wonder if that might be an issue. For grins I ran the docker build/run (Py 3.6) - which executes successfully but is not listening on 5000 ...

**Comment by miguelgrinberg** [comment]
I don't see any problems while running on 3.9. I have now updated the requirements file, I did not get any errors with the old or the upgraded dependencies.
