### ISSUE TITLE
{'csrf_token': ['The CSRF token is missing.']} when running on Azure

### ISSUE THREAD

**Issue by Tvonaxt** [miguelgrinberg/microblog#285]
Hello there,

I tried running this code on Azure (after some adaptations) but the login features are not working. The forms are constantly returning {'csrf_token': ['The CSRF token is missing.']}. The templates are unchanged from the example. 
I also created a [question](https://stackoverflow.com/questions/66447992/flask-login-not-working-after-migrating-to-azure) on stackoverflow about this with more details when I was still using your example of the flask megatutorial.
Do you know what might be causing this?
It worked fine on cloudfoundry but suddenly stopped working after a while in Azure.

ps: when I try to register a user, it says that the csrf token is invalid instead of missing, and when I try to print the token, it comes out fine, meaning the token is there but the system is not consuming it.

**Comment by miguelgrinberg** [comment]
There's nothing specific to Azure than can cause this. The only reasonable explanation is that something that you've done while setting up this application is constantly invalidating the user session. The CSRF token is stored there, so when the session is invalidated it also causes the CSRF token to be regenerated.

**Comment by Tvonaxt** [comment]
Thanks for the answer @miguelgrinberg.
Do you have any clue of what would cause my session to be invalidated?
I posted some of my code in the stackoverflow link, but I can post my __init__py here again:

`from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_script import Manager
from flask_migrate import Migrate, MigrateCommand
import os
from flask_login import LoginManager
from itsdangerous import URLSafeTimedSerializer

app = Flask(__name__)
app.config['MAIL_SERVER'] = os.getenv('MAIL_SERVER')
app.config['MAIL_PORT'] = os.getenv('MAIL_PORT')
app.config['MAIL_USERNAME'] = os.getenv('MAIL_USER')
app.config['MAIL_PASSWORD'] = os.getenv('MAIL_PASSWORD')
app.config['MAIL_USE_TLS'] = False
app.config['MAIL_USE_SSL'] = True
app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('MYSQL_URI')
app.config['SECRET_KEY'] = os.urandom(32)
app.config['SERVER_NAME'] = os.getenv('SERVER_NAME')
db = SQLAlchemy(app)
db.init_app(app)
migrate.init_app(app, db)
manager = Manager(app)
migrate = Migrate(app, db)
manager.add_command('db', MigrateCommand)
login = LoginManager()
login.init_app(app)
login.session_protection = "strong"
login_serializer = URLSafeTimedSerializer(app.secret_key)

from app import views, models

if __name__ == '__main__':
    app.run(debug=True)`

**Comment by miguelgrinberg** [comment]
This would cause all user sessions to be invalidated when you restart the application:

    app.config['SECRET_KEY'] = os.urandom(32)

**Comment by Tvonaxt** [comment]
Thank you very much @miguelgrinberg.
I will test this and let you know.

**Comment by Tvonaxt** [comment]
It seems it worked for the missing token problem.
In firefox it is working fine now. 
In Chrome Im receiving {'csrf_token': ['The CSRF tokens do not match.']}.
I tried clearing cookies, but it is still returning it.
Regardless, Im so happy it is working again, I was until midnight trying to solve this.
Thank you very much @miguelgrinberg. I a huge fan of your guides. Your work is amazing!
