### ISSUE TITLE
jwt - AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by samsimsom** [miguelgrinberg/microblog#286]
I got an error.
microblog / app / models.py
Line : 154

return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'

**Comment by miguelgrinberg** [comment]
The version of pyjwt that you are using is new. They have introduced a breaking change lately. The decode call is not necessary anymore as pyjwt now returns the token as a string.

**Comment by miguelgrinberg** [comment]
The tutorial has been updated to fix this issue.
