### ISSUE TITLE
novalidate Boolean missing on the page 26, first line, in the book 

### ISSUE THREAD

**Issue by SzabolcsMolnar82** [miguelgrinberg/microblog#287]
#<form action="" method="post" _**novalidate**_>
{{ form.hidden_tag() }}
<p>
{{ form.username.label }}<br>
{{ form.username(size=32) }}<br>
{% for error in form.username.errors %}
<span style="color: red;">[{{ error }}]</span>
{% endfor %}
</p>

**Comment by miguelgrinberg** [comment]
What edition of the book are you reading? Is it the digital version or print? When did you buy it? Because the `novalidate` was not in the original tutorial, this was a fix that had to be made due to a change in Flask-WTF and WTForms.

**Comment by SzabolcsMolnar82** [comment]
The book say :December 5 2017.  Its a digital format.  Finally my problem is solved, so excuse me for the unnecessary interruption!

**Comment by miguelgrinberg** [comment]
Yes, so you have a version of the tutorial that predates this problem. I keep the tutorial on the blog updated, so in the future you may want to give the corresponding blog article a quick review to see if anything has been updated.

**Comment by SzabolcsMolnar82** [comment]
Yes, I  will do it surely and thank you for the quick response! Funny but with poroblems like this I can learn the code more,  after 4-5 hours of looking for the solution,  all the code and its methods in my head  :)  have a good day!
