### ISSUE TITLE
How to contribute ?

### ISSUE THREAD

**Issue by JulianHysi** [miguelgrinberg/microblog#290]
Hi Miguel,

I want to contribute but I'm not seeing any file with the instructions on how to do so.
More specifically, on what branch/tag are you expecting new commits ?

**Comment by miguelgrinberg** [comment]
This repository is carefully constructed to match the written and video tutorials, so I cannot accept contributions using the standard GitHub workflow. If you have anything to suggest you can write an issue, and if it is something that I consider beneficial for the tutorial I will modify the tutorial and the code at the same time.

**Comment by JulianHysi** [comment]
Alright, I'll open new issues (with specific suggestions) when I can. Thanks.
