### ISSUE TITLE
Verify if elastic server is running

### ISSUE THREAD

**Issue by JulianHysi** [miguelgrinberg/microblog#291]
Hi Miguel,

I have a suggestion: in the application factory, check not only for the elastic env variable, but also if the elastic server is actually running. 

The code extract from my own project: 

`    if app.config['ELASTICSEARCH_URL']:
        es = Elasticsearch([app.config['ELASTICSEARCH_URL']])
        app.elasticsearch = es if es.ping() else None
    else:
        app.elasticsearch = None
`

**Comment by JulianHysi** [comment]
Looks like Github didn't preserve the code indentation, so here's a picture of it:

![image](https://user-images.githubusercontent.com/25062599/112466077-b8687980-8d65-11eb-8e0e-8afaae8c4c21.png)

**Comment by miguelgrinberg** [comment]
This is fine, but if the application is configured to use elasticsearch I think it is better that errors are generated, which will alert you that you have an issue with elasticsearch, instead of silently disabling all the search functionality.

**Comment by JulianHysi** [comment]
I see your point. 
In my case I have modified also the search() route function, where I do an `abort(500)` if elasticsearch attribute is set to None.
This way it is clear that something went wrong, and no low level detail is exposed.
