### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'None' has no attribute 'avatar'

### ISSUE THREAD

**Issue by nikkodc** [miguelgrinberg/microblog#296]
Suddenly the error jinja2.exceptions.UndefinedError: 'None' has no attribute 'avatar' shows in my explorer tab. And my search is not working. I'm currently in Chapter 16: Full-Text Search

**Comment by miguelgrinberg** [comment]
You have one or more blog posts in your database that have no author set.

**Comment by nikkodc** [comment]
Is there a way to check the author in each post? I tried to loop to my database in db Post and I can't check the author.

**Comment by miguelgrinberg** [comment]
```python
for post in Post.query:
    if post.author is None:
        print(f'blog post {post.id} has no author')
```

**Comment by nikkodc** [comment]
Thank you so much. I have able to find and delete the post with no author.
