### ISSUE TITLE
Cannot import app from app (Unknown Location)

### ISSUE THREAD

**Issue by AchalS-iglushrek** [miguelgrinberg/microblog#297]
Terminal Dump - 
``` * Serving Flask app 'microblog.py' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'microblog', an ImportError was raised:

Traceback (most recent call last):
  File "/home/iglu/repos/personal/Flask Mega Tutorial/microblog/venv/lib/python3.9/site-packages/flask/cli.py", line 256, in locate_app
    __import__(module_name)
  File "/home/iglu/repos/personal/Flask Mega Tutorial/microblog/microblog.py", line 1, in <module>
    from app import app
ImportError: cannot import name 'app' from 'app' (unknown location)
```

File Structure-
![image](https://user-images.githubusercontent.com/45008879/127244092-7b76cb26-ecae-4a8c-a19d-60f6243f2a9c.png)

__init__.py
```
from flask import Flask

app = Flask(__name__)

from app import routes
```

routes.py
```
from app import app

@app.route('/')
@app.route('/index')
def index():
    return "Hello, World!"
```
    
microblog.py
```
from app import app
```

The python variable is indeed set to the venv one
![image](https://user-images.githubusercontent.com/45008879/127244192-aa054537-d60c-42bf-985b-362c516c3d04.png)

Python 3.9.5
Flask 2.0.1
Werkzeug 2.0.1

Any help would be great! I have tried my best to follow the guide precisely.

**Comment by miguelgrinberg** [comment]
@AchalS-iglushrek Are you trying this from an IDE? Try it from the command line as shown in the tutorial. My guess is that your IDE is not setting the current directory correctly.

**Comment by AchalS-iglushrek** [comment]
> @AchalS-iglushrek Are you trying this from an IDE? Try it from the command line as shown in the tutorial. My guess is that your IDE is not setting the current directory correctly.

Thanks for the quick reply, but, already did, same result by running from terminal.

**Comment by miguelgrinberg** [comment]
@AchalS-iglushrek It's really difficult for me to help, because I don't have any information about what you are doing, and your descriptions are just vague verbal descriptions or partial dumps of the terminal instead of actually showing me what you are typing and what the complete response is.

**Comment by AchalS-iglushrek** [comment]
Uhh I see
```
iglu@pop-os:~/repos/personal/Flask Mega Tutorial/microblog$ source "/home/iglu/repos/personal/Flask Mega Tutorial/microblog/venv/bin/activate"
(venv) iglu@pop-os:~/repos/personal/Flask Mega Tutorial/microblog$ export FLASK_APP=microblog.py
(venv) iglu@pop-os:~/repos/personal/Flask Mega Tutorial/microblog$ flask run
 * Serving Flask app 'microblog.py' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'microblog', an ImportError was raised:

Traceback (most recent call last):
  File "/home/iglu/repos/personal/Flask Mega Tutorial/microblog/venv/lib/python3.9/site-packages/flask/cli.py", line 256, in locate_app
    __import__(module_name)
  File "/home/iglu/repos/personal/Flask Mega Tutorial/microblog/microblog.py", line 1, in <module>
    from app import app
ImportError: cannot import name 'app' from 'app' (unknown location)

(venv) iglu@pop-os:~/repos/personal/Flask Mega Tutorial/microblog$ 

```

So, I just followed the first part of the mega tutorial, the Hello World one and got stuck at the part where we run flask for the first time. All I have done is copied your code as shown in the tutorial while replicating the file structure and then tried to run it as shown. This specific time I just set to venv, ran the export command to set the flask app to microblog.py and then ran `flask run`.
(This one was run in terminal not IDE)

**Comment by AchalS-iglushrek** [comment]
Also I have it set up on github too
https://github.com/AchalS-iglushrek/microblog

**Comment by miguelgrinberg** [comment]
@AchalS-iglushrek Your `__init__.py` file inside the `app` directory has a space before the first underscore.

**Comment by AchalS-iglushrek** [comment]
> @AchalS-iglushrek Your `__init__.py` file inside the `app` directory has a space before the first underscore.

bruhhh, thanks! Dumb mistake, sorry for wasting your time.
