### ISSUE TITLE
app package and Flask instance have the same name

### ISSUE THREAD

**Issue by farisachugthai** [miguelgrinberg/microblog#299]
First and foremost thank you so much for this project! It's incredibly helpful.

I'm also going to note that this is directly mentioned and explained in the mega tutorial. 

But would it be prohibitively difficult to change either the package name or the Flask instance name so that they're not the same?

When I was new to python the import system was one of the most confusing things to me.

It's relatively easy to figure out what:

`from app import routes`

`app.config['SECRET_KEY'] = X`

are doing and for people that are familiar with python you know that one refers to a package and another to an instance.

But I genuinely think it would hugely clarify things to do something simple like renaming the package application. These are variables used on the first page and it'd be a shame to get people confused/frustrated immediately.

Yes the package is referred to A LOT in the tutorial, but I'd be happy to help since I think it would help alleviate potential confusion that would arise on literally the first article.

If this doesn't seem useful or feasible let me know but I'm happy to help here!

Thank you again for your phenomenal work.

**Comment by miguelgrinberg** [comment]
This tutorial came out in 2012. It's been 9+ years that it has been available in this form. I recognize that some people find the double use of the `app` identifier confusing, and this is explained in the first part of the tutorial. I will not be making structure changes to the tutorial at this point, but the code is released under a MIT license, so you are free to fork it and adapt it to your liking if you want to show people how it would look like under an alternative structure.
