### ISSUE TITLE
There is no user register function.

### ISSUE THREAD

**Issue by JulyUp** [miguelgrinberg/microblog#30]
Hello, I follow your tutorials and repositories, and find that there no user register function though your repositories have user login-in function. Could you show a example include user register function. It will be very necessary for newbie as me.
Thankyou very much!

**Comment by miguelgrinberg** [comment]
The code that accompanies my O'Reilly book does show how to register users. Have you looked at that project?

**Comment by JulyUp** [comment]
@miguelgrinberg  your O'Reilly book is very amazing. But  it seems to do not receive an email with a confirmation link when I  heck my inbox. What causes it?

**Comment by miguelgrinberg** [comment]
@JulyUp have you tested sending emails? There are a lot of things that can be wrong. If the email server returns an error it is going to be visible on your log when you run in debug mode.

**Comment by JulyUp** [comment]
@miguelgrinberg  First I run 'manage.py runserver'. When registering it shows error
`127.0.0.1 - - [04/Jan/2017 10:41:04] "GET /auth/confirm HTTP/1.1" 302 -
127.0.0.1 - - [04/Jan/2017 10:41:04] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [04/Jan/2017 10:41:05] "GET /auth/unconfirmed HTTP/1.1" 200 -
send: 'ehlo [127.0.1.1]\r\n'
reply: '250-smtp.googlemail.com at your service, [2001:cc0:2016:f178:acb5:3800:747b:3643]\r\n'
reply: '250-SIZE 35882577\r\n'
reply: '250-8BITMIME\r\n'
reply: '250-STARTTLS\r\n'
reply: '250-ENHANCEDSTATUSCODES\r\n'
reply: '250-PIPELINING\r\n'
reply: '250-CHUNKING\r\n'
reply: '250 SMTPUTF8\r\n'
reply: retcode (250); Msg: smtp.googlemail.com at your service, [2001:cc0:2016:f178:acb5:3800:747b:3643]
SIZE 35882577
8BITMIME
STARTTLS
ENHANCEDSTATUSCODES
PIPELINING
CHUNKING
SMTPUTF8
send: 'STARTTLS\r\n'
reply: '220 2.0.0 Ready to start TLS\r\n'
reply: retcode (220); Msg: 2.0.0 Ready to start TLS
send: 'ehlo [127.0.1.1]\r\n'
reply: '250-smtp.googlemail.com at your service, [2001:cc0:2016:f178:acb5:3800:747b:3643]\r\n'
reply: '250-SIZE 35882577\r\n'
reply: '250-8BITMIME\r\n'
reply: '250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH\r\n'
reply: '250-ENHANCEDSTATUSCODES\r\n'
reply: '250-PIPELINING\r\n'
reply: '250-CHUNKING\r\n'
reply: '250 SMTPUTF8\r\n'
reply: retcode (250); Msg: smtp.googlemail.com at your service, [2001:cc0:2016:f178:acb5:3800:747b:3643]
SIZE 35882577
8BITMIME
AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
ENHANCEDSTATUSCODES
PIPELINING
CHUNKING
SMTPUTF8
send: 'mail FROM:<flasky@example.com> size=1767\r\n'
reply: '530-5.5.1 Authentication Required. Learn more at\r\n'
reply: '530 5.5.1  https://support.google.com/mail/?p=WantAuthError y15sm144118820pgc.43 - gsmtp\r\n'
reply: retcode (530); Msg: 5.5.1 Authentication Required. Learn more at
5.5.1  https://support.google.com/mail/?p=WantAuthError y15sm144118820pgc.43 - gsmtp
send: 'rset\r\n'
reply: '250 2.1.5 Flushed y15sm144118820pgc.43 - gsmtp\r\n'
reply: retcode (250); Msg: 2.1.5 Flushed y15sm144118820pgc.43 - gsmtp
send: 'quit\r\n'
reply: '221 2.0.0 closing connection y15sm144118820pgc.43 - gsmtp\r\n'
reply: retcode (221); Msg: 2.0.0 closing connection y15sm144118820pgc.43 - gsmtp
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/congleng/work/flask-web/flasky-master/app/email.py", line 9, in send_async_email
    mail.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/flask_mail.py", line 416, in send
    message.send(connection)
  File "/usr/local/lib/python2.7/dist-packages/flask_mail.py", line 351, in send
    connection.send(self)
  File "/usr/local/lib/python2.7/dist-packages/flask_mail.py", line 168, in send
    message.as_string())
  File "/usr/lib/python2.7/smtplib.py", line 731, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
SMTPSenderRefused: (530, '5.5.1 Authentication Required. Learn more at\n5.5.1  https://support.google.com/mail/?p=WantAuthError y15sm144118820pgc.43 - gsmtp', 'Flasky Admin <flasky@example.com>')
`
Why it is refused? How to solve it? Thank youvert much.

**Comment by miguelgrinberg** [comment]
And did you see the error message that gmail is giving you?

> SMTPSenderRefused(code, resp, from_addr) SMTPSenderRefused: (530, '5.5.1 Authentication Required. Learn more at\n5.5.1 https://support.google.com/mail/?p=WantAuthError y15sm144118820pgc.43 - gsmtp

**Comment by JulyUp** [comment]
@miguelgrinberg Yes I read it. And I find a same issue [https://github.com/miguelgrinberg/flasky/issues/167](url). Do I have to modify the varibles for class 'Config' in config.py?

**Comment by JulyUp** [comment]
@miguelgrinberg  sir，i have solved this problem. Thank you very much!
