### ISSUE TITLE
 ImportError: cannot import name 'app' from 'flask_login' 

### ISSUE THREAD

**Issue by Sukumaran007** [miguelgrinberg/microblog#300]
**i referd miguel flask mega tutorial, but i have struggle with an import error issue please help to how to solving this error**

**microblog.py**
```
from app import app,db

from app.models import User, Post

from app import flask_login



@app.shell_context_processor
def make_shell_context():
    return {'db': db, 'User': User, 'Post': Post}
```

**__init__.py**
```
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_login import app
#from app.routes import flask_login
from flask_login import microblog

##login function recuring

#login = LoginManager(app)
login.login_view = 'login'
app = Flask(__name__)
login = LoginManager(app)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
from app import routes,models

```
**error**

> C:\Users\WELCOME\PycharmProjects\microblog>flask shell
> Usage: flask shell [OPTIONS]
> 
> Error: While importing "app", an ImportError was raised:
> 
> Traceback (most recent call last):
>   File "c:\users\welcome\appdata\local\programs\python\python39\lib\site-packages\flask\cli.py", line 240, in locate_app
>     __import__(module_name)
>   File "C:\Users\WELCOME\PycharmProjects\microblog\app\__init__.py", line 6, in <module>
>     from flask_login import app
> ImportError: cannot import name 'app' from 'flask_login' (c:\users\welcome\appdata\local\programs\python\python39\lib\site-packages\flask_login\__init__.py)
>

**Comment by miguelgrinberg** [comment]
This line in microblog.py is wrong:

    from app import flask_login

Why did you put it there? What is it for?

**Comment by Sukumaran007** [comment]
@miguelgrinberg ok i remove it, but again the same error was arrived.

**Comment by miguelgrinberg** [comment]
Are you reviewing the errors that you get? You aren't really using the code as shown in the tutorial. If you decide to deviate from the tutorial then you must check the code that you write and make sure it is correct.

**Comment by Sukumaran007** [comment]
@miguelgrinberg   your tutorial very useful for me

**Comment by miguelgrinberg** [comment]
I'm going to close this issue. If you have a question, please open a discussion, not an issue. Thanks.
