### ISSUE TITLE
Suggestion for Deploying Application Updates section

### ISSUE THREAD

**Issue by SSteve** [miguelgrinberg/microblog#306]
I successfully deployed microblog on my Raspberry Pi in chapter 17. It worked on the first try. Thanks for the great instructions.

After I finished chapter 23 I followed the instructions in the Deploying Application Updates section. At `flask db upgrade` I encountered an error because all the dependencies weren't installed. It was easy enough to fix, but you might want to add `pip install -r requirements.txt` in the instructions before `flask db upgrade`.

**Comment by miguelgrinberg** [comment]
Closing as this does not apply to the new edition of this tutorial.
