### ISSUE TITLE
Automatically register a default user (admin)

### ISSUE THREAD

**Issue by lambda-science** [miguelgrinberg/microblog#309]
Hello,

I am using your work as a template for my own project. I'm building an application that doesn't have a register page, instead I simply want to register a default admin user when the app is created.
However I run into issues with Flask Migrate and I wondered if you had any idea how I could fix it.

### Objective
When the app in launched: create an entry in the User table if the table is empty, with infos from envrionnement variables.

### What I Did
In `app/models.py` I added this to the User class:
```python
class User(UserMixin, db.Model):
    """Database table for Users"""

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, nullable=False)
    email = db.Column(db.String(120), index=True, unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)
   
[...]

   # ADDED
    @staticmethod
    def create_admin_account():
        # Create default admin account if user table is empty
        user_entry = User.query.get(1)
        if not user_entry:
            user = User(username="admin", email=current_app.config["DEFAULT_ADMIN_EMAIL"])
            user.set_password(current_app.config["DEFAULT_ADMIN_PASSWORD"])
            db.session.add(user)
            db.session.commit()
```
In `microblog.py` I added this:
```python
from app import create_app, db
from app.models import User

# Create instance of app
app = create_app()
# ADDED
with app.app_context():
    User.create_admin_account()

if __name__ == "__main__":
    app.run(use_debugger=False, use_reloader=False, passthrough_errors=True)
```

### Issue
Now when I run `flask db upgrade` in run into the issue `sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user`
I guess this come from the fact that flask migrate run `microblog.py` and triggers `create_admin_account()` before the app.db with proper tables is created.
Do you have any idea on how to make it so this doesn't trigger during migration or only after migration ?
I should probably call this function elsewhere !

Thanks a lot for your great tutorial and time !

EDIT:
Full traceback if need attached :)
[error.log](https://github.com/miguelgrinberg/microblog/files/7447124/error.log)

**Comment by miguelgrinberg** [comment]
You can move the admin account creation logic right before the app.run call, inside the if statement.

**Comment by lambda-science** [comment]
> 
> 
> You can move the admin account creation logic right before the app.run call, inside the if statement.

Well, that was easy !
Side question, now when I do `python microblog.py` it works, launch flask and create the user, and flask migrate works.
However when running it with `flask run` or `gunicorn -b :5000 --preload microblog:app` 
the `if __name__ == "__main__":` doesn't trigger.
Is that expected ?

**Comment by lambda-science** [comment]
> 
> 
> > You can move the admin account creation logic right before the app.run call, inside the if statement.
> 
> Well, that was easy ! Side question, now when I do `python microblog.py` it works, launch flask and create the user, and flask migrate works. However when running it with `flask run` or `gunicorn -b :5000 --preload microblog:app` the `if __name__ == "__main__":` doesn't trigger. Is that expected ? If yes, how could I make the admin account creation logic to trigger when launching the app using flask run or gunicorn.

I guess one solution would be to simply change it as
```python
if __name__ == "__main__":
    with app.app_context():
        User.create_admin_account()
    # app.run(use_debugger=False, use_reloader=False, passthrough_errors=True)
```
and to run once `microblog.py` during deployment process and `flask run` and `gunicorn microblog:app` still works ! :)

**Comment by miguelgrinberg** [comment]
You have several options:

- Move the admin account creation to a CLI command that you run separately from the web server
- Add the account creation logic to a database migration
- Put the account creation logic in a `before_first_request` handler
- Leave the account creation as you had it originally, but add a try/catch construct to catch the error and ignore it.

**Comment by lambda-science** [comment]
> 
> 
> You have several options:
> 
>     * Move the admin account creation to a CLI command that you run separately from the web server
> 
>     * Add the account creation logic to a database migration
> 
>     * Put the account creation logic in a `before_first_request` handler
> 
>     * Leave the account creation as you had it originally, but add a try/catch construct to catch the error and ignore it.

Thanks you very much for these multiple options !
I can now close this, have a nice week-end !
