### ISSUE TITLE
bootstrap base.html dose not align

### ISSUE THREAD

**Issue by zhangruiskyline** [miguelgrinberg/microblog#31]
in base.html, 

<a class="brand" </a>
In safari and firefox, this will make microblog index and other nav links  not aligned horizontally. 

changed to
<a class="navbar-brand" </a>

will solve it

**Comment by miguelgrinberg** [comment]
Are you using the same version of bootstrap? This project was created a few years ago, using Bootstrap 2. If you are going to upgrade to a newer version of Bootstrap, the markup will definitely need to change.

**Comment by zhangruiskyline** [comment]
I am using same css and js files from your repo, the original html works in chrome, but not in safari and firefox, after that change it will work on safari and firefox also

**Comment by miguelgrinberg** [comment]
Hmm. Weird, because the docs show that `brand` is correct. http://getbootstrap.com/2.3.2/components.html#navbar

**Comment by zhangruiskyline** [comment]
takes time to figure out this tricky issue:)

**Comment by miguelgrinberg** [comment]
Closing this issue, as it does not apply anymore.
