### ISSUE TITLE
flask-limiter

### ISSUE THREAD

**Issue by ikamran** [miguelgrinberg/microblog#311]
Hi guys, 

I wonder how we can implement flask-limiter into this structure, i mean blueprint and create_app
I couldn't figure out how to solve it

it limit all urls of a blueprint, how if i just want to use it on for example 

@bp.route('/users', methods=['POST'])
def create_user():

register user?

**Comment by miguelgrinberg** [comment]
I'm sorry but I don't understand what the problem is. I don't use Flask-Limiter, so if you have a specific problem with the extension you need to ask in a support form for it. If the problem is in my project, then please let me know what the exact problem is.
