### ISSUE TITLE
Part XVI: Full-Text Search / Constant Redirects

### ISSUE THREAD

**Issue by nuonce** [miguelgrinberg/microblog#314]
I am enjoying your tutorial, thank you.  I just wanted to reference this Issue #219 

I am using your files from the Git Repo, and I ran into the same issue #219.  I found this via Google Fu.
[https://stackoverflow.com/questions/61237524/validating-get-params-with-wtforms-in-flask](https://stackoverflow.com/questions/61237524/validating-get-params-with-wtforms-in-flask)

Lead me to update:

app/main/forms.py
YOURS:
```
        if 'csrf_enabled' not in kwargs:  
           kwargs['csrf_enabled'] = False
```

I added:
```
       if 'meta' not in kwargs:  
            kwargs['meta'] = {'csrf': False}
```

By doing so allowed "g.search_form.validate" (app/main/routes.py) to return True when I put data into the 'q' field.  Until I had that, I would always be redirected.

```
192.168.1.188 - - [22/Jan/2022 16:57:15] "GET /search?q=crap HTTP/1.1" 302 -
192.168.1.188 - - [22/Jan/2022 16:57:15] "GET /explore HTTP/1.1" 200 -
```

**Comment by miguelgrinberg** [comment]
While the end result is the same, #219 was user error. Your case is different, I'm guessing you are using release 1.0 of Flask-WTF, which was released a couple of months ago, and removed the `csrf_enabled` option. Earlier versions supported both `csrf_enabled` and `meta` for this, now it's only `meta`. I'll update the tutorial, thanks.

**Comment by miguelgrinberg** [comment]
Fixed: https://github.com/miguelgrinberg/microblog/blob/main/app/main/forms.py#L41-L42
