### ISSUE TITLE
[Starting from Chapter 8] Unit tests fail with "Working outside of application context" RuntimeError

### ISSUE THREAD

**Issue by tsunamistate** [miguelgrinberg/microblog#327]
OS: Windows 11 22H2
Python: v3.11.0
Flask: v2.2.2

Running unit tests in `tests.py` provided in [Chapter 8](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-viii-followers) will fail with the following error:
```
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
```
Full log: 
[tests_log.txt](https://github.com/miguelgrinberg/microblog/files/9937519/tests_log.txt)

The solution is to precede test code that uses `app` and `db` objects with the `with app.app_context():` block, for example:
```patch
 class UserModelCase(unittest.TestCase):
     def setUp(self):
-        app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite://"
-        db.create_all()
+        with app.app_context():
+            app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite://"
+            db.create_all()
 
     def tearDown(self):
-        db.session.remove()
-        db.drop_all()
+        with app.app_context():
+            db.session.remove()
+            db.drop_all()
```

**Comment by miguelgrinberg** [comment]
Ah yes, this is due to a background incompatible change introduced in the latest release of Flask-SQLAlchemy. I will update the code and the tutorial to reflect this. Thanks.

**Comment by tsunamistate** [comment]
Also, I have noticed, running tests drops existing tables in existing `app.db` database, and `flask db upgrade` doesn't restore them
You have to delete `app.db` and rerun `flask db upgrade` to create a new **empty** database

No idea how to work around that, maybe don't `db.drop_all()` on `tearDown`?

**Comment by miguelgrinberg** [comment]
The code in this repository and chapter 8 of the tutorial have been updated to work with Flask-SQLAlchemy 3.x.

**Comment by tsunamistate** [comment]
Thank you, the tests now execute and pass, but they will still drop existing tables in database after execution

**Comment by miguelgrinberg** [comment]
I have addressed the problem with the tables as well.

**Comment by tsunamistate** [comment]
Fix confirmed!
Thank you for maintaining this project! It's a really good resource
