### ISSUE TITLE
Heroku will no longer provide Postgres DB for free since November 28th, 2022

### ISSUE THREAD

**Issue by tsunamistate** [miguelgrinberg/microblog#328]
> **Starting November 28th, 2022, free Heroku Dynos, free Heroku Postgres, and free Heroku Data for Redis® will no longer be available.**
> 
> 
> If you have apps using any of these resources, you must upgrade to paid plans by this date to ensure your apps continue to run and to retain your data. For students, we will announce a new program by the end of September.[ Learn more](https://blog.heroku.com/next-chapter)

Well, all good things must come to an end :(

Looks like after this, it will no longer be possible to host an app for free. Cheapest option for Heroku is 9 USD per month.
What would be the course of action for the Heroku tutorial? Will you consider rewriting it for another service?

**Comment by miguelgrinberg** [comment]
I am not planning to change the tutorial.

The idea of showing a Heroku deployment was not that is was free, it was to demonstrate a high-level platform-as-a-service option. The free tier of Heroku has always been extremely limited, and has never been viable for a production deployment, outside of the most simple tests.
