### ISSUE TITLE
No such file or directory after adding Logging db_migrate

### ISSUE THREAD

**Issue by KevDi** [miguelgrinberg/microblog#33]
I followed your great tutorial (thanks for that great one) and i'm now on Part 8. I noticed that i become a 

No such file or directory Error
for the microblog.log file. It seems to look inside the app directory for the tmp Directory and inside there for the log file. Strange is that this only happens in the db_migrate file. 
The config.py and the __init__.py are like the ones in your repository.

**Comment by miguelgrinberg** [comment]
What is your current directory? You should be starting the script from the root directory, one level above the `app` package.

**Comment by KevDi** [comment]
Thank you for your reply. The problem was the wrong working directory. Now the script runs
