### ISSUE TITLE
sqlalchemy.exc.OperationalError

### ISSUE THREAD

**Issue by yishun-Liu** [miguelgrinberg/microblog#331]
Dear blogger, I want to know how you managed to run this project successfully? I tried to add the following code in the microblog.py file to run the project and used the registration function, but the program reported the following error. Could you please tell me how to solve it?
Add the code launcher as shown in the figure：
![image](https://user-images.githubusercontent.com/92320906/202981582-b70285a7-958f-4bba-b973-67272719bef1.png)

Program error as shown below：
![image](https://user-images.githubusercontent.com/92320906/202981878-0c240282-125c-4048-b466-756408e2a323.png)

**Comment by miguelgrinberg** [comment]
@yishun-Liu Are you following my tutorial? I'm not sure what you are trying to do, but the code that you added is not part of the tutorial. The shell context function is not supposed to be called directly, what you are doing is incorrect.

**Comment by yishun-Liu** [comment]
I found it was caused by the conflict between the Python version and the Jinja2 version. The problem has been solved. Thank you very much and wish you good health.
