### ISSUE TITLE
Ch4: flask application context

### ISSUE THREAD

**Issue by stressfulPanda** [miguelgrinberg/microblog#334]
I have followed the tutorial to Chapter 4, but when I run 

`db.session.add(u)`

I get:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dev/code/tutorial/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 361, in add
    return self._proxied.add(instance, _warn=_warn)
  File "/home/dev/code/tutorial/venv/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 188, in _proxied
    return self.registry()
  File "/home/dev/code/tutorial/venv/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 639, in __call__
    key = self.scopefunc()
  File "/home/dev/code/tutorial/venv/lib/python3.10/site-packages/flask_sqlalchemy/session.py", line 81, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "/home/dev/code/tutorial/venv/lib/python3.10/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.`

I have deleted the migrations folder and app.db and run through it again, still the same result. I have checked the Ch4 github branch and there are no code diffs between mine and the source. I have looked at the Application Context docs the recommendations differ from the tutorial code. I have also looked at SO examples, which align to the docs, but again differ from the tutorial code. I am stuck, any help would be appreciated.

**Comment by stressfulPanda** [comment]
My requirements.txt reads as:

alembic==1.9.2
click==8.1.3
Flask==2.2.2
Flask-Migrate==4.0.3
Flask-SQLAlchemy==3.0.2
Flask-WTF==1.1.1
greenlet==2.0.2
itsdangerous==2.1.2
Jinja2==3.1.2
Mako==1.2.4
MarkupSafe==2.1.2
python-dotenv==0.21.1
SQLAlchemy==2.0.0
typing_extensions==4.4.0
Werkzeug==2.2.2
WTForms==3.0.1

**Comment by miguelgrinberg** [comment]
This is due to a recent change in Flask-SQLAlchemy that is backwards incompatible. One possible solution is to enter these two lines in your Python session:

```python
from app import app
app.app_context().push()
```

Another option is to open a Flask shell instead of a regular Python shell, by using the `flask shell` command, which does the above automatically.

**Comment by stressfulPanda** [comment]
Brilliant, thanks @miguelgrinberg that solved the issue.
