### ISSUE TITLE
How to solve the syntax conflict between JinJia2 and CSS in chapter 21.3 ?

### ISSUE THREAD

**Issue by JTP-123** [miguelgrinberg/microblog#337]
I met such a question that JinJia2 used in CSS inline style will cause a conflict that the default block string will be misunderstood as a css property value in visual studio code . The detail is :
```
<span id='message_count' class="badge"
            style="visibility: {% if new_messages %}visible
            {% else %}hidden {% endif %};">
```
---
I happend to find a related plausible solution that is to set <code>app.jinja_env.block_start_string = '(%'</code>, this solution asks me to alter every existed block start string , that would be boring. So is there anyway to solve such question besides this?

**Comment by miguelgrinberg** [comment]
Are you just concerned about the way the code is highlighted in VS Code? In that case you may want to install a Jinja extension. I don't really have experience with this, but a Google search returned https://marketplace.visualstudio.com/items?itemName=samuelcolvin.jinjahtml. Hopefully that works.

**Comment by JTP-123** [comment]
> Are you just concerned about the way the code is highlighted in VS Code? In that case you may want to install a Jinja extension. I don't really have experience with this, but a Google search returned https://marketplace.visualstudio.com/items?itemName=samuelcolvin.jinjahtml. Hopefully that works.

The above code  will be shown in VS Code like this: 
![批注 2023-02-27 114326](https://user-images.githubusercontent.com/68136548/222619101-ebed4d5f-e12f-4e32-85c9-23c9c4a3cac1.jpg)

**Comment by miguelgrinberg** [comment]
As I explained, this is not a problem, it's just that VS Code does not understand the Jinja template syntax. Have you tried installing a Jinja plugin?

**Comment by JTP-123** [comment]
> As I explained, this is not a problem, it's just that VS Code does not understand the Jinja template syntax. Have you tried installing a Jinja plugin?

Yes, i have installed Better JinJa,  it seems that this plugin changes nothing. But it does really not matter, what i really care about is that syntax conflict, and now i know i made a mistake. Thank you so much.

**Comment by JTP-123** [comment]
> As I explained, this is not a problem, it's just that VS Code does not understand the Jinja template syntax. Have you tried installing a Jinja plugin?

Oh, i made a mistake, thank you for your reply. By the way, i have installed Better JinJa, but it seems that this plugin changes nothing, did i miss some key step?

**Comment by miguelgrinberg** [comment]
I'm not sure if you made a mistake or not. As I said above, I'm not familiar with the Jinja plugins available for VS Code, so I don't know how they are used, or if they need some special configuration.

My opinion is that this can be ignored. As I said above, this isn't an error in your application, it's just that VS Code does not understand the Jinja template syntax.

**Comment by JTP-123** [comment]
> I'm not sure if you made a mistake or not. As I said above, I'm not familiar with the Jinja plugins available for VS Code, so I don't know how they are used, or if they need some special configuration.
> 
> My opinion is that this can be ignored. As I said above, this isn't an error in your application, it's just that VS Code does not understand the Jinja template syntax.

ok, now that it is not a problem, i will leave aside it. thank you for your reply, sincerely.
