### ISSUE TITLE
Did you check documentation? 

### ISSUE THREAD

**Issue by Towareesh** [miguelgrinberg/microblog#339]
https://github.com/miguelgrinberg/microblog/blob/f4a401e32077ab6ceada5bf5ae3cea7c0b34cf81/app/__init__.py#L79
[You have to set locale_selector to be able use own function:](https://stackoverflow.com/questions/75229322/flask-babel-get-locale-seems-to-be-not-working)

**Comment by miguelgrinberg** [comment]
https://github.com/miguelgrinberg/microblog/blob/3472187155ba60d36aa819cf4e6dbfeefeadf2fa/requirements.txt#L12

You are using a fairly recent version of Flask-Babel. See the requirements in this repository. If you want this project to work correctly use the versions I'm using. I am currently working on an update that includes this and other recent changes to dependencies.

**Comment by Towareesh** [comment]
Thanks for answer

сб, 4 мар. 2023 г. в 17:49, Miguel Grinberg ***@***.***>:
