### ISSUE TITLE
AttributeError: 'Babel' object has no attribute 'localeselector'

### ISSUE THREAD

**Issue by jwmurray** [miguelgrinberg/microblog#342]
I have looked around to find the source of this error, to no avail.

Using the Chapter 4 code and the final code for the microblog, after updatint the requirements.txt file several times and using pythono 3.11.2 and babl version 3.01, I get this error.

I see that you have a Bable 3.0 bug registered, but not resolved.  Is this related to the bug you are already tracking?

I love the books!

thank you,

john

`  File "/local/home/jwmu/code/microblog/chapter4/microblog/venv/lib/python3.11/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/local/home/jwmu/code/microblog/chapter4/microblog/venv/lib/python3.11/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/local/home/jwmu/code/microblog/chapter4/microblog/microblog.py", line 1, in <module>
    from app import create_app, db, cli
  File "/local/home/jwmu/code/microblog/chapter4/microblog/app/__init__.py", line 94, in <module>
    @babel.localeselector
     ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Babel' object has no attribute 'localeselector'`

if I comment out the following code from __init__.py, the error does not occur:

`
@babel.localeselector
def get_locale():
    return request.accept_languages.best_match(current_app.config['LANGUAGES'])
`

**Comment by miguelgrinberg** [comment]
The current version of the tutorial uses the 2.x releases of Babel. The 3.x releases are not backwards compatible, and I haven't gotten around to make an update yet, but I will get to this soon. In the meantime you can install Babel and Flask-Babel 2.

**Comment by jwmurray** [comment]
That worked.  Thank you.

The hard part now is trying to figure out how to create a simpler application.  

My goal is to 
1. Pull a bunch of json data into an SQLAlquemy database
2. Figure out how to avoid going into python shell to create the database tables
3. Create a couple of views based on queries
4. Display those
5. Then use your method of paginating and filtering the data from one of your youtube posts

I can tell that if I understand it, it will be elegant and beautiful.  I am just taking too long to figure it out.

Some guy at work did it in Ruby.  I am supposed to modify his code, but I don't want to learn Ruby.  So, I bought a couple of your books and trying to figure out how to simplify your microblog.

I love how you are able to separate out the models and the routes so cleanly.  Sometimes python fights the imports of local stuff. 

I will close this.
