### ISSUE TITLE
Popover does not work in chapter 20 due to bootstrapcdn source issue? 

### ISSUE THREAD

**Issue by JTP-123** [miguelgrinberg/microblog#345]
It showed nothing when my mouse pointer hover upon a username. The browser console reported such issue as follows:
"Failed to https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css source  : net::ERR_CONNECTION_TIMED_OUT"
I have found some related question in url https://github.com/jsdelivr/bootstrapcdn/issues/1203, but it seems not helpful.
I can'f figure out this bootstrpcdn source issue. is there any possible solution ? 
![1](https://github.com/miguelgrinberg/microblog/assets/68136548/ebd6f3fb-62ea-4000-938d-cc765bc55a11)
![2](https://github.com/miguelgrinberg/microblog/assets/68136548/b6ad17bd-554e-4481-addc-68756e9f772e)
![3](https://github.com/miguelgrinberg/microblog/assets/68136548/9c7ec701-5259-43eb-8cbf-2166bbbd1eaf)
![4](https://github.com/miguelgrinberg/microblog/assets/68136548/bab3bf21-6451-40e6-a2c1-f39958c1d9ea)

**Comment by miguelgrinberg** [comment]
The URL that is referenced in your error seems to work fine today. Maybe it was a temporary hiccup?

**Comment by JTP-123** [comment]
> The URL that is referenced in your error seems to work fine today. Maybe it was a temporary hiccup?

I can visit the above referenced url, but after a long while, it remained same when i had a look at popover content again.

**Comment by JTP-123** [comment]
I am so sorry for interrupting again. After several month, this question can still not be resolved, for i just dived into javascript learning since this question was raised and then flask learning was paused.  The good news is that such above error report does not exist when looking back now, but popover still does not work when mouse hovers upon icon. I have proofread source code with typed code, but all my effort was in vain. really frustrated.

**Comment by JTP-123** [comment]
> @JTP-123 any errors in the browser's console?
 I have read that chapter 20 again, it works after code retyped.  Although the reason still hides itself,  Thank you so much.
