### ISSUE TITLE
elastic_transport.ConnectionError when post is submitted?

### ISSUE THREAD

**Issue by JTP-123** [miguelgrinberg/microblog#349]
when I opt to submit posts,  it produces a hiccup and  then reports elastic_transport_ConnectionError. But when the page was reloaded, the new post indeed sits here. When prompt line opens the elasticsearch, such error will not show up and this post will be posted  successfully. which part is wrong?
![批注 2023-09-15 094333](https://github.com/miguelgrinberg/microblog/assets/68136548/249be14c-0d5a-440b-a147-6f708246eca1)

**Comment by miguelgrinberg** [comment]
Are you running Elasticsearch as shown in the tutorial?

**Comment by JTP-123** [comment]
> Are you running Elasticsearch as shown in the tutorial?

what do you mean?

**Comment by JTP-123** [comment]
> Are you running Elasticsearch as shown in the tutorial?

Sorry, you mean i have to open elasticsearch by prompt line during posting?  if i run source code, it seems that i do not have to open elasticsearch when i want to post.

**Comment by miguelgrinberg** [comment]
I'm just trying to figure out what you are doing, I'm not trying to tell you what you should or should not do.

The error means that your application is trying to connect to Elasticsearch, and the connection is failing.

**Comment by JTP-123** [comment]
> I'm just trying to figure out what you are doing, I'm not trying to tell you what you should or should not do.
> 
> The error means that your application is trying to connect to Elasticsearch, and the connection is failing.

I have noticed a detail in the very beginning of the second paragraph in chapter 16.20, which is quoted as follows:
"Once you install Elasticsearch on your computer, you can verify that it
is running by typing http://localhost:9200 in your browser’s address
bar, which should return some basic information about the service in
JSON format"
so once i install elasticsearch and open port 9200 by using command "python -m http.server 9200",  but it only shows a list of documents rather than JSON format when entering url localhost:9200 in address bar, just like this. Did I misunderstood?

![1](https://github.com/miguelgrinberg/microblog/assets/68136548/3937637c-afdb-454e-b8c4-92e7857435c9)

**Comment by JTP-123** [comment]
So Elasticsearch installed is definitely not running according to this detail,  To solve this bane, i open the elasticsearch service in cmd, and it indeed is posted successfully while elasticsearch is running. My question is that, according to running complete code, it seems that i do not need to open elasticsearch service in cmd (i tried this) and posts are submitted, why?

**Comment by miguelgrinberg** [comment]
This is explained later in the tutorial. You are jumping ahead.
