### ISSUE TITLE
Language inconsistency during poedit translation process?

### ISSUE THREAD

**Issue by JTP-123** [miguelgrinberg/microblog#350]
According to tutorial, i used poedit to translate language. But a single language is a mix of two different languages like chinese and english. The tricky point is that <code>%(when)s</code> produces an uncertain long string whose format is like "number + date"
rather than a single string. How to solve it to make it become a pure one-kind language?
![5](https://github.com/miguelgrinberg/microblog/assets/68136548/ce45bb4c-a04a-40dc-b0cc-1bc51ebf739e)
![6](https://github.com/miguelgrinberg/microblog/assets/68136548/f282b8d5-7f28-48f1-8d85-8f5bdcc85647)

**Comment by JTP-123** [comment]
Precisely speaking, <code>%(username) said %(when)s</code> shoudle be translated into a whole chinese clause like “username 发布于 10 天前" ranther than a mix  'username 发布于 10 days ago'.
![7](https://github.com/miguelgrinberg/microblog/assets/68136548/691d3ced-0bad-4cad-b555-eb9a945ab848)

**Comment by miguelgrinberg** [comment]
[This line](https://github.com/miguelgrinberg/microblog/blob/main/app/templates/base.html#L84) shows how to set the locale for date and time conversions. If this does not work for Chinese, then it is a problem with the moment.js library and should be reported to them as a bug.

**Comment by JTP-123** [comment]
> [This line](https://github.com/miguelgrinberg/microblog/blob/main/app/templates/base.html#L84) shows how to set the locale for date and time conversions. If this does not work for Chinese, then it is a problem with the moment.js library and should be reported to them as a bug.

I indeed have these code in base template and in routes.py
![8](https://github.com/miguelgrinberg/microblog/assets/68136548/19215645-e658-4da5-b331-c3cb94dd863c)
![9](https://github.com/miguelgrinberg/microblog/assets/68136548/f4d9bdc2-946e-43db-9de5-c8f3841bf0f9)

**Comment by miguelgrinberg** [comment]
To test Chinese timestamps, I changed the line I highlighted above in base.html to this:

        {{ moment.lang('zh-cn') }}

Then I started the application, and I'm getting timestamps in Chinese.

![image](https://github.com/miguelgrinberg/microblog/assets/2715854/e1f4a11b-27a9-473c-b1bd-c81a2024aa01)

I do not know if this is correct or not, but the moment.js library clearly has support for the language.

**Comment by JTP-123** [comment]
I happen to find a chinese who have meet same question at <a>https://zhuanlan.zhihu.com/p/79061618</a>. 
According to his statement, the reason lies in the language code acceptance inconsistency between flask_babel and moment.js: 

> the get_locale function from flask_babel only accepts chinese code <code>'zh'</code> and <code>'zh-cn'</code>. But moment.lang(g.locale) only accepts zh_cn.


I don't find any support from moment.js or  flask_babel documentation.

**Comment by JTP-123** [comment]
I happen to find a chinese who have meet same question at <a>https://zhuanlan.zhihu.com/p/79061618</a>. 
According to his statement, the reason lies in the language code acceptance inconsistency between flask_babel and moment.js: 

> the get_locale function from flask_babel only accepts chinese code <code>'zh'</code> and <code>'zh-cn'</code>. But moment.lang(g.locale) only accepts <code>zh_cn</code>.


I don't find any support from moment.js or  flask_babel documentation.

**Comment by miguelgrinberg** [comment]
As I said before, it is difficult for me to test a language that I do not understand, but based on what I could find out the solution is to use a language code that is supported by moment.js. The list of available locales is here: https://github.com/moment/moment/tree/develop/locale. There are four Chinese regions to choose from.

Once you select the one you want to use, create a translation repository with that language code, and then I think everything will work correctly for you.

**Comment by JTP-123** [comment]
Thank you for your patience to answer my question.
