### ISSUE TITLE
Using JinJa2 filter function truncate to implement 'Read more'?

### ISSUE THREAD

**Issue by JTP-123** [miguelgrinberg/microblog#351]
I design to implement one functionality that the hidden part of article will be shown when  i click the font "read more" using JinJa2's filter truncate as follows. 
![2](https://github.com/miguelgrinberg/microblog/assets/68136548/ebaed43e-94fe-4aea-80a4-e0fd505d7c6a)
it supposed to be string<code>truncate...</code>, but it fails to work:
![1](https://github.com/miguelgrinberg/microblog/assets/68136548/85b0c40e-6a4d-41b0-bf00-899763740593)

**Comment by miguelgrinberg** [comment]
My guess is that the if condition, not shown in your screen capture, is incorrect.

**Comment by JTP-123** [comment]
> My guess is that the if condition, not shown in your screen capture, is incorrect.

The if condition is that:
![3](https://github.com/miguelgrinberg/microblog/assets/68136548/a2071f79-5d61-40ff-b2b3-c30b82a19f54)

**Comment by miguelgrinberg** [comment]
The condition is always true. How did you want to decide when to show the file text and when to show the truncated version?

**Comment by JTP-123** [comment]
I want to use the truncated vision if the text's length is larger than the given argument to truncate functon at any time. In such case, the given length is 10.

**Comment by miguelgrinberg** [comment]
First of all, I don't believe doing this in a Jinja template is a good idea. Normally you would do this in JavaScript. Because when you click "Read More" in the template the whole page is going to refresh. For this to work smoothly you want the page to update dynamically from JavaScript.

But in any case, you are missing a condition that checks for the length of the comment. You did not put that anywhere.

**Comment by JTP-123** [comment]
The source code said :<code>truncate(env, s, length=255, killwords=False, end="...")</code>, i think the third argument is that given length which function as if condition.  Does i mistaken it?

**Comment by miguelgrinberg** [comment]
The truncated comment is in the else part of the conditional. The if condition is always true, so that code will never execute.

**Comment by JTP-123** [comment]
Sorry, I do not understand.  Why does it falls into the first if condition?  The field post.body_html is about html code, in such case, is markdown. The  above post content " truncate this part"  is a plain text string, not code.

**Comment by miguelgrinberg** [comment]
The `{% if post.body_html %}` condition always evaluates to `true`. The only case it would evaluate to `False` is when the field is not set.

**Comment by JTP-123** [comment]
Thnak you, I got it. But i don't know how to fix it using truncate.

**Comment by miguelgrinberg** [comment]
Unfortunately I can't think of any good implementation that is based on Jinja. As I suggested above, this is a dynamic behavior that is best implemented using JavaScript in the browser, Jinja is best suited to rendering static pages.

**Comment by JTP-123** [comment]
I will try to solve it with javscript, thank you so much.

**Comment by JTP-123** [comment]
The if condition always evaluates to <code>true</code> if the body_html field  was set, In the llight of this statement, it will finallly fall into the if condition, right? Or when it falls into the second else condition?

**Comment by miguelgrinberg** [comment]
I'm not sure I understand what you are asking me. The condition`{% if post.body_html %}` will evaluate to true when `post.body_html` has a non empty value. It will evaluate to false when `post.body_html` is empty or `None`.

**Comment by JTP-123** [comment]
In your good book flask development, the related code is:
 <code>
from markdown import markdown
import bleach
class Post(db.Model):
        # ...
        body = db.Column(db.Text)
        body_html = db.Column(db.Text)
        # ...
       @staticmethod
       def on_changed_body(target, value, oldvalue, initiator):
             allowed_tags = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
                                      'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
                                      'h1', 'h2', 'h3', 'p']
             target.body_html = bleach.linkify(bleach.clean(
                   markdown(value, output_format='html'),
                  tags=allowed_tags, strip=True))
db.event.listen(Post.body, 'set', Post.on_changed_body)
</code>
In my opinion, after reading above code, Once a post was submitted, the staticmethod on_changed_body will detect it and automatically run to produce the field <code>body_html</code>. 

<strong>But what if the post content was a plain text without markdown format ? 
What will post_html be? Is it same with <code>body</code> because of html tag absent?</strong>

In the light of this statement, the <code>post.body_html</code> will always exist, then <code>if condition</code> will be true forever. And In template, it will inevitably fall into the first condition, namely <code>if {{ post.body_html }}</code>.

So what's the meaning of  the <code>{{ post.body }}</code> in the second condition else part ? 
 What's wrong with my understanding?

**Comment by miguelgrinberg** [comment]
> But what if the post content was a plain text without markdown format ?

If there is no formatting then `body_html` will have something like `<p>text content of the post</p>`.

> So what's the meaning of the {{ post.body }} in the second condition else part ?

The `{{ post.body }}` is there to render any blog posts that for any reason did not get their rendered version stored in `body_html`. For example, posts that are in your database from before the markdown support was added to the application. This is called "defensive programming", the idea is to make sure unexpected or unusual conditions are handled correctly.

**Comment by JTP-123** [comment]
I have used simple javascript to implement this, but i also want to do experiment with JinJa template out of curiosity. But it raises <code>SyntaxError jinja2.exceptions.TemplateSyntaxError: expected token ':', got '}'</code>. why did <code>{% if {{post.body_html | safe | striptags | length}} >= 255 %}</code> cause error? Actually, I just want the text "Read more" not to show in some short posts.

**Comment by miguelgrinberg** [comment]
You can't use `{{` and `}}` inside a `{% .. %}` block.

**Comment by JTP-123** [comment]
what should I do to fix it ?

**Comment by miguelgrinberg** [comment]
Did you try removing the `{{` and `}}`? I recommend that you review the [Jinja documentation](https://jinja.palletsprojects.com/en/3.0.x/templates/), which has many actual examples of control structures.

**Comment by JTP-123** [comment]
It works. I thought <code>post.body_html | safe | striptags | length</code> was a variable and has to be embraced with <code>{{</code> and <code>}}</code>.
