### ISSUE TITLE
Lesson 6, FLASK_ENV is removed from Flask 2.3.0

### ISSUE THREAD

**Issue by klinge** [miguelgrinberg/microblog#353]
In lesson 6 the code suggests enabling debugging by setting FLASK_ENV=development. 

This does not work since the environment variable FLASK_ENV is [removed](https://flask.palletsprojects.com/en/3.0.x/changes/) from Flask version 2.3.0. 

The new way to enable debugging is to set the environment variable: 
FLASK_DEBUG=True

**Comment by miguelgrinberg** [comment]
> The new way

The new old way is how I would call it. :)

The `FLASK_DEBUG` variable was the way to do this in the 0.x and 1.x versions of Flask. The Flask Mega-Tutorial made use of it. At some point they decided that `FLASK_ENV` was better. The Flask Mega-Tutorial was updated to reflect their thinking. Now they decided that `FLASK_DEBUG` is actually better and not worse, and removed `FLASK_ENV`. I really try to not be frustrated by all the breakage these people generate with this and many other silly changes like it, but it is really hard not to be! They continue putting out releases with no substantive changes, just renames and removals.
