### ISSUE TITLE
Unable to import 'url_parse' from 'werkzeug.urls' in flask shell execution

### ISSUE THREAD

**Issue by JRGaddy** [miguelgrinberg/microblog#355]
Section 5.8, attempt to run flask shell results in "ImportError: cannot import name 'url_parse' form 'werkzeug.urls'  -- Running Python 3.9 on Raspberry Pi Model 4 with Bullseye

**Comment by miguelgrinberg** [comment]
Flask introduced breaking changes recently. The solution is to upgrade Flask, Werkzeug and Flask-Login to their latest releases.

**Comment by JRGaddy** [comment]
I tried this solution and it did not work, nor did the one proposed by Klinge earlier.  Anything more to try?

**Comment by JRGaddy** [comment]
Unfortunately, this solution did not work.  All of the relevant packages were reported back as “Requirement already satisfied.”  The solution proposed in October by another contributor did not work either.  Any further updates?

Thanks,
Jim Gaddy

**Comment by miguelgrinberg** [comment]
Please provide the stack trace of the error.

**Comment by JRGaddy** [comment]
Hope this is what you requested:
(venv) pi@Four:~/microblog $ flask shell
Usage: flask shell [OPTIONS]
Try 'flask shell --help' for help.

Error: While importing 'microblog', an ImportError was raised:

Traceback (most recent call last):
  File "/home/pi/microblog/venv/lib/python3.9/site-packages/flask/cli.py", line 219, in locate_app
    __import__(module_name)
  File "/home/pi/microblog/microblog.py", line 1, in <module>
    from app import app, db
  File "/home/pi/microblog/app/__init__.py", line 15, in <module>
    from app import routes, models
  File "/home/pi/microblog/app/routes.py", line 7, in <module>
    from werkzeug import url_parse
ImportError: cannot import name 'url_parse' from 'werkzeug' (/home/pi/microblog/venv/lib/python3.9/site-packages/werkzeug/__init__.py)

**Comment by miguelgrinberg** [comment]
I'm sorry, my bad. I missed one instance that I need to fix.

Temporary workaround is to stay on Flask 2.x. Use this command to downgrade:

```bash
pip install "flask<3" "werkzeug<3"
```

This should allow you to continue with the tutorial until I update this code.

**Comment by miguelgrinberg** [comment]
The correct import is:

    from werkzeug.urls import url_parse

**Comment by JRGaddy** [comment]
After correcting my omission and downgrading the packages, I am still having problems.  Rather than churn both our schedules, I think it best to wait until you have worked out the bug using the latest Flask/Werkzeug packages.  I appreciate you prompt attention and your continuing efforts, and I look foward to continuing with the tutorial in its revised version.  Thanks.

**Comment by miguelgrinberg** [comment]
Are you having the same problem or something else? The changes that I will need to make for Flask 3 is just to find an alternative to the `url_parse` function, which the Flask maintainers decided to delete from the project.

If you are having other problems after you got past this one it might be best to mention what the new problem is, in case it is something else I need to be aware of.

**Comment by JRGaddy** [comment]
After downgrading Flask & Werzeug, ‘flask shell’ works but when I continue in the tutorial, the entry “u.set_password(‘cat’)” results in an error message: ‘Attribute error: ‘User’ object has no attribute ’set password’.  I have no idea how to proceed from that.

**Comment by miguelgrinberg** [comment]
@JRGaddy that is because I'm guessing you missed adding the `set_password()` method to the `User` class. Do a search for `set_password` in Chapter 5 to find all the references to it. You must have missed the part where this method is added.

**Comment by JRGaddy** [comment]
Yes, that was it.  Thank you for your time and patience.  I will proceed with the tutorial and look forward to any updates.

**Comment by miguelgrinberg** [comment]
Closing as this does not apply to the new edition of this tutorial.

**Comment by truenothing** [comment]
As per Werkzeug documentation (https://werkzeug.palletsprojects.com/en/3.0.x/changes/#version-3-0-1):

Deprecate the werkzeug.urls module, except for the uri_to_iri and iri_to_uri functions. Use the urllib.parse library instead. [#2600](https://github.com/pallets/werkzeug/issues/2600)

So this function is no longer there anymore.

Changes:

`#from werkzeug.urls import url_parse`
`from urllib.parse import urlparse`

and 

`if not next_page or urlparse(next_page).netloc != '': #or url_parse(next_page).netloc != '':`

seem to be working.
