### ISSUE TITLE
Dead link to flask-babel docs

### ISSUE THREAD

**Issue by kingkong-cmd** [miguelgrinberg/microblog#361]
Chapter 13; Introduction to Flask-Babel; The extension is called [Flask-Babel](https://pythonhosted.org/Flask-Babel/) and...

`https://pythonhosted.org/Flask-Babel/` redirects to -> `https://flask-babel.tkte.ch/`. Flask-babel docs are now on `https://python-babel.github.io/flask-babel/`.

**Comment by miguelgrinberg** [comment]
Thanks. I updated the link.
