### ISSUE TITLE
extra 'novalidate' attribute in form tag

### ISSUE THREAD

**Issue by bernardfitch** [miguelgrinberg/microblog#395]
Unless I'm reading the template wrong (which is quite possible!), I think that you have an extra 'novalidate' attribute in the form tag that starts on [line 48 of the bootstrap_wtf.html template](https://github.com/miguelgrinberg/microblog/blob/11b588c92faf58780b5d59ce1d6e5524ceb4f112/app/templates/bootstrap_wtf.html#L48C7-L48C17) - given that you add one (conditionally) later on (on line 52).

(Thanks for creating the 'mega tutorial' - and all your Flask work, I've really enjoyed playing with it)

**Comment by miguelgrinberg** [comment]
You are correct, I'll fix it. Thanks!

**Comment by miguelgrinberg** [comment]
The extra `novalidate` has been removed. Thanks!
