### ISSUE TITLE
TypeError: 'AnonymousUserMixin' object is not callable

### ISSUE THREAD

**Issue by felexkemboi** [miguelgrinberg/microblog#40]
below is my code

from app import db

class User(db.Model): 
    id = db.Column(db.Integer, primary_key=True)
    nickname = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    posts = db.relationship('Post', backref = 'author',lazy ='dynamic')

    # just return True unless the object represents a user that should not be allowed to authenticate for some reason.
    @property
    def is_authenticated(self):
        return True
    
    #should return True for users unless they are inactive e.g they have been banned
    @property
    def is_active(self):
     	return False

    #should return True for users that are not supposed to log in to the system
    
    @property
    def is_anonymous(self):
        return False
    

    def get_id(self):
     	 try:
     		return unicode(self.id) #for python 2
         except NameError:
        	return str(self.id) #for python 3   

    def __repr__(self):
         return '<User %r>' % (self.nickname)

**Comment by miguelgrinberg** [comment]
Please provide the complete stack trace of your error.

**Comment by felexkemboi** [comment]
for example convert 
@property
def is_anonymous(self):
    return False
to be a property

**Comment by miguelgrinberg** [comment]
Closing this issue, as it does not apply anymore.
