### ISSUE TITLE
Chapter 5: User Logins - app/models.py - can't find generate_password_hash ...

### ISSUE THREAD

**Issue by dastagg** [miguelgrinberg/microblog#41]
In app/models.py:

The import:
```from werkzeug import generate_password_hash, check_password_hash```
should be:
```from werkzeug.security import generate_password_hash, check_password_hash```

In order to prepare for V1.0 of werkzeug, the automatic redirect was removed.

**Comment by miguelgrinberg** [comment]
Do you have any reference to this? Werkzeug master still supports the redirects.

**Comment by dastagg** [comment]
I am using Pycharm and it didn't find the methods.
I am using Werkzeug V0.13.
I looked at [Werkzeug Transition](http://werkzeug.pocoo.org/docs/0.13/transition/) and that's where I read about the re-direct being removed.
Once I changed it, Pycharm recognized it and it worked.

**Comment by dastagg** [comment]
Maybe it's a bug in Pycharm?
Later today, I'll try it in another Editor like VSCode and see if the same issue surfaces.

**Comment by miguelgrinberg** [comment]
Yes and no. Werkzeug uses a little bit of hackery to get all those imports available as top-level symbols. Pycharm probably does not find them because there aren't really any explicit `import` statements, the redirection is done using Python logic, not imports.

**Comment by dastagg** [comment]
I just tried closing Pycharm, opening the code in VSCode with the Python Extension enabled and pylint installed.
If I remove the security, the app still runs correctly but pylint displays an E611 error that those two names cannot be found in werkzeug.

To Summarize:

The import of the two methods works as far as the app running correctly goes but in order make the "error" go away in both Pycharm and VSCode, you have to be more explicit and make it "werkzeug.security".

**Comment by dastagg** [comment]
I'm going to close this issue as it's not really a problem with the application code.
