### ISSUE TITLE
chapter 5 - import werkzeug into models.py not explicitly mentioned

### ISSUE THREAD

**Issue by eriksays** [miguelgrinberg/microblog#42]
In the book, chapter 5.3 mentions importing werkzeug in the python terminal; however, it doesn't seem to explicitly mention to include the library in models.py.

I got a 'could not find generate_password_hash' until I looked at the git repo

just FYI -- great book.

also, if I misread or otherwise -- my apologies.

**Comment by dastagg** [comment]
Yeah, I can confirm this is true as well. I had to look at the git repo as well.

**Comment by miguelgrinberg** [comment]
Thanks. Fix is coming with the next drop in a day or two.
