### ISSUE TITLE
chapter 7.3 error pages, put the FLASK_DEBUG back to 0

### ISSUE THREAD

**Issue by eriksays** [miguelgrinberg/microblog#44]
just a comment, in chapter 7.3, we put the app into debug FLASK_DEBUG=1 and then we build the custom 404 and 500 pages.
One note you might put into the chapter is to put FLASK_DEBUG=0 so we actually see the error pages.

thanks :)
I'm enjoying the book

**Comment by miguelgrinberg** [comment]
Yes, I agree. I'll add a note regarding this. Thanks!
