### ISSUE TITLE
no such table: user

### ISSUE THREAD

**Issue by eriksays** [miguelgrinberg/microblog#45]
after running chapter 8 -- follower, contacts and friends
doing the tests.py, etc.
I attempt to login and 'follow' but get a "sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user"
i tried 'sqlite3' on terminal and the only table in sqlite app.db is alembic_version
I attempt 'flask db downgrade' and get "no such table: followers"

I'm going to keep looking, but is possible the tests.py emptied the database?

the beginning of my tests.py file:

```
class UserModelCase(unittest.TestCase):
    def setUp(self):
        app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite://'
        db.create_all()

    def tearDown(self):
        db.session.remove()
        db.drop_all()

```

**Comment by eriksays** [comment]
nm on this.
I rebuilt the migrations and it's working as expectd now.

**Comment by zjscy666** [comment]
I add this:
with app.app_context():
        db.create_all()
Now it can work

**Comment by miguelgrinberg** [comment]
@zjscy666 your approach is incorrect, as it bypasses the migration framework. The correct way to generate the database for this project is to run `flask db upgrade`.
