### ISSUE TITLE
Flask Admin

### ISSUE THREAD

**Issue by doaa-altarawy** [miguelgrinberg/microblog#49]
Is it possible to add Flask_admin to this tutorial?
It's a very useful and powerful extension. 
It will be very interesting to see how you would use it with this new Flask structure.

**Comment by miguelgrinberg** [comment]
The topic list is now closed, maybe if I do another round of updates at some point. But I honestly don't see much educational value in showing how to use Flask-Admin, while the extension can be useful for some types of applications, it does not really teach any new concepts. My suggestion is that you fork the project and work on adding it yourself as an exercise.

**Comment by doaa-altarawy** [comment]
Thanks. Would you accept pull requests on this repository (if it meets the coding style)?

**Comment by doaa-altarawy** [comment]
Also, Flask_Admin is a good example of circular import in multi-file flask projects (models needs db, admin needs models, and create_app register Admin_views)

**Comment by miguelgrinberg** [comment]
I can't accept it on this repository because it will be out of sync with the tutorial, but I can leave the PR here for others that are interested in seeing how you integrated it.

**Comment by SebastianOpiyo** [comment]
@doaa-altarawy, seems a good way to handle the problem, I am so convinced before I try it out. Thanks.

**Comment by ElLorans** [comment]
> ```python
> def add_admin_views():
>     """Register views to admin"""
> 
>     from .. import app_admin
>     app_admin.add_view(SoftwareView(Software, name='Software List'))
>     app_admin.add_view(UserView(User, name='Users'))
> ```

You are missing the app_admin, aren't you?
