### ISSUE TITLE
translate.py TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by immontilla** [miguelgrinberg/microblog#51]
Hello,

return json.loads(r.content) raise an error _TypeError: the JSON object must be str, not 'bytes'_

_return json.loads(r.content.decode('utf-8-sig'))_ fix it.

Regards,

immontilla

**Comment by miguelgrinberg** [comment]
What version of Python are you using?

**Comment by immontilla** [comment]
Python 3.5.2 on Ubuntu 16.04.3 LTS

**Comment by miguelgrinberg** [comment]
Oh, interesting, Python 3.6 does not appear to mind, but yeah, 3.5 does need the argument to be a string. I'll make an update, thanks.
