### ISSUE TITLE
chapter 16, form.py reference

### ISSUE THREAD

**Issue by eriksays** [miguelgrinberg/microblog#53]
just a typo I noticed.

Listing 16.7 references app/forms.py which you've moved to app/main/forms.py
Listing 16.8 references from app.forms import SearchForm when you when you want from app.main.forms 

running the app without the typo fix gets a "app.forms not found"

thanks

**Comment by miguelgrinberg** [comment]
Thanks. Looks like I missed a few updates, this happened after I reordered a couple of chapters. I'll get everything fixed.
