### ISSUE TITLE
elasticsearch.exceptions.ConnectionError

### ISSUE THREAD

**Issue by tdeyle** [miguelgrinberg/microblog#54]
Cannot seem to get a connection to the elasticsearch server started. I have tried the example setup in the python shell, import the module, pass the server address and port to the instance of es, however, I get the following error:

```
elasticsearch.exceptions.ConnectionError
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x73fc8a50>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x73fc8a50>: Failed to establish a new connection: [Errno 111] Connection refused)
```
I am running Microblog off a Raspberry Pi 3 server that I have connected remotely through SSH. I checked to see if the port was open with nmap through SSH, and it states:

```
Starting Nmap 7.40 ( https://nmap.org ) at 2017-12-22 13:36 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00029s latency).
Other addresses for localhost (not scanned): ::1
PORT     STATE  SERVICE
9200/tcp closed wap-wsp

Nmap done: 1 IP address (1 host up) scanned in 0.35 seconds

```
All of my testing that I have done is through an SSH shell into the Pi. I also have checked with `sudo netstat -tuplen` to see if port 9200 was open, and it was not shown.

I installed elasticsearch as described in Chapter 16 through pip.

Any assistance would be appreciated.

**Comment by miguelgrinberg** [comment]
You seem to have missed that Elasticsearch is not a Python package. The package that you installed with pip is the Elasticsearch client. You still need to have the service installed on your system. This is going to be the process that opens port 9200.

**Comment by tdeyle** [comment]
Yes, thank you, my mistake.

**Comment by dastorgaIGN** [comment]
Hi, me error is

elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f406014f208>

I want python connection to elasticsearch.

**Comment by miguelgrinberg** [comment]
@dastorgaIGN are you running Elasticsearch in your computer?

**Comment by wkl1998** [comment]
thank you

**Comment by wkl1998** [comment]
@miguelgrinberg thank you！！I forgot running Elasticsearch in my computer.
