### ISSUE TITLE
KeyError: 'POSTS_PER_PAGE'

### ISSUE THREAD

**Issue by tianke0711** [miguelgrinberg/microblog#55]
hi @miguelgrinberg thanks for your great book.

I am studying the chapter 9.4 Pagination of Blog

I almost copy you code about Pagination of Blog.
But after I click the explore, there is error as following in the terminal. Before the chapter 9.4, everything gone well.
The code in routes about explore:

```
@app.route('/', methods=['GET', 'POST'])
@app.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(body=form.post.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post is now live')
        return redirect(url_for('index'))
    page = request.args.get('page', 1, type=int)
    posts = current_user.followed_posts().paginate(
        page, app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('explore', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('explore', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('index.html', title='Home', form=form,
                           posts=posts.items, next_url=next_url,
                           prev_url=prev_url)


@app.route('/explore')
@login_required
def explore():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('explore', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('explore', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('index.html', title='Explore', posts=posts.items,
                           next_url=next_url, prev_url=prev_url) 

```

The error information in terminal as following:

127.0.0.1 - - [22/Dec/2017 23:32:07] "GET /explore HTTP/1.1" 500 -
[2017-12-22 23:32:08,138] ERROR in app: Exception on /index [GET]
Traceback (most recent call last):
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/anaconda3/envs/venv/lib/python3.6/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/kd/microblog/app/routes.py", line 31, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'

**Comment by miguelgrinberg** [comment]
Did you add `POSTS_PER_PAGE` to the configuration in config.py?

**Comment by tianke0711** [comment]
hi @miguelgrinberg thanks for your comment. I have added the PSTS_PER_PAGE in the config.py as following:

```
import os
basedir = os.path.abspath(os.path.dirname(__file__))


class Config(object):
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'you-will-never-guess'
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or \
        'sqlite:///' + os.path.join(basedir, 'app.db')
    SQLALCHEMY_TRACK_MODIFICATIONS = False

    MAIL_SERVER = os.environ.get('MAIL_SERVERE')
    MAIL_PORT = int(os.environ.get('MAIL_PORT') or 25)
    MAIL_USE_TLS = os.environ.get('MAIL_USE_TLS') is not None
    MAIL_USERNAME = os.environ.get('MAIL_USERNAME')
    MAIL_PASSWORD = os.environ.get('MAIL_PASSWORD')
    ADMINS = ['your-email@example']
    POSTS_PER_PAGE = 3
    
```

**Comment by tianke0711** [comment]
Hi @miguelgrinberg do you have some advices about this issue?

**Comment by tianke0711** [comment]
Hi @miguelgrinberg  I have solved since I have put a config.py (this file has set the POSTS_PER_PAGE = 3) in app directory, and there is another config.py (this file has not set the POSTS_PER_PAGE)with microblog directory.  Thanks!
