### ISSUE TITLE
Could microblog support python3?

### ISSUE THREAD

**Issue by leafonsword** [miguelgrinberg/microblog#6]
I'm a python beginner,it seems python3 will be the trend of python though python2 is dominant nowdays,so I study python3~I want to use python to write a personal blog,so I want to study  from microblog~But micro blog is written in python2,so could you support python3?And flask also support python3(maybe some plugins don't support)...

**Comment by fatzombi** [comment]
me too a python beginner :), i started out with python3 can you help me out - how did you exported config.py into app/ without populating sys.path

**Comment by miguelgrinberg** [comment]
Closing this issue, as it does not apply anymore.
