### ISSUE TITLE
Error in Listing 5.1 (UserMixin introduced later)

### ISSUE THREAD

**Issue by sdoering** [miguelgrinberg/microblog#60]
Hi Miguel, 

I just realized, that you have `class User(UserMixin, db.Model):` in Listing 5.1. 

But only in Listing 5.3, after installing flask-login `UserMixin` gets introduced:

`from flask_login import UserMixin`
`class User(UserMixin, db.Model):`
`    # ...`

Best regards
Sven

**Comment by miguelgrinberg** [comment]
Thanks, yes, I reordered the sections of that chapter recently, and that slipped. It should be fixed in the next update I make to the book. Thanks!

**Comment by sdoering** [comment]
You are very welcome. Glad to help.
