### ISSUE TITLE
Search view causing exception

### ISSUE THREAD

**Issue by tripdes** [miguelgrinberg/microblog#64]
https://github.com/miguelgrinberg/microblog/blob/998dffc9b7e98422656f2f23ed98848d6c14f329/app/main/routes.py#L155

This line is causing the app to raise an Exception. It looks like '_' imported from flask-babel has adopted an unnecessary 'l'?

Cheers!

Sam

**Comment by miguelgrinberg** [comment]
Ah, yes, I made a quick fix here in a rush and did not realize that in this case we are using `_()`, not `_l()`. It is fixed now. Thanks!
