### ISSUE TITLE
Ch 19.3 - Docker container exits immediately after docker run

### ISSUE THREAD

**Issue by rlheureu** [miguelgrinberg/microblog#65]
I'm new to Docker so it's possible I missed something here. At 19.3, we're asked to start the Docker container on our local machine with this command:

```
$ docker run --name microblog -d -p 8000:5000 --rm microblog:latest
```

When I do that, it executes successfully and it outputs the long hexadecimal. Next up is:

```
docker ps
```
Which if I run seconds after the previous command, will give me the name of the container ID. However, if you wait 30 seconds, _docker ps_ is empty. Same thing happens at the next step, when we try to start the container with the environment variables loaded. 

Some quick Googling has shown this happening to programs that either complete and exit the container or with commands that exit the shell when run in background mode. I didn't get the impression anything we've done to this point should be affecting that - can anyone replicate or explain what I've missed?

**Comment by miguelgrinberg** [comment]
Run `docker logs <container-id>` to find out why the process exited.

**Comment by rlheureu** [comment]
Ahh super helpful, as the log showed it couldn't find elasticsearch. I realized I hadn't updated my requirements.txt with Elasticsearch. Once I did that, it loaded and ran as expected.
