### ISSUE TITLE
chap 7 tag 0.7 why or 

### ISSUE THREAD

**Issue by playgoods** [miguelgrinberg/microblog#66]
if app.config['MAIL_USERNAME'] **or** app.config['MAIL_PASSWORD']:
this is code above you use or why or i see you must **and** if is i stand wrong :) 
thank you my boss   really the great book

**Comment by miguelgrinberg** [comment]
That is really a matter of choice. What do you want to happen if you forget to set one of the two? With my solution, you will get an authentication error. With your solution, you will get a missing credentials error. No big difference.

**Comment by playgoods** [comment]
thank you for answer :)
