### ISSUE TITLE
SearchableMixin limited to Post objects

### ISSUE THREAD

**Issue by avoidik** [miguelgrinberg/microblog#68]
Hi,

At this moment SearchableMixin is limited only to Post class. Could it be possible to change it to be more universal with the following change?
```
db.case(when, value=cls.id)), total
```

And then reuse the same mixin with User class
```
class User(SearchableMixin, UserMixin, db.Model):
    __searchable__ = ['username']
...
db.event.listen(db.session, 'before_commit', User.before_commit)
db.event.listen(db.session, 'after_commit', User.after_commit)
```

**Comment by miguelgrinberg** [comment]
Oh right, I missed that reference to `Post`, I did intend for this mixin class to be 100% generic. I'll fix it, thanks!
