### ISSUE TITLE
Problem with flask db init

### ISSUE THREAD

**Issue by wengkiat** [miguelgrinberg/microblog#69]
When i run flask db init, i get:

wengkiat$ flask db init
Usage: flask [OPTIONS] COMMAND [ARGS]...

Error: No such command "db".

However, I am able to run flask run as i exported the path.

I am able to reach this part:

->>> from app.models import User
->>> u = User(username='susan', email='susan@example.com')
->>> u
User susan

I have checked your files and my and there seems to be no difference, am i missing something?

**Comment by miguelgrinberg** [comment]
Did you install Flask-Migrate?

**Comment by wengkiat** [comment]
Yes:
wengkiat$ pip install flask-migrate
Requirement already satisfied: flask-migrate in ./venv/lib/python3.6/site-packages
Requirement already satisfied: Flask>=0.9 in ./venv/lib/python3.6/site-packages (from flask-migrate)
Requirement already satisfied: Flask-SQLAlchemy>=1.0 in ./venv/lib/python3.6/site-packages (from flask-migrate)
Requirement already satisfied: alembic>=0.6 in ./venv/lib/python3.6/site-packages (from flask-migrate)
Requirement already satisfied: Flask-Script>=0.6 in ./venv/lib/python3.6/site-packages (from flask-migrate)
Requirement already satisfied: itsdangerous>=0.21 in ./venv/lib/python3.6/site-packages (from Flask>=0.9->flask-migrate)
Requirement already satisfied: Werkzeug>=0.7 in ./venv/lib/python3.6/site-packages (from Flask>=0.9->flask-migrate)
Requirement already satisfied: Jinja2>=2.4 in ./venv/lib/python3.6/site-packages (from Flask>=0.9->flask-migrate)
Requirement already satisfied: click>=2.0 in ./venv/lib/python3.6/site-packages (from Flask>=0.9->flask-migrate)
Requirement already satisfied: SQLAlchemy>=0.7 in ./venv/lib/python3.6/site-packages (from Flask-SQLAlchemy>=1.0->flask-migrate)
Requirement already satisfied: Mako in ./venv/lib/python3.6/site-packages (from alembic>=0.6->flask-migrate)
Requirement already satisfied: python-editor>=0.3 in ./venv/lib/python3.6/site-packages (from alembic>=0.6->flask-migrate)
Requirement already satisfied: python-dateutil in ./venv/lib/python3.6/site-packages (from alembic>=0.6->flask-migrate)
Requirement already satisfied: MarkupSafe>=0.23 in ./venv/lib/python3.6/site-packages (from Jinja2>=2.4->Flask>=0.9->flask-migrate)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.6/site-packages (from python-dateutil->alembic>=0.6->flask-migrate)

**Comment by miguelgrinberg** [comment]
Flask-Migrate should register the `db` command with `flask`. Maybe trash the virtualenv and make a new one, not quite sure what's wrong, but maybe if you start freash you'll get past the problem.

**Comment by amjltc295** [comment]
I got this problem as well. I am using anaconda virtual environment. Flask-Migrate is installed.

**Comment by avoidik** [comment]
Did you tried to use conda? It's Anaconda specific packages manager

**Comment by avoidik** [comment]
Also FLASK_APP env. variable should be set beforehand.

**Comment by stevedunford** [comment]
I had this problem too - it was caused by an outdated version of something (I didn't investigate which).  The solution (for me) was to upgrade flask-migrate, which in turn also updated flask and flask-sqlalchemy among other things

`pip install flask-migrate --upgrade`

Hopefully this helps someone else :)

**Comment by aasimhussain** [comment]
Yes upgrade your flask migrate under virtualenv you are using that will not throw any errors,
use the below command to update your flask migrate
pip install flask-migrate --upgrade

**Comment by p4tin** [comment]
If someone else is still having this problem, I think you might have installed flask globally and that global instance does not have the required libraries from your virtual environment.  This is what I did to make it work:

* `deactivate`
* `pip uninstall flask`
* `source venv/bin/activate`
* and now `flask db init` worked no problem

**Comment by gwdavis** [comment]
> If someone else is still having this problem, I think you might have installed flask globally and that global instance does not have the required libraries from your virtual environment. This is what I did to make it work:
> 
>     * `deactivate`
> 
>     * `pip uninstall flask`
> 
>     * `source venv/bin/activate`
> 
>     * and now `flask db init` worked no problem

This worked for me as well. It seems that Anaconda changed the .bash_profile to point python3 to its version. I would have thought that virtualenv would avoid these conflicts more elegantly than having to uninstall. I had a similar issue with flask-wtf. I was able to resolve that issue by inserting this into config.py:
`sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'venv/Lib/python3.6/site-packages'))
` 
However, this did not help for the `flask db init` command.

**Comment by Great-Li-Xin** [comment]
@miguelgrinberg 
Accidentally, I found a 'sort of' solution which fixes this problem, just install flask-migrate in the global environment and it works. Perhaps it's not the best solution, but at least it is a solution.

**Comment by mossonli** [comment]
what a fuck problem!
if there are several flask virtualenv and someone has been used the command like flask db init 
at the same time if you installed Flask-Migrate, you can try to closed the terminal and open a new one.

**Comment by panhavad** [comment]
This problem happened to me but was solved by deleting my old env folder make the new one and install all module fresh. What he said is totally correct.

> Flask-Migrate should register the `db` command with `flask`. Maybe trash the virtualenv and make a new one, not quite sure what's wrong, but maybe if you start fresh you'll get past the problem.

**Comment by rednafi** [comment]
If you have tried the solutions above and it didn't work, try killing the terminal and opening a new one. Solved my issue!

**Comment by Tloch95** [comment]
> Flask-Migrate should register the `db` command with `flask`. Maybe trash the virtualenv and make a new one, not quite sure what's wrong, but maybe if you start fresh you'll get past the problem.

Tried every solution here except the first one suggested as it was the most cumbersome. Unfortunately, that was what did it for me. Oh well, got there in the end.

**Comment by sssyam** [comment]
For me `deactivate` and `source bin/activate` worked

**Comment by DmiDrok** [comment]
For me rename main.py to app.py

**Comment by jwmurray** [comment]
I have tried all of these options and continue to get "Error: No such command 'db'."

reinstalled Flask-Migrate
reinitialzied venv multiple times
renamed app to app.py

repeated all steps in fish and zsh

et al

Running on macos.

Seems like the flask-migrate extension would throw a debug message to indicate what it is seeing.

**Comment by jwmurray** [comment]
Finally got it to work.  Made two changes:

1. In __init__.py, made sure that `from config import Config` came after the flask_migrate import
2. include `app` in the argument to `migrate = Migrate(app,db) like this:

`from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from config import Config

app = Flask(__name__)

app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app, db)

from app import routes, models`

**Comment by pbharrin** [comment]
I was missing the `Migrate(app, db)` line.

**Comment by mcelhennyi** [comment]
> I was missing the `Migrate(app, db)` line.

Similar to this, I had 
```
if __name__ == "__main__":
    # Init DB - This shall happen after configs above
    init_db()

    # Run the app
    app.run(host='0.0.0.0', debug=debug, port=5001)
```

Where `init_db()` did the following: 
```
def init_db():

    db_local = db
    db_local.init_app(app)
    migrate.init_app(app, db)
...
```
Which caused it to not init, which never initialized my Migrate() object. Since I was doing it the [Command Reference](https://flask-migrate.readthedocs.io/en/latest/#command-reference) way.

So I created a "migrate.py" with:
```
from run import app, init_db

init_db()
```

Then ran the command: 
`python -m flask --app migrate.py db init`

**Comment by qusai95** [comment]
Just add
migrate = Migrate(app,db)
in your main.py page 
this solution is working with me

**Comment by SeeH1OvO** [comment]
hey,bro! I also encountered the same problem! If you have checked the code and there are no issues, and if you are using pycharm, and you only perform library installation under Terminal in pycharm when creating a virtual environment, you may report an error as a result. 
     My suggestion is that if you are a Windows system, please open the command line in Win+R and download the library: pip install Flask-Migrate.
     So, the libraries installed under Terminal in Pycharm may need to be downloaded again in the global environment of Python. The above is my solution and I hope it can help people who encounter the same problem as me.

**Comment by Kaes0n** [comment]
$env:FLASK_APP = "run.py" 
I'm working in PowerShell. It helped me. 
run.py is the start file of my Flask project, yours may be different

**Comment by adlzanchetta** [comment]
I was having the same issue. My problem was that the code:

```python
app = Flask(__name__)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
```

was present in my ```app.py``` file inside a ```if __name__ == "__main__":``` clause, but what is inside this ```if```` is just not registered by Flask.

Solution: just moved these 3 lines OUTSIDE the ```if```. They must be in the "root" of the script.

**Comment by MindaugasBernatavicius** [comment]
Solution for me was adding this: `migrate = Migrate(app, db)`

**Comment by webn1nja** [comment]
> I had this problem too - it seems to have been caused by an outdated version of something (I didn't investigate which). The solution (for me) was to upgrade flask-migrate, which in turn also updated flask and flask-sqlalchemy among other things
> 
> `pip install flask-migrate --upgrade`
> 
> Hopefully this helps someone else :)

Thanks a lot

**Comment by sunrise959** [comment]
export FLASK_APP="app.py"
try this

**Comment by Overlawd** [comment]
> Finally got it to work. Made two changes:
> 
> 1. In **init**.py, made sure that `from config import Config` came after the flask_migrate import
> 2. include `app` in the argument to `migrate = Migrate(app,db) like this:
> 
> ```
> from flask import Flask
> from flask_sqlalchemy import SQLAlchemy
> from flask_migrate import Migrate
> from config import Config
> 
> app = Flask(__name__)
> 
> app.config.from_object(Config)
> db = SQLAlchemy(app)
> migrate = Migrate(app, db)
> 
> from app import routes, models
> ```

After trying everything including the re-creation of the venv, adding the single line : 

migrate = Migrate(app, db)

to my __init__.py file fixed the Error: No such command 'db'.

Thank you kindly.
