### ISSUE TITLE
Elasticsearch query improvement

### ISSUE THREAD

**Issue by avoidik** [miguelgrinberg/microblog#70]
Hi,

Following request (which comes from tutorial) fails with the default Elasticsearch package bundled with Ubuntu. The package version is 1.7.3, and it's pretty outdated, I think this is the root cause and you will not have this problem with the latest Elasticsearch version distributed via official DEB-package.
This default package is referenced in Chapter 17.

Query:
```
curl -XPOST 'localhost:9200/_search?pretty' -d '{"query":{"multi_match":{"query":"post from","fields":["*"]}},"size":15,"from":0}'
```
Failed with the error:
```
NumberFormatException[For input string: \"post from\"];
```

Here's two possible ways to improve actual query

1. Refer exact field
```
curl -XPOST 'localhost:9200/_search?pretty' -d '{"query":{"multi_match":{"query":"post from","fields":["body"]}},"size":15,"from":0}'
```
2. Append lenient parameter
```
curl -XPOST 'localhost:9200/_search?pretty' -d '{"query":{"multi_match":{"query":"post from","fields":["*"],"lenient":true}},"size":15,"from":0}'
```

**Comment by avoidik** [comment]
search.py
```
    search = current_app.elasticsearch.search(
        index=index, doc_type=index,
        body={
            'query': {
                'multi_match': {
                    'query': query,
                    'fields': ['*'],
                    'lenient': 'true'
                }
            },
            'from': (page - 1) * per_page,
            'size': per_page
        }
    )
```

**Comment by avoidik** [comment]
Yes, but this is how you suggest to install it in Chapter 17, and query is not universal.

**Comment by miguelgrinberg** [comment]
@avoidik I have updated Chapter 17 a few days ago because I found two problems with those instructions. First is this, the elasticsearch service from Ubuntu is very old. Second, the RAM required to run this service is large. I changed the chapter to recommend skipping the installation of Elasticsearch if you are using a 512MB or 1GB server, and only do it if you have a 2GB or large server. The text now sends you to download the .deb package from elastic.co and not the Ubuntu package.

**Comment by yangxx1** [comment]
@miguelgrinberg  the __searchable__=['body'] , how to change this to several fields in Post. Besides the search can support several models?

**Comment by miguelgrinberg** [comment]
The value of the searchable argument is a list of fields that are to be included in the index. If you want to index multiple models, it's probably best to define a separate index for each model. You can use the same index if you like, but you'll need to make some changes to the `SearchableMixin` class to support that.
