### ISSUE TITLE
Dockerfile Redis

### ISSUE THREAD

**Issue by light4ever** [miguelgrinberg/microblog#73]
@miguelgrinberg In the Docker file I don't see anything regarding redis. Is background tasks going to work via the docker deployment?

I have not tried background tasks yet and I am very new to docker images.

**Comment by miguelgrinberg** [comment]
@light4ever the chapter on Docker comes first, so in that chapter no reference is made to how to deploy Redis. But in chapter 22, the last section covers how to extend the three deployment methods to include redis and rq. The changes are all done externally, no need to change anything in the Dockerfile.
