### ISSUE TITLE
SMTP AUTH extension not supported by server.

### ISSUE THREAD

**Issue by michaelangelorayco** [miguelgrinberg/microblog#76]
I'm trying to run the smtpd debugging server but whenever I run the application and force an error,
I don't get any message on my Debugging Server and the app returns this stack trace:

>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/handlers.py", line 1022, in emit
>     smtp.login(self.username, self.password)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/smtplib.py", line 697, in login
>     "SMTP AUTH extension not supported by server.")
> smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.

What am I doing wrong?

**Comment by miguelgrinberg** [comment]
The debugging server does not support authentication. Do you have email username/password configured? Remove them and I think you'll be fine.

**Comment by michaelangelorayco** [comment]
Oh. Yes you are right! It's now working, my bad. Thanks Miguel

**Comment by zhaowei699** [comment]
i have the same problem. But how to remove username/password configured?

**Comment by miguelgrinberg** [comment]
@zhaowei699 you have to remove them from your configuration.

**Comment by zhaowei699** [comment]
Thanks a lot, it is working now.

Wei Zhao
Sr. Simulation Engineer
Engineering/Development
wei.zhao@autoliv.com
Mobile: +86-18018673699
Direct: +86-21-69928489

**Comment by JaimeSilva** [comment]
how do you remove username/password from configuration?

**Comment by zhaowei699** [comment]
It is easy to remove:
See the following code, only remove smtpObj.login()

`#smtpObj.login('xxxx.xxxxx@xxxxx.com','xxxxxx')

 smtpObj.sendmail(sender, receivers, message.as_string())`

**Comment by shivambakshi** [comment]
> It is easy to remove:
> See the following code, only remove smtpObj.login()
> 
> `#smtpObj.login('[xxxx.xxxxx@xxxxx.com](mailto:xxxx.xxxxx@xxxxx.com)','xxxxxx')
> 
> smtpObj.sendmail(sender, receivers, message.as_string())`

Thank you so much for helping

**Comment by zhaowei699** [comment]
Thanks a lot
I have solved it since one year ago. Anyway, thanks a lot

Wei Zhao
Sr. Simulation Engineer
Engineering/Development
***@***.******@***.***>
Mobile: +86-18018673699
Direct: +86-021-60785703

**Comment by Palnetguy** [comment]
Hello. I have same problem here. When I try to send and email it fails yet I have set everything as needed
![Screenshot (74)](https://user-images.githubusercontent.com/72804656/132959778-258c93b3-2fd3-4e55-af92-99b206abee25.png)

**Comment by miguelgrinberg** [comment]
@Palnetguy wrong project. This repo is dedicated to the Flask Mega-Tutorial. You seem to be using Django and a completely different project.
