### ISSUE TITLE
Problem after login

### ISSUE THREAD

**Issue by Pablo2m** [miguelgrinberg/microblog#8]
**After login with my google openid, i see this traceback**

AttributeError

AttributeError: '_QueryProxy' object has no attribute 'paginate'
Traceback (most recent call last)

```
File "C:\Python27\lib\site-packages\flask\app.py", line 1701, in __call__

return self.wsgi_app(environ, start_response)

File "C:\Python27\lib\site-packages\flask\app.py", line 1689, in wsgi_app

response = self.make_response(self.handle_exception(e))

File "C:\Python27\lib\site-packages\flask\app.py", line 1687, in wsgi_app

response = self.full_dispatch_request()

File "C:\Python27\lib\site-packages\flask\app.py", line 1360, in full_dispatch_request

rv = self.handle_user_exception(e)

File "C:\Python27\lib\site-packages\flask\app.py", line 1358, in full_dispatch_request

rv = self.dispatch_request()

File "C:\Python27\lib\site-packages\flask\app.py", line 1344, in dispatch_request

return self.view_functions[rule.endpoint](**req.view_args)

File "C:\Python27\lib\site-packages\flask_login.py", line 515, in decorated_view

return fn(*args, **kwargs)

File "C:\Users\Pablo2M\Desktop\microblog-0.14\app\views.py", line 51, in index

posts = g.user.followed_posts().paginate(page, POSTS_PER_PAGE, False)

AttributeError: '_QueryProxy' object has no attribute 'paginate'
```

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

```
dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
```

**These are the packages that I have installed:**

C:\Users\Pablo2M>pip list
Babel (0.9.6)
blinker (1.2)
coverage (3.6)
decorator (3.4.0)
Flask (0.9)
Flask-Babel (0.8)
Flask-Login (0.1.3)
Flask-Mail (0.8.2)
Flask-OpenID (1.1.1)
Flask-SQLAlchemy (0.16)
Flask-WhooshAlchemy (0.54a)
Flask-WTF (0.9.4)
Warning: cannot find svn location for flup==1.0.3.dev-20110405
flup (1.0.3.dev-20110405)
guess-language (0.2)
gunicorn (0.17.2)
itsdangerous (0.23)
Jinja2 (2.6)
MarkupSafe (0.18)
oauthlib (0.6.1)
pip (1.5)
PyPump (0.4)
python-dateutil (2.2)
python-openid (2.2.5)
pytz (2013b)
requests (1.2.3)
requests-oauthlib (0.4.0)
setuptools (2.0.2)
six (1.5.2)
speaklater (1.3)
SQLAlchemy (0.7.9)
sqlalchemy-migrate (0.7.2)
Tempita (0.5.1)
Werkzeug (0.8.3)
Whoosh (2.4.1)
WTForms (1.0.3)

**Can you help me?**

**Comment by Enderthe3rd** [comment]
"Try upgrading to the latest Flask-WhooshAlchemy."
I got this error after _downgrading_ so I could do Part 16!

Is there anyway to fix this error while sticking with Whoosh 0.54a?

**Comment by miguelgrinberg** [comment]
@Enderthe3rd Flask-WhooshAlchemy used a fairly nasty trick to extend the Flask-SQLAlchemy query object. It appears that this trick does not work anymore on recent versions of Python. I think you should consider that article of interest only as a read, it would probably require finding an old version of Python 2 that allows the original query methods (such as the `paginate` that fails) to work again.

**Comment by Enderthe3rd** [comment]
@miguelgrinberg OK, sounds good to me. Thanks so much for this tutorial, it's be so helpful. I've been repurposing microblog to a project I had in mind to try. Man, you _really_ start to learn this stuff once you have to do it on your own instead of just copying someone else's work. I'm clearly going to have to learn some javascript.
