### ISSUE TITLE
Possible wrong pagination urls on index page

### ISSUE THREAD

**Issue by mikhailsidorov** [miguelgrinberg/microblog#85]
Hi, I found a possible error in the URL addresses of the Newer posts and Older posts buttons on the index page. Are the addresses correct? Details in pull request #86 .

**Comment by greyli** [comment]
Yes, they are correct.

**Comment by greyli** [comment]
The sources have changed to the correct endpoint (see [main/routes.py#L41](https://github.com/miguelgrinberg/microblog/blob/master/app/main/routes.py#L41)), you may close this issue and related PR.
