### ISSUE TITLE
Microsoft translation api  json not working

### ISSUE THREAD

**Issue by franco2ke** [miguelgrinberg/microblog#87]
Hi,

json responses are not working for the translation api, had to attempt a response in xml

**Comment by miguelgrinberg** [comment]
I just retested it here and everything works for me. I need details about your failure please.

**Comment by franco2ke** [comment]
Okay, I have tried json and still not working. 

Find the cmd line error attached as well as the code

 

 

 

Francis W. Wanyonyi

**Comment by franco2ke** [comment]
[cmd_line.txt](https://github.com/miguelgrinberg/microblog/files/1723035/cmd_line.txt)
[translate_py.txt](https://github.com/miguelgrinberg/microblog/files/1723036/translate_py.txt)

**Comment by miguelgrinberg** [comment]
Thanks. This was a bug that I had a while ago, but it is now fixed, both in this repository and in the book. It appears that you are still using the buggy version of the translate function. In particular, this line needs to be changed: https://github.com/miguelgrinberg/microblog/blob/master/app/translate.py#L19. The `utf-8` encoding needs to be `utf-8-sig` for the payloads returned by the MS Translator API.

**Comment by franco2ke** [comment]
Thanks Miguel, it worked, I think I'll update my book version just in case there are some changes.
